using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;

namespace ReactiveUITK.EditorSupport.HMR
{
    /// <summary>
    /// Generates C# source for hook body methods from a parsed DirectiveSet.
    /// The generated code is compiled into a temporary HMR assembly whose body
    /// methods are then swapped into the project assembly's delegate fields by
    /// <see cref="UitkxHmrDelegateSwapper.SwapHooks"/>.
    ///
    /// All DirectiveSet / HookDeclaration access is via reflection because
    /// <c>ReactiveUITK.Language.dll</c> is loaded dynamically at runtime.
    /// </summary>
    internal static class HmrHookEmitter
    {
        // ── Hook alias substitution (mirrors HmrCSharpEmitter) ───────────────

        private static readonly (string From, string To)[] s_hookAliases =
        {
            ("useState(", "Hooks.UseState("),
            ("useEffect(", "Hooks.UseEffect("),
            ("useLayoutEffect(", "Hooks.UseLayoutEffect("),
            ("useRef(", "Hooks.UseRef("),
            ("useCallback(", "Hooks.UseCallback("),
            ("useMemo(", "Hooks.UseMemo("),
            ("useContext(", "Hooks.UseContext("),
            ("useReducer(", "Hooks.UseReducer("),
            ("useSignal(", "Hooks.UseSignal("),
            ("useDeferredValue(", "Hooks.UseDeferredValue("),
            ("useTransition(", "Hooks.UseTransition("),
            ("useSfx(", "Hooks.UseSfx("),
            ("useUiDocumentRoot(", "Hooks.UseUiDocumentRoot("),
            ("provideContext(", "Hooks.ProvideContext("),
        };

        private static readonly Regex s_genericHookAliasRe = new Regex(
            @"\b(useState|useEffect|useLayoutEffect|useRef|useCallback|useMemo|useContext|useReducer|useSignal|useDeferredValue|useTransition)(<(?:[^<>]|<(?:[^<>]|<[^<>]*>)*>)*>)\s*\(",
            RegexOptions.Compiled
        );

        private static readonly Regex s_setterLambdaRe = new Regex(
            @"\b(set[A-Z][a-zA-Z0-9_]*)\(\s*(?=[a-zA-Z_][a-zA-Z0-9_]*\s*=>|\([^)]*\)\s*=>)",
            RegexOptions.Compiled
        );

        /// <summary>
        /// Emits C# source for all hook body methods in the given DirectiveSet.
        /// The directives object is accessed via reflection.
        /// </summary>
        /// <param name="directives">DirectiveSet (opaque — from Language.dll).</param>
        /// <param name="filePath">Absolute path to the .uitkx source file.</param>
        /// <param name="containerClassName">
        /// The container class name in the project assembly (e.g. "CounterHooks").
        /// Used as the class name in the HMR assembly so the swapper can find methods.
        /// </param>
        public static string Emit(object directives, string filePath, string containerClassName,
            bool withTrampoline = false)
        {
            string ns = (string)GetProp(directives, "Namespace") ?? "ReactiveUITK.Generated";
            var hookDecls = GetProp(directives, "HookDeclarations");

            // ImmutableArray<HookDeclaration> — enumerate via IEnumerable
            var hookList = new List<object>();
            if (hookDecls is IEnumerable enumerable)
            {
                foreach (var item in enumerable)
                    hookList.Add(item);
            }

            if (hookList.Count == 0)
                return string.Empty;

            string linePath = NormalizePath(filePath);

            var sb = new StringBuilder(2048);
            sb.AppendLine("// <auto-generated — HMR hook bodies />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("#pragma warning disable CS0105, CS8600, CS8601, CS8602, CS8603, CS8604");
            sb.AppendLine();

            // Standard usings
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using ReactiveUITK;");
            sb.AppendLine("using ReactiveUITK.Core;");
            sb.AppendLine("using ReactiveUITK.Core.Animation;");
            sb.AppendLine("using ReactiveUITK.Props.Typed;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using static ReactiveUITK.Props.Typed.StyleKeys;");
            sb.AppendLine("using static ReactiveUITK.Props.Typed.CssHelpers;");
            sb.AppendLine("using static ReactiveUITK.AssetHelpers;");
            sb.AppendLine("using UColor = UnityEngine.Color;");

            // User usings
            var usings = GetProp(directives, "Usings");
            if (usings is IEnumerable usingList)
            {
                foreach (var u in usingList)
                    sb.AppendLine($"using {u};");
            }

            sb.AppendLine("using Color = UnityEngine.Color;");
            sb.AppendLine("using EasingFunction = UnityEngine.UIElements.EasingFunction;");
            sb.AppendLine("using EasingMode = UnityEngine.UIElements.EasingMode;");
            sb.AppendLine("using BackgroundRepeat = UnityEngine.UIElements.BackgroundRepeat;");
            sb.AppendLine("using BackgroundPosition = UnityEngine.UIElements.BackgroundPosition;");
            sb.AppendLine("using BackgroundSize = UnityEngine.UIElements.BackgroundSize;");
            sb.AppendLine("using TransformOrigin = UnityEngine.UIElements.TransformOrigin;");
            sb.AppendLine("using BackgroundPositionKeyword = UnityEngine.UIElements.BackgroundPositionKeyword;");
            sb.AppendLine("using BackgroundSizeType = UnityEngine.UIElements.BackgroundSizeType;");
            sb.AppendLine("using Repeat = UnityEngine.UIElements.Repeat;");
            sb.AppendLine("using Length = UnityEngine.UIElements.Length;");
            sb.AppendLine("using StyleKeyword = UnityEngine.UIElements.StyleKeyword;");
            sb.AppendLine("using TextAutoSizeMode = UnityEngine.UIElements.TextAutoSizeMode;");
            sb.AppendLine();

            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine($"    public static class {containerClassName}");
            sb.AppendLine("    {");

            foreach (var hook in hookList)
            {
                EmitSingleHookBody(sb, hook, linePath, withTrampoline);
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// Emits C# source for all module bodies in the given DirectiveSet.
        /// </summary>
        public static string EmitModules(object directives, string filePath)
        {
            string ns = (string)GetProp(directives, "Namespace") ?? "ReactiveUITK.Generated";
            var moduleDecls = GetProp(directives, "ModuleDeclarations");

            var moduleList = new List<object>();
            if (moduleDecls is IEnumerable enumerable)
            {
                foreach (var item in enumerable)
                    moduleList.Add(item);
            }

            if (moduleList.Count == 0)
                return string.Empty;

            string linePath = NormalizePath(filePath);

            var sb = new StringBuilder(2048);
            sb.AppendLine("// <auto-generated — HMR module bodies />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("#pragma warning disable CS0105, CS8600, CS8601, CS8602, CS8603, CS8604");
            sb.AppendLine();

            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using ReactiveUITK;");
            sb.AppendLine("using ReactiveUITK.Core;");
            sb.AppendLine("using ReactiveUITK.Core.Animation;");
            sb.AppendLine("using ReactiveUITK.Props.Typed;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using static ReactiveUITK.Props.Typed.StyleKeys;");
            sb.AppendLine("using static ReactiveUITK.Props.Typed.CssHelpers;");
            sb.AppendLine("using static ReactiveUITK.AssetHelpers;");
            sb.AppendLine("using UColor = UnityEngine.Color;");

            var usings = GetProp(directives, "Usings");
            if (usings is IEnumerable usingList)
            {
                foreach (var u in usingList)
                    sb.AppendLine($"using {u};");
            }

            sb.AppendLine("using Color = UnityEngine.Color;");
            sb.AppendLine("using EasingFunction = UnityEngine.UIElements.EasingFunction;");
            sb.AppendLine("using EasingMode = UnityEngine.UIElements.EasingMode;");
            sb.AppendLine("using BackgroundRepeat = UnityEngine.UIElements.BackgroundRepeat;");
            sb.AppendLine("using BackgroundPosition = UnityEngine.UIElements.BackgroundPosition;");
            sb.AppendLine("using BackgroundSize = UnityEngine.UIElements.BackgroundSize;");
            sb.AppendLine("using TransformOrigin = UnityEngine.UIElements.TransformOrigin;");
            sb.AppendLine("using BackgroundPositionKeyword = UnityEngine.UIElements.BackgroundPositionKeyword;");
            sb.AppendLine("using BackgroundSizeType = UnityEngine.UIElements.BackgroundSizeType;");
            sb.AppendLine("using Repeat = UnityEngine.UIElements.Repeat;");
            sb.AppendLine("using Length = UnityEngine.UIElements.Length;");
            sb.AppendLine("using StyleKeyword = UnityEngine.UIElements.StyleKeyword;");
            sb.AppendLine("using TextAutoSizeMode = UnityEngine.UIElements.TextAutoSizeMode;");
            sb.AppendLine();

            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");

            foreach (var module in moduleList)
            {
                string name = (string)GetProp(module, "Name");
                int bodyStartLine = (int)GetProp(module, "BodyStartLine");
                string body = (string)GetProp(module, "Body");

                // Resolve relative Asset<T>("./x") / Ast<T>("../x") paths to absolute
                // Unity registry keys (parity with the source-gen ModuleEmitter, so HMR
                // recompiles produce identical literal strings to what UitkxAssetRegistry
                // indexes by).
                body = HmrCSharpEmitter.ResolveAssetPaths(body, filePath);

                sb.AppendLine($"    public partial class {name}");
                sb.AppendLine("    {");
                sb.AppendLine($"#line {bodyStartLine} \"{linePath}\"");
                sb.AppendLine($"        {body}");
                sb.AppendLine("#line hidden");
                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            return sb.ToString();
        }

        // ── Single hook body ──────────────────────────────────────────────────

        private static void EmitSingleHookBody(StringBuilder sb, object hook, string linePath,
            bool withTrampoline = false)
        {
            string name = (string)GetProp(hook, "Name");
            string genericParams = (string)GetProp(hook, "GenericParams");
            string returnType = (string)GetProp(hook, "ReturnType");
            string body = (string)GetProp(hook, "Body");
            int bodyStartLine = (int)GetProp(hook, "BodyStartLine");

            bool isVoid = string.IsNullOrEmpty(returnType);
            string genericSuffix = genericParams ?? string.Empty;
            string retType = isVoid ? "void" : returnType;
            string bodyMethodName = $"__{name}_body";

            // Read params via reflection (ImmutableArray<FunctionParam>)
            string paramList = BuildParamListFromReflection(hook);
            string paramNames = BuildParamNamesFromReflection(hook);
            // Apply hook aliases AND resolve relative asset paths so HMR-compiled
            // hook bodies behave identically to source-generated ones.
            string transformedBody = ApplyHookAliases(body);
            transformedBody = HmrCSharpEmitter.ResolveAssetPaths(transformedBody, linePath);

            sb.AppendLine();
            sb.AppendLine($"        public static {retType} {bodyMethodName}{genericSuffix}({paramList})");
            sb.AppendLine("        {");
            sb.AppendLine($"#line {bodyStartLine} \"{linePath}\"");
            sb.AppendLine($"            {transformedBody}");
            sb.AppendLine("#line hidden");
            sb.AppendLine("        }");

            // When emitting as a companion of a component (not for hot-swap),
            // also emit the public trampoline so the component can call
            // useXxx() directly via using-static.
            if (withTrampoline)
            {
                sb.AppendLine();
                sb.AppendLine($"        public static {retType} {name}{genericSuffix}({paramList})");
                if (isVoid)
                {
                    sb.AppendLine($"            => {bodyMethodName}{genericSuffix}({paramNames});");
                }
                else
                {
                    sb.AppendLine($"            => {bodyMethodName}{genericSuffix}({paramNames});");
                }
            }
        }

        // ── Helpers ───────────────────────────────────────────────────────────

        private static string BuildParamListFromReflection(object hook)
        {
            var paramsObj = GetProp(hook, "Params");
            if (paramsObj == null)
                return string.Empty;

            // ImmutableArray<FunctionParam> implements IEnumerable
            if (paramsObj is not IEnumerable enumerable)
                return string.Empty;

            var sb = new StringBuilder();
            int idx = 0;
            foreach (var p in enumerable)
            {
                if (idx > 0) sb.Append(", ");
                string type = (string)GetProp(p, "Type");
                string pname = (string)GetProp(p, "Name");
                sb.Append(type).Append(' ').Append(pname);

                string defaultVal = (string)GetProp(p, "DefaultValue");
                if (defaultVal != null)
                    sb.Append(" = ").Append(defaultVal);

                idx++;
            }
            return sb.ToString();
        }

        private static string BuildParamNamesFromReflection(object hook)
        {
            var paramsObj = GetProp(hook, "Params");
            if (paramsObj == null)
                return string.Empty;

            if (paramsObj is not IEnumerable enumerable)
                return string.Empty;

            var sb = new StringBuilder();
            int idx = 0;
            foreach (var p in enumerable)
            {
                if (idx > 0) sb.Append(", ");
                sb.Append((string)GetProp(p, "Name"));
                idx++;
            }
            return sb.ToString();
        }

        private static string ApplyHookAliases(string code)
        {
            code = s_setterLambdaRe.Replace(code, "$1.Set(");

            if (
                code.IndexOf("use", StringComparison.Ordinal) < 0
                && code.IndexOf("provideContext", StringComparison.Ordinal) < 0
            )
                return code;

            code = s_genericHookAliasRe.Replace(
                code,
                m =>
                {
                    string hookName = m.Groups[1].Value;
                    string typeArgs = m.Groups[2].Value;
                    string pascalName = char.ToUpper(hookName[3]) + hookName.Substring(4);
                    return $"Hooks.Use{pascalName}{typeArgs}(";
                }
            );

            foreach (var (from, to) in s_hookAliases)
                code = code.Replace(from, to);

            return code;
        }

        private static string NormalizePath(string path)
        {
            return path.Replace("\\", "/");
        }

        private static object GetProp(object obj, string propName)
        {
            // Records expose properties; use GetProperty first, then fall back to GetField
            var prop = obj.GetType().GetProperty(propName);
            if (prop != null)
                return prop.GetValue(obj);
            var field = obj.GetType().GetField(propName);
            return field?.GetValue(obj);
        }

        /// <summary>
        /// Derives the container class name from the .uitkx filename.
        /// Mirrors <c>HookEmitter.DeriveContainerClassName</c>.
        /// </summary>
        internal static string DeriveContainerClassName(string filePath)
        {
            string fileName = Path.GetFileNameWithoutExtension(filePath);
            // Strip any dot-suffix (e.g. .hooks, .style, .whatever) — the
            // file type is determined by content, not filename convention.
            int dot = fileName.IndexOf('.');
            if (dot > 0)
                fileName = fileName.Substring(0, dot);

            if (fileName.Length > 0 && char.IsLower(fileName[0]))
                fileName = char.ToUpper(fileName[0]) + fileName.Substring(1);

            return fileName + "Hooks";
        }
    }
}
