/**
 * Complete catalog of every style property in ReactiveUIToolKit.
 * Used by StylingPage to render consistent property cards.
 *
 * Each entry has:  key, name, type, description, typed example, untyped example,
 *                  related CssHelpers, category, version, shorthand info.
 *
 * Sorted by category â†’ version â†’ alphabetical.
 */

export interface PropertyCard {
  /** camelCase key used in Style dictionary, e.g. "flexGrow" */
  key: string
  /** PascalCase name used in typed Style API, e.g. "FlexGrow" */
  name: string
  /** C# type accepted by the typed property, e.g. "StyleFloat" */
  type: string
  /** One-line description */
  description: string
  /** Typed Style API example */
  typedExample: string
  /** Untyped tuple syntax example */
  untypedExample: string
  /** Related CssHelper names */
  helpers?: string[]
  /** Category for grouping */
  category: PropertyCategory
  /** Unity version where this was introduced (omit for floor) */
  sinceUnity?: string
  /** True if this is a shorthand that sets multiple properties */
  shorthand?: boolean
}

export type PropertyCategory =
  | 'Layout'
  | 'Positioning'
  | 'Spacing'
  | 'Flexbox'
  | 'Border'
  | 'Text'
  | 'Colors'
  | 'Enum Styles'
  | 'Background'
  | 'Transforms'
  | 'Assets'
  | 'Filter & Effects'
  | 'Transitions'

// ---------------------------------------------------------------------------
// The catalog
// ---------------------------------------------------------------------------

export const STYLE_PROPERTY_CATALOG: PropertyCard[] = [
  // â”€â”€ Layout â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    key: 'width',
    name: 'Width',
    type: 'StyleLength',
    category: 'Layout',
    description: 'Sets the width of the element.',
    typedExample: 'Width = Px(200)',
    untypedExample: '(StyleKeys.Width, 200f)',
    helpers: ['Px()', 'Pct()', 'StyleAuto'],
  },
  {
    key: 'height',
    name: 'Height',
    type: 'StyleLength',
    category: 'Layout',
    description: 'Sets the height of the element.',
    typedExample: 'Height = Px(100)',
    untypedExample: '(StyleKeys.Height, 100f)',
    helpers: ['Px()', 'Pct()', 'StyleAuto'],
  },
  {
    key: 'minWidth',
    name: 'MinWidth',
    type: 'StyleLength',
    category: 'Layout',
    description: 'Sets the minimum width. The element will not shrink below this.',
    typedExample: 'MinWidth = 120f',
    untypedExample: '(StyleKeys.MinWidth, 120f)',
    helpers: ['Px()', 'Pct()', 'StyleAuto'],
  },
  {
    key: 'minHeight',
    name: 'MinHeight',
    type: 'StyleLength',
    category: 'Layout',
    description: 'Sets the minimum height. The element will not shrink below this.',
    typedExample: 'MinHeight = 80f',
    untypedExample: '(StyleKeys.MinHeight, 80f)',
    helpers: ['Px()', 'Pct()', 'StyleAuto'],
  },
  {
    key: 'maxWidth',
    name: 'MaxWidth',
    type: 'StyleLength',
    category: 'Layout',
    description: 'Sets the maximum width. The element will not grow beyond this.',
    typedExample: 'MaxWidth = Pct(100)',
    untypedExample: '(StyleKeys.MaxWidth, 500f)',
    helpers: ['Px()', 'Pct()', 'StyleNone'],
  },
  {
    key: 'maxHeight',
    name: 'MaxHeight',
    type: 'StyleLength',
    category: 'Layout',
    description: 'Sets the maximum height. The element will not grow beyond this.',
    typedExample: 'MaxHeight = Pct(50)',
    untypedExample: '(StyleKeys.MaxHeight, 300f)',
    helpers: ['Px()', 'Pct()', 'StyleNone'],
  },

  // â”€â”€ Positioning â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    key: 'left',
    name: 'Left',
    type: 'StyleLength',
    category: 'Positioning',
    description: 'Offset from the left edge when position is absolute.',
    typedExample: 'Left = 0f',
    untypedExample: '(StyleKeys.Left, 0f)',
    helpers: ['Px()', 'Pct()', 'StyleAuto'],
  },
  {
    key: 'top',
    name: 'Top',
    type: 'StyleLength',
    category: 'Positioning',
    description: 'Offset from the top edge when position is absolute.',
    typedExample: 'Top = 0f',
    untypedExample: '(StyleKeys.Top, 0f)',
    helpers: ['Px()', 'Pct()', 'StyleAuto'],
  },
  {
    key: 'right',
    name: 'Right',
    type: 'StyleLength',
    category: 'Positioning',
    description: 'Offset from the right edge when position is absolute.',
    typedExample: 'Right = 0f',
    untypedExample: '(StyleKeys.Right, 0f)',
    helpers: ['Px()', 'Pct()', 'StyleAuto'],
  },
  {
    key: 'bottom',
    name: 'Bottom',
    type: 'StyleLength',
    category: 'Positioning',
    description: 'Offset from the bottom edge when position is absolute.',
    typedExample: 'Bottom = 0f',
    untypedExample: '(StyleKeys.Bottom, 0f)',
    helpers: ['Px()', 'Pct()', 'StyleAuto'],
  },

  // â”€â”€ Spacing â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    key: 'margin',
    name: 'Margin',
    type: 'StyleLength',
    category: 'Spacing',
    description: 'Shorthand that sets all four margins at once.',
    typedExample: 'Margin = 8f',
    untypedExample: '(StyleKeys.Margin, 8f)',
    helpers: ['Px()', 'Pct()', 'StyleAuto'],
    shorthand: true,
  },
  {
    key: 'marginLeft',
    name: 'MarginLeft',
    type: 'StyleLength',
    category: 'Spacing',
    description: 'Sets the left margin.',
    typedExample: 'MarginLeft = 16f',
    untypedExample: '(StyleKeys.MarginLeft, 16f)',
    helpers: ['Px()', 'Pct()', 'StyleAuto'],
  },
  {
    key: 'marginRight',
    name: 'MarginRight',
    type: 'StyleLength',
    category: 'Spacing',
    description: 'Sets the right margin.',
    typedExample: 'MarginRight = 16f',
    untypedExample: '(StyleKeys.MarginRight, 16f)',
    helpers: ['Px()', 'Pct()', 'StyleAuto'],
  },
  {
    key: 'marginTop',
    name: 'MarginTop',
    type: 'StyleLength',
    category: 'Spacing',
    description: 'Sets the top margin.',
    typedExample: 'MarginTop = 8f',
    untypedExample: '(StyleKeys.MarginTop, 8f)',
    helpers: ['Px()', 'Pct()', 'StyleAuto'],
  },
  {
    key: 'marginBottom',
    name: 'MarginBottom',
    type: 'StyleLength',
    category: 'Spacing',
    description: 'Sets the bottom margin.',
    typedExample: 'MarginBottom = 8f',
    untypedExample: '(StyleKeys.MarginBottom, 8f)',
    helpers: ['Px()', 'Pct()', 'StyleAuto'],
  },
  {
    key: 'padding',
    name: 'Padding',
    type: 'StyleLength',
    category: 'Spacing',
    description: 'Shorthand that sets all four paddings at once.',
    typedExample: 'Padding = 16f',
    untypedExample: '(StyleKeys.Padding, 16f)',
    helpers: ['Px()', 'Pct()'],
    shorthand: true,
  },
  {
    key: 'paddingLeft',
    name: 'PaddingLeft',
    type: 'StyleLength',
    category: 'Spacing',
    description: 'Sets the left padding.',
    typedExample: 'PaddingLeft = 12f',
    untypedExample: '(StyleKeys.PaddingLeft, 12f)',
    helpers: ['Px()', 'Pct()'],
  },
  {
    key: 'paddingRight',
    name: 'PaddingRight',
    type: 'StyleLength',
    category: 'Spacing',
    description: 'Sets the right padding.',
    typedExample: 'PaddingRight = 12f',
    untypedExample: '(StyleKeys.PaddingRight, 12f)',
    helpers: ['Px()', 'Pct()'],
  },
  {
    key: 'paddingTop',
    name: 'PaddingTop',
    type: 'StyleLength',
    category: 'Spacing',
    description: 'Sets the top padding.',
    typedExample: 'PaddingTop = 8f',
    untypedExample: '(StyleKeys.PaddingTop, 8f)',
    helpers: ['Px()', 'Pct()'],
  },
  {
    key: 'paddingBottom',
    name: 'PaddingBottom',
    type: 'StyleLength',
    category: 'Spacing',
    description: 'Sets the bottom padding.',
    typedExample: 'PaddingBottom = 8f',
    untypedExample: '(StyleKeys.PaddingBottom, 8f)',
    helpers: ['Px()', 'Pct()'],
  },

  // â”€â”€ Flexbox â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    key: 'flexDirection',
    name: 'FlexDirection',
    type: 'FlexDirection',
    category: 'Flexbox',
    description: 'Sets the main axis direction of flex children.',
    typedExample: 'FlexDirection = FlexColumn',
    untypedExample: '(StyleKeys.FlexDirection, "column")',
    helpers: ['FlexRow', 'FlexColumn', 'FlexRowReverse', 'FlexColumnReverse'],
  },
  {
    key: 'flexWrap',
    name: 'FlexWrap',
    type: 'Wrap',
    category: 'Flexbox',
    description: 'Controls whether flex children wrap to the next line.',
    typedExample: 'FlexWrap = WrapOn',
    untypedExample: '(StyleKeys.FlexWrap, "wrap")',
    helpers: ['WrapOn', 'WrapOff', 'WrapReverse'],
  },
  {
    key: 'flexGrow',
    name: 'FlexGrow',
    type: 'StyleFloat',
    category: 'Flexbox',
    description: 'How much this element grows to fill available space.',
    typedExample: 'FlexGrow = 1f',
    untypedExample: '(StyleKeys.FlexGrow, 1f)',
  },
  {
    key: 'flexShrink',
    name: 'FlexShrink',
    type: 'StyleFloat',
    category: 'Flexbox',
    description: 'How much this element shrinks when space is limited.',
    typedExample: 'FlexShrink = 0f',
    untypedExample: '(StyleKeys.FlexShrink, 0f)',
  },
  {
    key: 'flexBasis',
    name: 'FlexBasis',
    type: 'StyleLength',
    category: 'Flexbox',
    description: 'The initial main-axis size before growing or shrinking.',
    typedExample: 'FlexBasis = Pct(50)',
    untypedExample: '(StyleKeys.FlexBasis, 200f)',
    helpers: ['Px()', 'Pct()', 'StyleAuto'],
  },
  {
    key: 'justifyContent',
    name: 'JustifyContent',
    type: 'Justify',
    category: 'Flexbox',
    description: 'Aligns children along the main axis.',
    typedExample: 'JustifyContent = JustifySpaceBetween',
    untypedExample: '(StyleKeys.JustifyContent, "center")',
    helpers: ['JustifyStart', 'JustifyEnd', 'JustifyCenter', 'JustifySpaceBetween', 'JustifySpaceAround', 'JustifySpaceEvenly'],
  },
  {
    key: 'alignItems',
    name: 'AlignItems',
    type: 'Align',
    category: 'Flexbox',
    description: 'Aligns children along the cross axis.',
    typedExample: 'AlignItems = AlignCenter',
    untypedExample: '(StyleKeys.AlignItems, "center")',
    helpers: ['AlignStart', 'AlignEnd', 'AlignCenter', 'AlignStretch', 'AlignAuto'],
  },
  {
    key: 'alignSelf',
    name: 'AlignSelf',
    type: 'Align',
    category: 'Flexbox',
    description: 'Overrides the parent\u2019s alignItems for this element.',
    typedExample: 'AlignSelf = AlignStretch',
    untypedExample: '(StyleKeys.AlignSelf, "stretch")',
    helpers: ['AlignStart', 'AlignEnd', 'AlignCenter', 'AlignStretch', 'AlignAuto'],
  },
  {
    key: 'alignContent',
    name: 'AlignContent',
    type: 'Align',
    category: 'Flexbox',
    description: 'Aligns wrapped flex lines along the cross axis.',
    typedExample: 'AlignContent = AlignCenter',
    untypedExample: '(StyleKeys.AlignContent, "center")',
    helpers: ['AlignStart', 'AlignEnd', 'AlignCenter', 'AlignStretch', 'AlignAuto'],
  },

  // â”€â”€ Border â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    key: 'borderWidth',
    name: 'BorderWidth',
    type: 'StyleFloat',
    category: 'Border',
    description: 'Shorthand that sets all four border widths at once.',
    typedExample: 'BorderWidth = 2f',
    untypedExample: '(StyleKeys.BorderWidth, 2f)',
    shorthand: true,
  },
  {
    key: 'borderLeftWidth',
    name: 'BorderLeftWidth',
    type: 'StyleFloat',
    category: 'Border',
    description: 'Sets the left border width.',
    typedExample: 'BorderLeftWidth = 1f',
    untypedExample: '(StyleKeys.BorderLeftWidth, 1f)',
  },
  {
    key: 'borderRightWidth',
    name: 'BorderRightWidth',
    type: 'StyleFloat',
    category: 'Border',
    description: 'Sets the right border width.',
    typedExample: 'BorderRightWidth = 1f',
    untypedExample: '(StyleKeys.BorderRightWidth, 1f)',
  },
  {
    key: 'borderTopWidth',
    name: 'BorderTopWidth',
    type: 'StyleFloat',
    category: 'Border',
    description: 'Sets the top border width.',
    typedExample: 'BorderTopWidth = 1f',
    untypedExample: '(StyleKeys.BorderTopWidth, 1f)',
  },
  {
    key: 'borderBottomWidth',
    name: 'BorderBottomWidth',
    type: 'StyleFloat',
    category: 'Border',
    description: 'Sets the bottom border width.',
    typedExample: 'BorderBottomWidth = 1f',
    untypedExample: '(StyleKeys.BorderBottomWidth, 1f)',
  },
  {
    key: 'borderColor',
    name: 'BorderColor',
    type: 'Color',
    category: 'Border',
    description: 'Shorthand that sets all four border colors at once.',
    typedExample: 'BorderColor = ColorRed',
    untypedExample: '(StyleKeys.BorderColor, Color.red)',
    helpers: ['Hex()', 'Rgba()', 'ColorWhite', 'ColorBlack', 'ColorRed'],
    shorthand: true,
  },
  {
    key: 'borderLeftColor',
    name: 'BorderLeftColor',
    type: 'Color',
    category: 'Border',
    description: 'Sets the left border color.',
    typedExample: 'BorderLeftColor = Hex("#ccc")',
    untypedExample: '(StyleKeys.BorderLeftColor, Color.grey)',
    helpers: ['Hex()', 'Rgba()', 'ColorWhite', 'ColorBlack'],
  },
  {
    key: 'borderRightColor',
    name: 'BorderRightColor',
    type: 'Color',
    category: 'Border',
    description: 'Sets the right border color.',
    typedExample: 'BorderRightColor = Hex("#ccc")',
    untypedExample: '(StyleKeys.BorderRightColor, Color.grey)',
    helpers: ['Hex()', 'Rgba()', 'ColorWhite', 'ColorBlack'],
  },
  {
    key: 'borderTopColor',
    name: 'BorderTopColor',
    type: 'Color',
    category: 'Border',
    description: 'Sets the top border color.',
    typedExample: 'BorderTopColor = ColorWhite',
    untypedExample: '(StyleKeys.BorderTopColor, Color.white)',
    helpers: ['Hex()', 'Rgba()', 'ColorWhite', 'ColorBlack'],
  },
  {
    key: 'borderBottomColor',
    name: 'BorderBottomColor',
    type: 'Color',
    category: 'Border',
    description: 'Sets the bottom border color.',
    typedExample: 'BorderBottomColor = ColorWhite',
    untypedExample: '(StyleKeys.BorderBottomColor, Color.white)',
    helpers: ['Hex()', 'Rgba()', 'ColorWhite', 'ColorBlack'],
  },
  {
    key: 'borderRadius',
    name: 'BorderRadius',
    type: 'StyleLength',
    category: 'Border',
    description: 'Shorthand that sets all four corner radii at once.',
    typedExample: 'BorderRadius = 8f',
    untypedExample: '(StyleKeys.BorderRadius, 8f)',
    helpers: ['Px()', 'Pct()'],
    shorthand: true,
  },
  {
    key: 'borderTopLeftRadius',
    name: 'BorderTopLeftRadius',
    type: 'StyleLength',
    category: 'Border',
    description: 'Sets the top-left corner radius.',
    typedExample: 'BorderTopLeftRadius = Px(12)',
    untypedExample: '(StyleKeys.BorderTopLeftRadius, 12f)',
    helpers: ['Px()', 'Pct()'],
  },
  {
    key: 'borderTopRightRadius',
    name: 'BorderTopRightRadius',
    type: 'StyleLength',
    category: 'Border',
    description: 'Sets the top-right corner radius.',
    typedExample: 'BorderTopRightRadius = Px(12)',
    untypedExample: '(StyleKeys.BorderTopRightRadius, 12f)',
    helpers: ['Px()', 'Pct()'],
  },
  {
    key: 'borderBottomLeftRadius',
    name: 'BorderBottomLeftRadius',
    type: 'StyleLength',
    category: 'Border',
    description: 'Sets the bottom-left corner radius.',
    typedExample: 'BorderBottomLeftRadius = Px(4)',
    untypedExample: '(StyleKeys.BorderBottomLeftRadius, 4f)',
    helpers: ['Px()', 'Pct()'],
  },
  {
    key: 'borderBottomRightRadius',
    name: 'BorderBottomRightRadius',
    type: 'StyleLength',
    category: 'Border',
    description: 'Sets the bottom-right corner radius.',
    typedExample: 'BorderBottomRightRadius = Px(4)',
    untypedExample: '(StyleKeys.BorderBottomRightRadius, 4f)',
    helpers: ['Px()', 'Pct()'],
  },

  // â”€â”€ Text â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    key: 'fontSize',
    name: 'FontSize',
    type: 'StyleLength',
    category: 'Text',
    description: 'Sets the font size.',
    typedExample: 'FontSize = 24f',
    untypedExample: '(StyleKeys.FontSize, 24f)',
    helpers: ['Px()', 'Pct()'],
  },
  {
    key: 'letterSpacing',
    name: 'LetterSpacing',
    type: 'StyleLength',
    category: 'Text',
    description: 'Sets the spacing between characters.',
    typedExample: 'LetterSpacing = 1.5f',
    untypedExample: '(StyleKeys.LetterSpacing, 1.5f)',
    helpers: ['Px()'],
  },
  {
    key: 'textAlign',
    name: 'TextAlign',
    type: 'TextAnchor',
    category: 'Text',
    description: 'Sets the horizontal and vertical text alignment.',
    typedExample: 'TextAlign = TextMiddleCenter',
    untypedExample: '(StyleKeys.TextAlign, "center")',
    helpers: ['TextUpperLeft', 'TextUpperCenter', 'TextUpperRight', 'TextMiddleLeft', 'TextMiddleCenter', 'TextMiddleRight', 'TextLowerLeft', 'TextLowerCenter', 'TextLowerRight'],
  },
  {
    key: 'textOverflow',
    name: 'TextOverflow',
    type: 'TextOverflow',
    category: 'Text',
    description: 'How overflowing text is handled (clip or show ellipsis).',
    typedExample: 'TextOverflow = TextEllipsis',
    untypedExample: '(StyleKeys.TextOverflow, "ellipsis")',
    helpers: ['TextClip', 'TextEllipsis'],
  },
  {
    key: 'unityFontStyle',
    name: 'UnityFontStyle',
    type: 'FontStyle',
    category: 'Text',
    description: 'Sets the font weight and style (bold, italic, etc.).',
    typedExample: 'UnityFontStyle = FontBold',
    untypedExample: '(StyleKeys.UnityFontStyle, "bold")',
    helpers: ['FontBold', 'FontItalic', 'FontBoldItalic', 'FontNormal'],
  },
  {
    key: 'unityTextOutlineColor',
    name: 'UnityTextOutlineColor',
    type: 'Color',
    category: 'Text',
    description: 'Sets the text outline color.',
    typedExample: 'UnityTextOutlineColor = ColorBlack',
    untypedExample: '(StyleKeys.UnityTextOutlineColor, Color.black)',
    helpers: ['Hex()', 'Rgba()', 'ColorWhite', 'ColorBlack'],
  },
  {
    key: 'unityTextOutlineWidth',
    name: 'UnityTextOutlineWidth',
    type: 'StyleFloat',
    category: 'Text',
    description: 'Sets the text outline width.',
    typedExample: 'UnityTextOutlineWidth = 1f',
    untypedExample: '(StyleKeys.UnityTextOutlineWidth, 1f)',
  },
  {
    key: 'unityTextOverflowPosition',
    name: 'UnityTextOverflowPosition',
    type: 'TextOverflowPosition',
    category: 'Text',
    description: 'Where the ellipsis appears when text overflows.',
    typedExample: 'UnityTextOverflowPosition = TextOverflowMiddle',
    untypedExample: '(StyleKeys.UnityTextOverflowPosition, "middle")',
    helpers: ['TextOverflowStart', 'TextOverflowMiddle', 'TextOverflowEnd'],
  },
  {
    key: 'wordSpacing',
    name: 'WordSpacing',
    type: 'StyleLength',
    category: 'Text',
    description: 'Sets the spacing between words.',
    typedExample: 'WordSpacing = 2f',
    untypedExample: '(StyleKeys.WordSpacing, 2f)',
    helpers: ['Px()'],
  },
  {
    key: 'unityParagraphSpacing',
    name: 'UnityParagraphSpacing',
    type: 'StyleLength',
    category: 'Text',
    description: 'Sets the spacing between paragraphs (between newline-separated runs).',
    typedExample: 'UnityParagraphSpacing = 4f',
    untypedExample: '(StyleKeys.UnityParagraphSpacing, 4f)',
    helpers: ['Px()'],
  },
  {
    key: 'textShadow',
    name: 'TextShadow',
    type: 'TextShadow',
    category: 'Text',
    description: 'Casts a drop shadow behind text. Combines an offset, blur radius, and color.',
    typedExample: 'TextShadow = Shadow(2, 2, 4, ColorBlack)',
    untypedExample: '(StyleKeys.TextShadow, new TextShadow { offset = new Vector2(2,2), blurRadius = 4, color = Color.black })',
    helpers: ['Shadow(dx, dy, blur, color)'],
  },
  {
    key: 'unityTextGenerator',
    name: 'UnityTextGenerator',
    type: 'TextGeneratorType',
    category: 'Text',
    description: 'Selects the text generator: Standard (legacy IMGUI) or Advanced (TextCore, supports rich shaping & emoji).',
    typedExample: 'UnityTextGenerator = TextGenAdvanced',
    untypedExample: '(StyleKeys.UnityTextGenerator, "advanced")',
    helpers: ['TextGenStandard', 'TextGenAdvanced'],
  },
  {
    key: 'unityEditorTextRenderingMode',
    name: 'UnityEditorTextRenderingMode',
    type: 'EditorTextRenderingMode',
    category: 'Text',
    description: 'Editor-only: chooses SDF (signed-distance-field, sharper at any zoom) or Bitmap text rendering. Has no effect at runtime in players.',
    typedExample: 'UnityEditorTextRenderingMode = EditorTextSDF',
    untypedExample: '(StyleKeys.UnityEditorTextRenderingMode, "sdf")',
    helpers: ['EditorTextSDF', 'EditorTextBitmap'],
  },

  // â”€â”€ Colors â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    key: 'color',
    name: 'Color',
    type: 'Color',
    category: 'Colors',
    description: 'Sets the text color.',
    typedExample: 'Color = ColorWhite',
    untypedExample: '(StyleKeys.Color, Color.white)',
    helpers: ['Hex()', 'Rgba()', 'ColorWhite', 'ColorBlack', 'ColorRed', 'ColorTransparent'],
  },
  {
    key: 'backgroundColor',
    name: 'BackgroundColor',
    type: 'Color',
    category: 'Colors',
    description: 'Sets the background color of the element.',
    typedExample: 'BackgroundColor = Hex("#1a1a2e")',
    untypedExample: '(StyleKeys.BackgroundColor, new Color(0.1f, 0.1f, 0.18f))',
    helpers: ['Hex()', 'Rgba()', 'ColorWhite', 'ColorBlack'],
  },
  {
    key: 'backgroundImageTint',
    name: 'BackgroundImageTint',
    type: 'Color',
    category: 'Colors',
    description: 'Tints the background image with a color.',
    typedExample: 'BackgroundImageTint = Rgba(255, 200, 200)',
    untypedExample: '(StyleKeys.BackgroundImageTint, Color.red)',
    helpers: ['Hex()', 'Rgba()', 'ColorWhite', 'ColorBlack'],
  },

  // â”€â”€ Enum Styles â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    key: 'position',
    name: 'Position',
    type: 'Position',
    category: 'Enum Styles',
    description: 'Sets the positioning mode (relative or absolute).',
    typedExample: 'Position = PosAbsolute',
    untypedExample: '(StyleKeys.Position, "absolute")',
    helpers: ['PosRelative', 'PosAbsolute'],
  },
  {
    key: 'display',
    name: 'Display',
    type: 'DisplayStyle',
    category: 'Enum Styles',
    description: 'Shows or hides the element (flex or none).',
    typedExample: 'Display = DisplayNone',
    untypedExample: '(StyleKeys.Display, "none")',
    helpers: ['DisplayFlex', 'DisplayNone'],
  },
  {
    key: 'visibility',
    name: 'Visibility',
    type: 'Visibility',
    category: 'Enum Styles',
    description: 'Controls visibility. Unlike display, the element still takes space when hidden.',
    typedExample: 'Visibility = VisHidden',
    untypedExample: '(StyleKeys.Visibility, "hidden")',
    helpers: ['VisVisible', 'VisHidden'],
  },
  {
    key: 'overflow',
    name: 'Overflow',
    type: 'Overflow',
    category: 'Enum Styles',
    description: 'How content that overflows the element bounds is handled.',
    typedExample: 'Overflow = OverflowHidden',
    untypedExample: '(StyleKeys.Overflow, "hidden")',
    helpers: ['OverflowVisible', 'OverflowHidden'],
  },
  {
    key: 'opacity',
    name: 'Opacity',
    type: 'StyleFloat',
    category: 'Enum Styles',
    description: 'Sets the overall opacity of the element (0 = transparent, 1 = opaque).',
    typedExample: 'Opacity = 0.5f',
    untypedExample: '(StyleKeys.Opacity, 0.5f)',
  },
  {
    key: 'whiteSpace',
    name: 'WhiteSpace',
    type: 'WhiteSpace',
    category: 'Enum Styles',
    description: 'Controls whether text wraps to the next line.',
    typedExample: 'WhiteSpace = WsNowrap',
    untypedExample: '(StyleKeys.WhiteSpace, "nowrap")',
    helpers: ['WsNormal', 'WsNowrap', 'WsPre', 'WsPreWrap'],
  },
  {
    key: 'unityOverflowClipBox',
    name: 'UnityOverflowClipBox',
    type: 'OverflowClipBox',
    category: 'Enum Styles',
    description: 'When Overflow is Hidden, chooses whether content is clipped at the padding box or the content box.',
    typedExample: 'UnityOverflowClipBox = ClipPaddingBox',
    untypedExample: '(StyleKeys.UnityOverflowClipBox, "padding-box")',
    helpers: ['ClipPaddingBox', 'ClipContentBox'],
  },

  // â”€â”€ Background â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    key: 'backgroundImage',
    name: 'BackgroundImage',
    type: 'Texture2D',
    category: 'Background',
    description: 'Sets a background image from a Texture2D or Sprite.',
    typedExample: 'BackgroundImage = myTexture',
    untypedExample: '(StyleKeys.BackgroundImage, myTexture)',
  },
  {
    key: 'backgroundRepeat',
    name: 'BackgroundRepeat',
    type: 'BackgroundRepeat',
    category: 'Background',
    description: 'Controls how the background image tiles.',
    typedExample: 'BackgroundRepeat = BgRepeatNone',
    untypedExample: '(StyleKeys.BackgroundRepeat, "no-repeat")',
    helpers: ['BgRepeat(x, y)', 'BgRepeatNone', 'BgRepeatBoth', 'BgRepeatX', 'BgRepeatY', 'BgRepeatSpace', 'BgRepeatRound'],
  },
  {
    key: 'backgroundPositionX',
    name: 'BackgroundPositionX',
    type: 'BackgroundPosition',
    category: 'Background',
    description: 'Horizontal position of the background image.',
    typedExample: 'BackgroundPositionX = BgPosCenter',
    untypedExample: '(StyleKeys.BackgroundPositionX, "center")',
    helpers: ['BgPos(keyword)', 'BgPos(keyword, offset)', 'BgPosCenter', 'BgPosLeft', 'BgPosRight'],
  },
  {
    key: 'backgroundPositionY',
    name: 'BackgroundPositionY',
    type: 'BackgroundPosition',
    category: 'Background',
    description: 'Vertical position of the background image.',
    typedExample: 'BackgroundPositionY = BgPosCenter',
    untypedExample: '(StyleKeys.BackgroundPositionY, "center")',
    helpers: ['BgPos(keyword)', 'BgPos(keyword, offset)', 'BgPosCenter', 'BgPosTop', 'BgPosBottom'],
  },
  {
    key: 'backgroundSize',
    name: 'BackgroundSize',
    type: 'BackgroundSize',
    category: 'Background',
    description: 'Controls the size of the background image.',
    typedExample: 'BackgroundSize = BgSizeCover',
    untypedExample: '(StyleKeys.BackgroundSize, "cover")',
    helpers: ['BgSize(x, y)', 'BgSizeCover', 'BgSizeContain'],
  },
  {
    key: 'unitySliceLeft',
    name: 'UnitySliceLeft',
    type: 'StyleInt',
    description: '9-slice left border in pixels. Only takes effect when BackgroundImage is set to a 9-slice texture.',
    category: 'Background',
    typedExample: 'UnitySliceLeft = 12',
    untypedExample: '(StyleKeys.UnitySliceLeft, 12)',
  },
  {
    key: 'unitySliceRight',
    name: 'UnitySliceRight',
    type: 'StyleInt',
    description: '9-slice right border in pixels.',
    category: 'Background',
    typedExample: 'UnitySliceRight = 12',
    untypedExample: '(StyleKeys.UnitySliceRight, 12)',
  },
  {
    key: 'unitySliceTop',
    name: 'UnitySliceTop',
    type: 'StyleInt',
    description: '9-slice top border in pixels.',
    category: 'Background',
    typedExample: 'UnitySliceTop = 12',
    untypedExample: '(StyleKeys.UnitySliceTop, 12)',
  },
  {
    key: 'unitySliceBottom',
    name: 'UnitySliceBottom',
    type: 'StyleInt',
    description: '9-slice bottom border in pixels.',
    category: 'Background',
    typedExample: 'UnitySliceBottom = 12',
    untypedExample: '(StyleKeys.UnitySliceBottom, 12)',
  },
  {
    key: 'unitySliceScale',
    name: 'UnitySliceScale',
    type: 'StyleFloat',
    description: 'Multiplier applied to all 9-slice borders. Use to upscale slice borders alongside DPI.',
    category: 'Background',
    typedExample: 'UnitySliceScale = 1f',
    untypedExample: '(StyleKeys.UnitySliceScale, 1f)',
  },
  {
    key: 'unitySliceType',
    name: 'UnitySliceType',
    type: 'SliceType',
    description: 'How the center region of a 9-slice fills its area: Sliced (stretched) or Tiled (repeated).',
    category: 'Background',
    typedExample: 'UnitySliceType = SliceFill',
    untypedExample: '(StyleKeys.UnitySliceType, "tiled")',
    helpers: ['SliceFill', 'SliceTile'],
  },

  // â”€â”€ Transforms â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    key: 'rotate',
    name: 'Rotate',
    type: 'float',
    category: 'Transforms',
    description: 'Rotates the element by the given degrees.',
    typedExample: 'Rotate = 45f',
    untypedExample: '(StyleKeys.Rotate, 45f)',
  },
  {
    key: 'scale',
    name: 'Scale',
    type: 'float',
    category: 'Transforms',
    description: 'Scales the element uniformly. Values > 1 enlarge, < 1 shrink.',
    typedExample: 'Scale = 1.2f',
    untypedExample: '(StyleKeys.Scale, 1.2f)',
  },
  {
    key: 'translate',
    name: 'Translate',
    type: 'Translate',
    category: 'Transforms',
    description: 'Moves the element by the given X/Y offset.',
    typedExample: 'Translate = Xlate(Px(10), Px(-5))',
    untypedExample: '(StyleKeys.Translate, new Translate(...))',
    helpers: ['Xlate(x, y)'],
  },
  {
    key: 'transformOrigin',
    name: 'TransformOrigin',
    type: 'TransformOrigin',
    category: 'Transforms',
    description: 'Sets the pivot point for rotate, scale, and translate.',
    typedExample: 'TransformOrigin = OriginCenter',
    untypedExample: '(StyleKeys.TransformOrigin, new TransformOrigin(...))',
    helpers: ['Origin(x, y)', 'OriginCenter'],
  },

  // â”€â”€ Assets â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    key: 'fontFamily',
    name: 'FontFamily',
    type: 'Font',
    category: 'Assets',
    description: 'Sets the font used for text rendering.',
    typedExample: 'FontFamily = myFont',
    untypedExample: '(StyleKeys.FontFamily, myFont)',
  },
  {
    key: 'unityFontDefinition',
    name: 'UnityFontDefinition',
    type: 'FontDefinition',
    category: 'Assets',
    description: 'Advanced font binding. Wraps either a legacy Font or a TextCore FontAsset for the Advanced text generator.',
    typedExample: 'UnityFontDefinition = FontDef(myFont)',
    untypedExample: '(StyleKeys.UnityFontDefinition, FontDefinition.FromFont(myFont))',
    helpers: ['FontDef(font)'],
  },

  // â”€â”€ Filter & Effects (Unity 6.3+) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    key: 'aspectRatio',
    name: 'AspectRatio',
    type: 'StyleRatio',
    category: 'Filter & Effects',
    sinceUnity: '6000.3',
    description: 'Sets the preferred aspect ratio (width / height). The layout engine uses this when one dimension is auto.',
    typedExample: 'AspectRatio = new StyleRatio(new Ratio(16, 9))',
    untypedExample: '(StyleKeys.AspectRatio, new StyleRatio(new Ratio(16, 9)))',
  },
  {
    key: 'filter',
    name: 'Filter',
    type: 'StyleList<FilterFunction>',
    category: 'Filter & Effects',
    sinceUnity: '6000.3',
    description: 'Applies graphical filter effects (blur, grayscale, etc.). Multiple filters can be chained.',
    typedExample: 'Filter = new StyleList<FilterFunction>(\\n    new List<FilterFunction> { FilterBlur(4), FilterGrayscale(0.5f) })',
    untypedExample: '(StyleKeys.Filter, new StyleList<FilterFunction>(...))',
    helpers: ['FilterBlur()', 'FilterGrayscale()', 'FilterContrast()', 'FilterHueRotate()', 'FilterInvert()', 'FilterOpacity()', 'FilterSepia()', 'FilterTint()'],
  },
  {
    key: 'unityMaterial',
    name: 'UnityMaterial',
    type: 'StyleMaterialDefinition',
    category: 'Filter & Effects',
    sinceUnity: '6000.3',
    description: 'Assigns a Unity Material (Shader Graph or built-in) for custom rendering. Useful for shader-driven effects.',
    typedExample: 'UnityMaterial = new StyleMaterialDefinition(\n    new MaterialDefinition(myMaterial))',
    untypedExample: '(StyleKeys.UnityMaterial, new StyleMaterialDefinition(...))',
  },

  // ── Transitions ─────────────────────────────────────────────────────
  {
    key: 'transitionProperty',
    name: 'TransitionProperty',
    type: 'StyleList<StylePropertyName>',
    category: 'Transitions',
    description: 'Specifies which style properties to animate when their values change.',
    typedExample: 'TransitionProperty = new List<StylePropertyName>\n    { new("opacity"), new("width") }',
    untypedExample: '(StyleKeys.TransitionProperty, new List<StylePropertyName> { new("opacity") })',
  },
  {
    key: 'transitionDuration',
    name: 'TransitionDuration',
    type: 'StyleList<TimeValue>',
    category: 'Transitions',
    description: 'How long each transition takes to complete.',
    typedExample: 'TransitionDuration = new List<TimeValue>\n    { new(0.3f, TimeUnit.Second) }',
    untypedExample: '(StyleKeys.TransitionDuration, new List<TimeValue> { new(0.3f, TimeUnit.Second) })',
  },
  {
    key: 'transitionDelay',
    name: 'TransitionDelay',
    type: 'StyleList<TimeValue>',
    category: 'Transitions',
    description: 'How long to wait before starting each transition.',
    typedExample: 'TransitionDelay = new List<TimeValue>\n    { new(0f, TimeUnit.Second) }',
    untypedExample: '(StyleKeys.TransitionDelay, new List<TimeValue> { new(0f, TimeUnit.Second) })',
  },
  {
    key: 'transitionTimingFunction',
    name: 'TransitionTimingFunction',
    type: 'StyleList<EasingFunction>',
    category: 'Transitions',
    description: 'The easing curve for each transition (e.g. ease-in, ease-out, linear).',
    typedExample: 'TransitionTimingFunction = new List<EasingFunction>\n    { EaseInOut }',
    untypedExample: '(StyleKeys.TransitionTimingFunction, "ease-in-out")',
    helpers: ['Easing(mode)', 'EaseDefault', 'EaseLinear', 'EaseIn', 'EaseOut', 'EaseInOut', '+ sine/cubic/circ/elastic/back/bounce'],
  },
]

// ---------------------------------------------------------------------------
// Category ordering for the page
// ---------------------------------------------------------------------------

export const CATEGORY_ORDER: PropertyCategory[] = [
  'Layout',
  'Positioning',
  'Spacing',
  'Flexbox',
  'Border',
  'Text',
  'Colors',
  'Enum Styles',
  'Background',
  'Transforms',
  'Assets',
  'Filter & Effects',
  'Transitions',
]
