using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using ReactiveUITK.Language;
using ReactiveUITK.Language.Nodes;
using ReactiveUITK.Language.Parser;

namespace ReactiveUITK.SourceGenerator.Emitter
{
    /// <summary>
    /// Phase 4 — walks the AST produced by <see cref="UitkxParser"/> and emits a
    /// compilable C# partial-class source string.
    ///
    /// Output structure:
    /// <code>
    ///   // &lt;auto-generated /&gt;
    ///   namespace {Namespace}
    ///   {
    ///       public partial class {ComponentName}
    ///       {
    ///           private static VirtualNode[] __C(params object[] items) { ... }
    ///
    ///           public static VirtualNode Render(
    ///               Dictionary&lt;string,object&gt; __rawProps,
    ///               IReadOnlyList&lt;VirtualNode&gt; __children)
    ///           {
    ///               var props = ...;        // @props binding, if declared
    ///               // @code block content
    ///   #line N "File.uitkx"
    ///               return V.XXX(...);
    ///           }
    ///       }
    ///   }
    /// </code>
    ///
    /// The <c>#line</c> directives map generated C# lines back to the .uitkx source
    /// so that compiler errors and debugger breakpoints point at the template file.
    /// </summary>
    public static class CSharpEmitter
    {
        public static string Emit(
            string filePath,
            DirectiveSet directives,
            ImmutableArray<AstNode> rootNodes,
            PropsResolver resolver,
            IList<Diagnostic> diagnostics
        )
        {
            var ctx = new EmitContext(filePath, directives, resolver, diagnostics);
            return ctx.BuildSource(rootNodes);
        }
    }

    // ── Implementation ────────────────────────────────────────────────────────

    internal sealed class EmitContext
    {
        private readonly string _filePath;
        private readonly string _displayName; // bare filename for headers/diagnostics
        private readonly string _linePath; // normalized absolute path for #line directives
        private readonly DirectiveSet _directives;
        private readonly PropsResolver _resolver;
        private readonly IList<Diagnostic> _diagnostics;
        private readonly StringBuilder _sb = new StringBuilder(4096);
        private bool _isRootElement = true; // tracks whether the next element is the root

        // Indent constants
        private const string I2 = "        "; // 8sp — class member level
        private const string I3 = "            "; // 12sp — method body level
        private const string I4 = "                "; // 16sp — inside __C args

        private const string QVNode = "global::ReactiveUITK.Core.VirtualNode";

        internal EmitContext(
            string filePath,
            DirectiveSet directives,
            PropsResolver resolver,
            IList<Diagnostic> diagnostics
        )
        {
            _filePath = filePath;
            _directives = directives;
            _resolver = resolver;
            _diagnostics = diagnostics;
            _displayName = Path.GetFileName(filePath);
            _linePath = NormalizeLinePath(filePath);
        }

        // ── Top-level builder ─────────────────────────────────────────────────

        internal string BuildSource(ImmutableArray<AstNode> rootNodes)
        {
            // Separate markup from non-rendering nodes
            var markupNodes = ImmutableArray.CreateBuilder<AstNode>();

            foreach (var n in rootNodes)
            {
                if (n is CommentNode) { } // comments are markup-only; skip in emitted C#
                else
                    markupNodes.Add(n);
            }

            // ── Header ───────────────────────────────────────────────────────
            L("// <auto-generated — do not edit — source: " + _displayName + " />");
            L("// Add class members or partial methods in the companion .cs file.");
            L("#nullable enable");
            L("#pragma warning disable CS0105  // duplicate using directives");
            L("#pragma warning disable CS8600  // null literal to non-nullable");
            L("#pragma warning disable CS8601  // null literal to nullable reference type");
            L("#pragma warning disable CS8602  // dereference of possibly null reference");
            L("#pragma warning disable CS8603  // possible null reference return");
            L("#pragma warning disable CS8604  // possible null reference argument");
            L("");

            // ── Usings ───────────────────────────────────────────────────────
            L("using System;");
            L("using System.Collections.Generic;");
            L("using System.Linq;");
            L("using ReactiveUITK;");
            L("using ReactiveUITK.Core;");
            L("using ReactiveUITK.Core.Animation;");
            L("using ReactiveUITK.Props.Typed;");
            L("using static ReactiveUITK.Props.Typed.StyleKeys;");
            L("using static ReactiveUITK.Props.Typed.CssHelpers;");
            L("using static ReactiveUITK.AssetHelpers;");
            L("using UColor = UnityEngine.Color;");
            foreach (var u in _directives.Usings)
                L($"using {u};");
            // `using static StyleKeys` imports string constants (e.g. FlexDirection = "flexDirection")
            // that collide with identically-named enums/structs from UnityEngine.UIElements.
            // We cannot import UIElements wholesale. Instead, targeted aliases import only
            // the non-conflicting types that CssHelpers returns and users may reference.
            L("using Color = UnityEngine.Color;");
            L("using EasingFunction = UnityEngine.UIElements.EasingFunction;");
            L("using EasingMode = UnityEngine.UIElements.EasingMode;");
            L("using BackgroundRepeat = UnityEngine.UIElements.BackgroundRepeat;");
            L("using BackgroundPosition = UnityEngine.UIElements.BackgroundPosition;");
            L("using BackgroundSize = UnityEngine.UIElements.BackgroundSize;");
            L("using TransformOrigin = UnityEngine.UIElements.TransformOrigin;");
            L(
                "using BackgroundPositionKeyword = UnityEngine.UIElements.BackgroundPositionKeyword;"
            );
            L("using BackgroundSizeType = UnityEngine.UIElements.BackgroundSizeType;");
            L("using Repeat = UnityEngine.UIElements.Repeat;");
            L("using Length = UnityEngine.UIElements.Length;");
            L("using StyleKeyword = UnityEngine.UIElements.StyleKeyword;");
            L("using TextAutoSizeMode = UnityEngine.UIElements.TextAutoSizeMode;");
            L("");

            // ── Namespace + class ────────────────────────────────────────────
            L($"namespace {_directives.Namespace}");
            L("{");
            L($"    [global::ReactiveUITK.UitkxSource(@\"{_filePath.Replace("\"", "\"\"")}\")]");
            L($"    [global::ReactiveUITK.UitkxElement(\"{_directives.ComponentName}\")]");

            // Emit hook signature for proactive HMR state-reset detection
            string hookSig = ExtractHookSignature(_directives.FunctionSetupCode);
            if (hookSig.Length > 0)
                L($"    [global::ReactiveUITK.HookSignature(\"{hookSig}\")]");

            L($"    public partial class {_directives.ComponentName}");
            L("    {");

            EmitHelperMethod();

            // ── @inject fields ────────────────────────────────────────────────
            // Each @inject directive emits a static field.  Set the value in the
            // companion (non-generated) partial class or via a static initialiser.
            if (!_directives.Injects.IsDefault && !_directives.Injects.IsEmpty)
            {
                L($"{I2}// @inject — set these fields before calling Render.");
                foreach (var inj in _directives.Injects)
                    L($"{I2}public static {inj.Type} {inj.Name};");
                L("");
            }

            // ── @uss stylesheet keys ──────────────────────────────────────────
            if (!_directives.UssFiles.IsDefaultOrEmpty)
            {
                string projectRoot = GetProjectRoot();

                _sb.Append(
                    $"{I2}internal static readonly string[] __uitkx_ussKeys = new string[] {{ "
                );
                for (int idx = 0; idx < _directives.UssFiles.Length; idx++)
                {
                    if (idx > 0)
                        _sb.Append(", ");
                    string rawPath = _directives.UssFiles[idx];
                    string resolved;
                    if (rawPath.StartsWith("./") || rawPath.StartsWith("../"))
                        resolved = ResolveRelativePath(rawPath);
                    else
                        resolved = rawPath;
                    _sb.Append($"\"{resolved}\"");

                    // Validate file existence at compile time (UITKX0022)
                    if (projectRoot != null)
                    {
                        string absolute = Path.Combine(
                            projectRoot,
                            resolved.Replace('/', Path.DirectorySeparatorChar)
                        );
                        if (!File.Exists(absolute))
                        {
                            var loc = Location.Create(_filePath, default, default);
                            _diagnostics.Add(
                                Diagnostic.Create(UitkxDiagnostics.AssetFileNotFound, loc, resolved)
                            );
                        }
                        else
                        {
                            // Type-mismatch check — @uss must reference a .uss file
                            string ext = Path.GetExtension(rawPath);
                            if (
                                !string.IsNullOrEmpty(ext)
                                && s_extensionValidTypes.TryGetValue(ext, out var validTypes)
                                && !validTypes.Contains("StyleSheet")
                            )
                            {
                                var loc = Location.Create(_filePath, default, default);
                                _diagnostics.Add(
                                    Diagnostic.Create(
                                        UitkxDiagnostics.AssetTypeMismatch,
                                        loc,
                                        "StyleSheet",
                                        ext,
                                        string.Join(", ", validTypes)
                                    )
                                );
                            }
                        }
                    }
                }
                _sb.AppendLine(" };");
                L("");
            }

            // ── Render method signature ───────────────────────────────────────
            L($"{I2}public static {QVNode} Render(");
            L($"{I2}    global::ReactiveUITK.Core.IProps __rawProps,");
            L($"{I2}    IReadOnlyList<{QVNode}> __children)");
            L($"{I2}{{");

            // Props binding
            if (_directives.PropsTypeName is { } propsType)
            {
                L($"{I3}var props = (__rawProps as {propsType}) ?? new {propsType}();");
                L("");
            }

            // Function-style param variable bindings: var x = props.X;
            if (
                _directives.IsFunctionStyle
                && !_directives.FunctionParams.IsDefault
                && !_directives.FunctionParams.IsEmpty
            )
            {
                foreach (var fp in _directives.FunctionParams)
                {
                    string propName = ToPropName(fp.Name);
                    L($"{I3}var {fp.Name} = props.{propName};");
                }
                L("");
            }

            // ── Function-style setup code ─────────────────────────────────────
            if (
                _directives.IsFunctionStyle
                && !string.IsNullOrWhiteSpace(_directives.FunctionSetupCode)
            )
            {
                int setupLine = _directives.FunctionSetupStartLine > 0
                    ? _directives.FunctionSetupStartLine
                    : _directives.ComponentDeclarationLine > 0
                        ? _directives.ComponentDeclarationLine
                        : _directives.MarkupStartLine;
                L($"#line {setupLine} \"{_linePath}\"");
                string setupCode = SpliceSetupCodeMarkup(_directives.FunctionSetupCode);
                setupCode = ApplyHookAliases(setupCode);
                setupCode = ResolveAssetPaths(setupCode);
                _sb.Append(setupCode);
                if (!setupCode.EndsWith("\n"))
                    _sb.AppendLine();
            }

            // ── Return expression ─────────────────────────────────────────────
            var markup = markupNodes.ToImmutable();

            if (markup.IsEmpty)
            {
                L($"{I3}return ({QVNode})null;");
            }
            else if (markup.Length == 1)
            {
                // Single root — determine its #line
                int srcLine = markup[0].SourceLine;
                L($"#line {srcLine} \"{_linePath}\"");
                _sb.Append($"{I3}return ");
                EmitNode(markup[0]);
                _sb.AppendLine(";");
            }
            else
            {
                // Multiple roots — emit compile-time error
                L($"#error UITKX0025: Component return must have a single root element. Wrap multiple elements in a container like <VisualElement>.");
                _sb.AppendLine($"{I3}return ({QVNode})null;");
            }

            L($"{I2}}}"); // close Render

            // ── Auto-generated props class for function-style components ──────
            // Emitted as a NESTED type INSIDE the partial class, before its
            // closing brace (e.g. ComponentName.ComponentNameProps).
            if (
                _directives.IsFunctionStyle
                && !_directives.FunctionParams.IsDefault
                && !_directives.FunctionParams.IsEmpty
            )
            {
                EmitFunctionPropsClass();
            }

            L("    }"); // close class
            L("}"); // close namespace

            return _sb.ToString();
        }

        // ── Hook alias substitution ───────────────────────────────────────────

        private static readonly (string From, string To)[] s_hookAliases =
        {
            ("useState(", "Hooks.UseState("),
            ("useEffect(", "Hooks.UseEffect("),
            ("useLayoutEffect(", "Hooks.UseLayoutEffect("),
            ("useRef(", "Hooks.UseRef("),
            ("useCallback(", "Hooks.UseCallback("),
            ("useMemo(", "Hooks.UseMemo("),
            ("useContext(", "Hooks.UseContext("),
            ("useReducer(", "Hooks.UseReducer("),
            ("useSignal(", "Hooks.UseSignal("),
            ("useDeferredValue(", "Hooks.UseDeferredValue("),
            ("useTransition(", "Hooks.UseTransition("),
            ("provideContext(", "Hooks.ProvideContext("),
        };

        // Matches generic hook calls including up to 3 levels of nested type args:
        //   useContext<Color>(                         → level 1
        //   useRef<List<int>>(                         → level 2
        //   useMemo<Dictionary<string, List<Color>>>(  → level 3
        // The non-generic form is handled by s_hookAliases simple replacements above.
        private static readonly System.Text.RegularExpressions.Regex s_genericHookAliasRe =
            new System.Text.RegularExpressions.Regex(
                @"\b(useState|useEffect|useLayoutEffect|useRef|useCallback|useMemo|useContext|useReducer|useSignal|useDeferredValue|useTransition)(<(?:[^<>]|<(?:[^<>]|<[^<>]*>)*>)*>)\s*\(",
                System.Text.RegularExpressions.RegexOptions.Compiled
            );

        internal static string ApplyHookAliases(string code)
        {
            // State-setter lambda sugar applies regardless of whether hooks are present:
            //   setFoo(v => v + 1)  →  setFoo.Set(v => v + 1)
            // Matches conventional React-style setter names: set followed by an
            // upper-case letter, called with a lambda argument.
            // Replacement: "$1.Set(" — group 1 is the setter name; the matched
            // opening "(" is consumed by "\(" in the pattern and rebuilt as ".Set(".
            code = s_setterLambdaRe.Replace(code, "$1.Set(");

            // Fast path: bail early if no lowercase hook names are present
            if (code.IndexOf("use", StringComparison.Ordinal) < 0)
                return code;
            // Handle generic hook calls (e.g. useContext<Color>() → Hooks.UseContext<Color>())
            code = s_genericHookAliasRe.Replace(
                code,
                m =>
                {
                    string hookName = m.Groups[1].Value;
                    string typeArgs = m.Groups[2].Value;
                    string pascalName = char.ToUpper(hookName[3]) + hookName.Substring(4);
                    return $"Hooks.Use{pascalName}{typeArgs}(";
                }
            );
            foreach (var (from, to) in s_hookAliases)
                code = code.Replace(from, to);

            return code;
        }

        // Matches:  setX(   setFoo(   setState(  followed immediately by a lambda
        // arg (single or multiple params), but NOT when it's setX.Set( already.
        private static readonly System.Text.RegularExpressions.Regex s_setterLambdaRe =
            new System.Text.RegularExpressions.Regex(
                @"\b(set[A-Z][a-zA-Z0-9_]*)\(\s*(?=[a-zA-Z_][a-zA-Z0-9_]*\s*=>|\([^)]*\)\s*=>)",
                System.Text.RegularExpressions.RegexOptions.Compiled
            );

        // Matches Asset<T>("path") or Ast<T>("path") — type in group[1], path in group[2].
        private static readonly System.Text.RegularExpressions.Regex s_assetCallRe =
            new System.Text.RegularExpressions.Regex(
                @"(?:Asset|Ast)\s*<\s*(\w+)\s*>\s*\(\s*""([^""]+)""\s*\)",
                System.Text.RegularExpressions.RegexOptions.Compiled
            );

        // ── Hook signature extraction ──────────────────────────────────────────

        /// <summary>
        /// Matches any hook call in setup code — both user-written camelCase
        /// (useState, useEffect) and fully-qualified PascalCase (Hooks.UseState).
        /// Captures the hook name (without "Hooks." prefix) in group 1.
        /// </summary>
        private static readonly System.Text.RegularExpressions.Regex s_hookSignatureRe =
            new System.Text.RegularExpressions.Regex(
                @"(?:Hooks\.)?\b(useState|useEffect|useLayoutEffect|useRef|useCallback|useMemo|useContext|useReducer|useSignal|useDeferredValue|useTransition|useSafeArea|useStableFunc|useStableAction|useStableCallback|useImperativeHandle|useAnimate|useTweenFloat|provideContext|UseState|UseEffect|UseLayoutEffect|UseRef|UseCallback|UseMemo|UseContext|UseReducer|UseSignal|UseDeferredValue|UseTransition|UseSafeArea|UseStableFunc|UseStableAction|UseStableCallback|UseImperativeHandle|UseAnimate|UseTweenFloat|ProvideContext)(?:<[^>]*>)?\s*\(",
                System.Text.RegularExpressions.RegexOptions.Compiled
            );

        /// <summary>
        /// Scans raw setup code for hook call patterns and returns
        /// a comma-separated ordered signature string (e.g. "UseState,UseEffect,UseMemo").
        /// Returns empty string if no hooks are found.
        /// </summary>
        internal static string ExtractHookSignature(string setupCode)
        {
            if (string.IsNullOrWhiteSpace(setupCode))
                return string.Empty;

            var matches = s_hookSignatureRe.Matches(setupCode);
            if (matches.Count == 0)
                return string.Empty;

            var sb = new StringBuilder();
            for (int i = 0; i < matches.Count; i++)
            {
                if (i > 0)
                    sb.Append(',');
                sb.Append(NormalizeHookName(matches[i].Groups[1].Value));
            }
            return sb.ToString();
        }

        /// <summary>
        /// Normalizes a hook name to its canonical PascalCase form
        /// matching the runtime hook ID constants in Hooks.cs.
        /// </summary>
        internal static string NormalizeHookName(string name)
        {
            // Already PascalCase
            if (char.IsUpper(name[0]))
                return name;

            // camelCase → PascalCase: useState → UseState, provideContext → ProvideContext
            if (name.StartsWith("use"))
                return "Use" + char.ToUpper(name[3]) + name.Substring(4);
            if (name.StartsWith("provide"))
                return "Provide" + char.ToUpper(name[7]) + name.Substring(8);

            return name;
        }

        private static readonly Dictionary<string, HashSet<string>> s_extensionValidTypes = new(
            StringComparer.OrdinalIgnoreCase
        )
        {
            {
                ".png",
                new HashSet<string> { "Texture2D", "Sprite" }
            },
            {
                ".jpg",
                new HashSet<string> { "Texture2D", "Sprite" }
            },
            {
                ".jpeg",
                new HashSet<string> { "Texture2D", "Sprite" }
            },
            {
                ".bmp",
                new HashSet<string> { "Texture2D", "Sprite" }
            },
            {
                ".tga",
                new HashSet<string> { "Texture2D", "Sprite" }
            },
            {
                ".psd",
                new HashSet<string> { "Texture2D", "Sprite" }
            },
            {
                ".gif",
                new HashSet<string> { "Texture2D", "Sprite" }
            },
            {
                ".tif",
                new HashSet<string> { "Texture2D", "Sprite" }
            },
            {
                ".tiff",
                new HashSet<string> { "Texture2D", "Sprite" }
            },
            {
                ".exr",
                new HashSet<string> { "Texture2D", "Sprite" }
            },
            {
                ".hdr",
                new HashSet<string> { "Texture2D", "Sprite" }
            },
            {
                ".svg",
                new HashSet<string> { "VectorImage" }
            },
            {
                ".wav",
                new HashSet<string> { "AudioClip" }
            },
            {
                ".mp3",
                new HashSet<string> { "AudioClip" }
            },
            {
                ".ogg",
                new HashSet<string> { "AudioClip" }
            },
            {
                ".aiff",
                new HashSet<string> { "AudioClip" }
            },
            {
                ".ttf",
                new HashSet<string> { "Font" }
            },
            {
                ".otf",
                new HashSet<string> { "Font" }
            },
            {
                ".mat",
                new HashSet<string> { "Material" }
            },
            {
                ".uss",
                new HashSet<string> { "StyleSheet" }
            },
            {
                ".renderTexture",
                new HashSet<string> { "RenderTexture" }
            },
        };

        // ── __C helper method ─────────────────────────────────────────────────

        private void EmitHelperMethod()
        {
            // Generates a child-array builder that:
            //   • skips null VirtualNode entries (from @if without @else)
            //   • flattens VirtualNode[] arrays (from @foreach → .Select().ToArray())
            L($"{I2}private static {QVNode}[] __C(params object[] items)");
            L($"{I2}{{");
            L($"{I3}var list = new global::System.Collections.Generic.List<{QVNode}>();");
            L($"{I3}foreach (var __ci in items)");
            L($"{I3}{{");
            L($"{I4}if (__ci is {QVNode} __vn) {{ if (__vn != null) list.Add(__vn); }}");
            L(
                $"{I4}else if (__ci is global::System.Collections.Generic.IEnumerable<{QVNode}> __seq)"
            );
            L($"{I4}    foreach (var __sn in __seq) {{ if (__sn != null) list.Add(__sn); }}");
            L($"{I3}}}");
            L($"{I3}return list.ToArray();");
            L($"{I2}}}");
            L("");
        }

        // ── Node dispatch ─────────────────────────────────────────────────────

        private void EmitNode(AstNode node)
        {
            switch (node)
            {
                case ElementNode e:
                    EmitElementNode(e);
                    break;
                case TextNode t:
                    EmitTextNode(t);
                    break;
                case ExpressionNode x:
                    EmitExpressionNode(x);
                    break;
                case IfNode i:
                    EmitIfNode(i);
                    break;
                case ForeachNode f:
                    EmitForeachNode(f);
                    break;
                case ForNode fn:
                    EmitForNode(fn);
                    break;
                case WhileNode wn:
                    EmitWhileNode(wn);
                    break;
                case SwitchNode s:
                    EmitSwitchNode(s);
                    break;
                case CommentNode:
                    // comments emit nothing to C#
                    break;
                default:
                    _sb.Append($"({QVNode})null /* unhandled: {node.GetType().Name} */");
                    break;
            }
        }

        // ── ElementNode ───────────────────────────────────────────────────────

        private void EmitElementNode(ElementNode el)
        {
            bool injectUss = _isRootElement && !_directives.UssFiles.IsDefaultOrEmpty;
            _isRootElement = false;

            // Search the current namespace first, then explicit @using namespaces.
            // This matches C# lookup rules better and avoids cross-namespace peer
            // components falling back to stale metadata matches.
            var searchNamespaces = BuildSearchNamespaces();
            var res = _resolver.Resolve(el.TagName, searchNamespaces, out var diagDesc);

            if (diagDesc != null)
            {
                var loc = Location.Create(_filePath, default, default);
                _diagnostics.Add(Diagnostic.Create(diagDesc, loc, el.TagName));
            }

            string keyExpr = ExtractKey(el.Attributes);

            switch (res.Kind)
            {
                case TagResolutionKind.Fragment:
                    EmitFragment(keyExpr, el.Children);
                    break;

                case TagResolutionKind.BuiltinTyped:
                    EmitBuiltinTyped(res, el.Attributes, keyExpr, el.Children, injectUss);
                    break;

                case TagResolutionKind.BuiltinDictionary:
                    EmitBuiltinDict(res, el.Attributes, keyExpr, el.Children, injectUss);
                    break;

                case TagResolutionKind.BuiltinText:
                {
                    string txt = GetAttrValue(el.Attributes, "text") ?? "\"\"";
                    _sb.Append($"V.Text({txt}, key: {keyExpr})");
                    break;
                }

                case TagResolutionKind.BuiltinSuspense:
                    EmitSuspense(el.Attributes, keyExpr, el.Children);
                    break;

                case TagResolutionKind.BuiltinPortal:
                    EmitPortal(el.Attributes, keyExpr, el.Children);
                    break;

                case TagResolutionKind.FuncComponent:
                    EmitFuncComponent(res, el.Attributes, keyExpr, el.Children, searchNamespaces);
                    break;

                case TagResolutionKind.Unknown:
                    _sb.Append($"({QVNode})null /* unknown: {el.TagName} */");
                    break;
            }
        }

        private ImmutableArray<string> BuildSearchNamespaces()
        {
            var seen = new HashSet<string>(StringComparer.Ordinal);
            var builder = ImmutableArray.CreateBuilder<string>();

            if (!string.IsNullOrEmpty(_directives.Namespace) && seen.Add(_directives.Namespace!))
                builder.Add(_directives.Namespace!);

            foreach (var ns in _directives.Usings)
            {
                if (seen.Add(ns))
                    builder.Add(ns);
            }

            return builder.ToImmutable();
        }

        private void EmitBuiltinTyped(
            TagResolution res,
            ImmutableArray<AttributeNode> attrs,
            string keyExpr,
            ImmutableArray<AstNode> children,
            bool injectUssKeys = false
        )
        {
            // UITKX0002 — validate attribute names against known Props properties
            if (res.PropsTypeName != null)
            {
                var knownProps = _resolver.GetPublicPropertyNames(res.PropsTypeName);
                if (knownProps.Count > 0)
                {
                    foreach (var attr in attrs)
                    {
                        if (IsKey(attr.Name))
                            continue;
                        string mapped = ToPropName(attr.Name);
                        if (!knownProps.Contains(mapped))
                        {
                            string? suggestion = FindClosestMatch(mapped, knownProps);
                            string hint =
                                suggestion != null ? $". Did you mean '{suggestion}'?" : "";
                            var loc = Location.Create(_filePath, default, default);
                            _diagnostics.Add(
                                Diagnostic.Create(
                                    UitkxDiagnostics.UnknownAttribute,
                                    loc,
                                    attr.Name,
                                    res.MethodName.ToLowerInvariant(),
                                    hint
                                )
                            );
                        }
                    }
                }
            }

            _sb.Append($"V.{res.MethodName}(new {res.PropsTypeName} {{");

            bool first = true;
            foreach (var attr in attrs)
            {
                if (IsKey(attr.Name))
                    continue;
                if (!first)
                    _sb.Append(", ");
                first = false;
                _sb.Append($" {ToPropName(attr.Name)} = {AttrVal(attr.Value)}");
            }

            if (injectUssKeys)
            {
                if (!first)
                    _sb.Append(", ");
                _sb.Append(
                    " ExtraProps = new Dictionary<string, object> { { \"__ussKeys\", __uitkx_ussKeys } }"
                );
            }

            _sb.Append(" }, key: ");
            _sb.Append(keyExpr);

            if (res.AcceptsChildren && !children.IsEmpty)
            {
                _sb.Append(", __C(");
                EmitChildArgs(children);
                _sb.Append(")");
            }

            _sb.Append(")");
        }

        private void EmitBuiltinDict(
            TagResolution res,
            ImmutableArray<AttributeNode> attrs,
            string keyExpr,
            ImmutableArray<AstNode> children,
            bool injectUssKeys = false
        )
        {
            bool hasNonKeyAttrs = injectUssKeys;
            foreach (var a in attrs)
            {
                if (!IsKey(a.Name))
                {
                    hasNonKeyAttrs = true;
                    break;
                }
            }

            if (hasNonKeyAttrs)
            {
                _sb.Append($"V.{res.MethodName}(new Dictionary<string, object>");
                _sb.Append(" {");
                bool first = true;
                foreach (var attr in attrs)
                {
                    if (IsKey(attr.Name))
                        continue;
                    if (!first)
                        _sb.Append(", ");
                    first = false;
                    _sb.Append($" {{ \"{attr.Name}\", {AttrVal(attr.Value)} }}");
                }
                if (injectUssKeys)
                {
                    if (!first)
                        _sb.Append(", ");
                    _sb.Append(" { \"__ussKeys\", __uitkx_ussKeys }");
                }
                _sb.Append(" }");
            }
            else
            {
                _sb.Append($"V.{res.MethodName}((Dictionary<string, object>)null");
            }

            _sb.Append($", key: {keyExpr}");

            if (!children.IsEmpty)
            {
                _sb.Append(", __C(");
                EmitChildArgs(children);
                _sb.Append(")");
            }

            _sb.Append(")");
        }

        private void EmitFuncComponent(
            TagResolution res,
            ImmutableArray<AttributeNode> attrs,
            string keyExpr,
            ImmutableArray<AstNode> children,
            ImmutableArray<string> searchNamespaces
        )
        {
            string typeName = res.FuncTypeName!;

            // Pull out a bare ref={x} attribute before the loop so it can be
            // routed to the component's MutableRef<T> param rather than rendered
            // as a literal "ref" property (which doesn't exist on any Props class).
            AttributeNode? refAttr = null;
            foreach (var a in attrs)
            {
                if (IsRefAttr(a.Name))
                {
                    refAttr = a;
                    break;
                }
            }

            if (res.FuncPropsTypeName != null)
            {
                // ── Typed path: V.Func<PropsType>(TypeName.Render, new PropsType { ... }) ──
                string propsTypeName = res.FuncPropsTypeName;
                _sb.Append($"V.Func<{propsTypeName}>({typeName}.Render, new {propsTypeName} {{");

                bool first = true;
                foreach (var attr in attrs)
                {
                    if (IsKey(attr.Name) || IsRefAttr(attr.Name))
                        continue;
                    if (!first)
                        _sb.Append(", ");
                    first = false;
                    _sb.Append($" {ToPropName(attr.Name)} = {AttrVal(attr.Value)}");
                }

                // Route ref={x} to the component's MutableRef<T> parameter.
                if (refAttr != null)
                {
                    var lookupResult = _resolver.TryGetRefParamPropName(
                        typeName,
                        propsTypeName,
                        searchNamespaces,
                        out string? refPropName
                    );
                    switch (lookupResult)
                    {
                        case PropsResolver.RefParamLookupResult.Found:
                            if (!first)
                                _sb.Append(",");
                            _sb.Append($" {refPropName} = {AttrVal(refAttr.Value)}");
                            break;

                        case PropsResolver.RefParamLookupResult.None:
                        {
                            var loc = Location.Create(_filePath, default, default);
                            _diagnostics.Add(
                                Diagnostic.Create(
                                    UitkxDiagnostics.RefOnComponentWithNoRefParam,
                                    loc,
                                    typeName
                                )
                            );
                            break;
                        }

                        case PropsResolver.RefParamLookupResult.Ambiguous:
                        {
                            var loc = Location.Create(_filePath, default, default);
                            _diagnostics.Add(
                                Diagnostic.Create(
                                    UitkxDiagnostics.RefOnComponentWithAmbiguousRefParam,
                                    loc,
                                    typeName
                                )
                            );
                            break;
                        }
                    }
                }

                _sb.Append(" }");
            }
            else
            {
                // ── No-props path: V.Func(TypeName.Render, ...) ──
                // ref={x} on a no-props component has no route — emit UITKX0020.
                if (refAttr != null)
                {
                    var loc = Location.Create(_filePath, default, default);
                    _diagnostics.Add(
                        Diagnostic.Create(
                            UitkxDiagnostics.RefOnComponentWithNoRefParam,
                            loc,
                            typeName
                        )
                    );
                }
                _sb.Append($"V.Func({typeName}.Render");
            }

            _sb.Append($", key: {keyExpr}");

            if (!children.IsEmpty)
            {
                _sb.Append(", children: __C(");
                EmitChildArgs(children);
                _sb.Append(")");
            }

            _sb.Append(")");
        }

        // ── Auto-generated props class ────────────────────────────────────────

        /// <summary>
        /// Emits a public sealed class <c>{ComponentName}Props : IProps</c> that
        /// holds one auto-property per entry in <see cref="DirectiveSet.FunctionParams"/>.
        ///
        /// Generated structure (inside the same namespace, after the partial class closing brace):
        /// <code>
        ///   public sealed class FooProps : global::ReactiveUITK.Core.IProps
        ///   {
        ///       public int X { get; set; } = 0;
        ///       public string Label { get; set; } = "hi";
        ///
        ///       public override bool Equals(object obj) { ... }
        ///       public override int GetHashCode() { ... }
        ///   }
        /// </code>
        /// </summary>
        private void EmitFunctionPropsClass()
        {
            string className = _directives.ComponentName + "Props";
            var fps = _directives.FunctionParams;

            L("");
            L(
                $"    /// <summary>Auto-generated typed props for <see cref=\"{_directives.ComponentName}\"/>.</summary>"
            );
            L($"    public sealed class {className} : global::ReactiveUITK.Core.IProps");
            L("    {");

            // Properties
            foreach (var fp in fps)
            {
                string propName = ToPropName(fp.Name);
                string def = string.IsNullOrWhiteSpace(fp.DefaultValue)
                    ? "default"
                    : fp.DefaultValue!;
                L($"        public {fp.Type} {propName} {{ get; set; }} = {def};");
            }

            L("");

            // Equals
            L("        public override bool Equals(object? obj)");
            L("        {");
            L($"            if (obj is not {className} other) return false;");
            bool firstEq = true;
            foreach (var fp in fps)
            {
                string propName = ToPropName(fp.Name);
                string conjunction = firstEq ? "            return " : "                && ";
                firstEq = false;
                L(
                    $"{conjunction}global::System.Collections.Generic.EqualityComparer<{fp.Type}>.Default.Equals({propName}, other.{propName})"
                );
            }
            if (firstEq) // no params — always equal
                L("            return true;");
            else
                L("                ;"); // close the boolean chain with a dangling semicolon
            L("        }");

            L("");

            // GetHashCode
            L("        public override int GetHashCode()");
            L("        {");
            L("            unchecked");
            L("            {");
            L("                int hash = 17;");
            foreach (var fp in fps)
            {
                string propName = ToPropName(fp.Name);
                L(
                    $"                hash = hash * 31 + global::System.Collections.Generic.EqualityComparer<{fp.Type}>.Default.GetHashCode({propName}!);"
                );
            }
            L("                return hash;");
            L("            }");
            L("        }");

            L("    }");
        }

        // ── Suspense built-in ─────────────────────────────────────────────────
        // Emits V.Suspense(isReady, [pendingTask,] fallback, key:..., children...)
        // from well-known attribute names: isReady / is-ready, pendingTask /
        // pending-task, and fallback.
        private void EmitSuspense(
            ImmutableArray<AttributeNode> attrs,
            string keyExpr,
            ImmutableArray<AstNode> children
        )
        {
            string? isReady = GetAttrValue(attrs, "isReady") ?? GetAttrValue(attrs, "is-ready");
            string? pendingTask =
                GetAttrValue(attrs, "pendingTask") ?? GetAttrValue(attrs, "pending-task");
            string? fallbackAttr = GetAttrValue(attrs, "fallback");

            string isReadyArg = isReady ?? "() => false";
            string fallbackArg = fallbackAttr ?? $"({QVNode})null";

            _sb.Append("V.Suspense(");
            _sb.Append(isReadyArg);
            _sb.Append(", ");
            if (pendingTask != null)
            {
                _sb.Append(pendingTask);
                _sb.Append(", ");
            }
            _sb.Append(fallbackArg);
            _sb.Append($", key: {keyExpr}");

            if (!children.IsEmpty)
            {
                _sb.Append(", ");
                EmitChildArgs(children);
            }

            _sb.Append(")");
        }

        private void EmitPortal(
            ImmutableArray<AttributeNode> attrs,
            string keyExpr,
            ImmutableArray<AstNode> children
        )
        {
            string targetArg = GetAttrValue(attrs, "target") ?? "null";

            _sb.Append($"V.Portal({targetArg}, key: {keyExpr}");

            if (!children.IsEmpty)
            {
                _sb.Append(", ");
                EmitChildArgs(children);
            }

            _sb.Append(")");
        }

        private void EmitFragment(string keyExpr, ImmutableArray<AstNode> children)
        {
            if (children.IsEmpty)
            {
                _sb.Append($"V.Fragment(key: {keyExpr})");
            }
            else
            {
                _sb.Append($"V.Fragment(key: {keyExpr}, __C(");
                EmitChildArgs(children);
                _sb.Append("))");
            }
        }

        // ── Control flow ──────────────────────────────────────────────────────

        private void EmitIfNode(IfNode ifn)
        {
            if (ifn.Branches.IsEmpty)
            {
                _sb.Append($"({QVNode})null");
                return;
            }

            // If any branch has setup code, use statement-mode IIFE
            bool hasSetupCode = false;
            foreach (var br in ifn.Branches)
                if (br.SetupCode != null) { hasSetupCode = true; break; }

            if (hasSetupCode)
            {
                _sb.Append($"((System.Func<{QVNode}>)(() => {{ ");
                for (int i = 0; i < ifn.Branches.Length; i++)
                {
                    var branch = ifn.Branches[i];
                    if (branch.Condition == null)
                    {
                        _sb.Append("else { ");
                    }
                    else if (i == 0)
                    {
                        _sb.Append($"if ({branch.Condition}) {{ ");
                    }
                    else
                    {
                        _sb.Append($"else if ({branch.Condition}) {{ ");
                    }

                    if (branch.SetupCode != null)
                    {
                        var code = ApplyHookAliases(branch.SetupCode);
                        code = ResolveAssetPaths(code);
                        _sb.Append(code);
                        _sb.Append(" ");
                    }
                    _sb.Append("return ");
                    EmitBodyAsFragment(branch.Body);
                    _sb.Append("; } ");
                }
                _sb.Append($"return ({QVNode})null; }}))()");
                return;
            }

            // No setup code — use ternary expression (existing path)
            // Stable-type strategy: outer + inner Fragment wrapping
            _sb.Append("V.Fragment(key: null, __C(");

            for (int i = 0; i < ifn.Branches.Length; i++)
            {
                var branch = ifn.Branches[i];

                if (branch.Condition == null)
                {
                    EmitBodyAsFragment(branch.Body);
                    _sb.Append("))");
                    return;
                }

                _sb.Append($"({branch.Condition}) ? ");
                EmitBodyAsFragment(branch.Body);
                _sb.Append(" : ");

                if (i == ifn.Branches.Length - 1)
                    _sb.Append("V.Fragment(key: null)");
            }
            _sb.Append("))");
        }

        private void EmitForNode(ForNode fn)
        {
            // Always use statement mode — setup code + body expression
            _sb.Append($"((System.Func<{QVNode}[]>)(() => {{ ");
            _sb.Append($"var __r = new System.Collections.Generic.List<{QVNode}>(); ");
            _sb.Append($"for ({fn.ForExpression}) {{ ");
            if (fn.SetupCode != null)
            {
                var code = ApplyHookAliases(fn.SetupCode);
                code = ResolveAssetPaths(code);
                _sb.Append(code);
                _sb.Append(" ");
            }
            _sb.Append("__r.Add(");
            EmitBodyExpr(fn.Body);
            _sb.Append("); ");
            _sb.Append("} return __r.ToArray(); }))()");
        }

        private void EmitWhileNode(WhileNode wn)
        {
            _sb.Append($"((System.Func<{QVNode}[]>)(() => {{ ");
            _sb.Append($"var __r = new System.Collections.Generic.List<{QVNode}>(); ");
            _sb.Append($"while ({wn.Condition}) {{ ");
            if (wn.SetupCode != null)
            {
                var code = ApplyHookAliases(wn.SetupCode);
                code = ResolveAssetPaths(code);
                _sb.Append(code);
                _sb.Append(" ");
            }
            _sb.Append("__r.Add(");
            EmitBodyExpr(wn.Body);
            _sb.Append("); ");
            _sb.Append("} return __r.ToArray(); }))()");
        }

        private void EmitForeachNode(ForeachNode forn)
        {
            // UITKX0009 — warn if direct element children lack a key attribute
            foreach (var bodyNode in forn.Body)
            {
                if (bodyNode is ElementNode elCheck && !HasKey(elCheck.Attributes))
                {
                    var loc = Location.Create(_filePath, default, default);
                    _diagnostics.Add(
                        Diagnostic.Create(
                            UitkxDiagnostics.ForeachMissingKey,
                            loc,
                            string.IsNullOrEmpty(elCheck.TagName) ? "fragment" : elCheck.TagName,
                            elCheck.SourceLine,
                            _displayName
                        )
                    );
                }
            }

            if (forn.SetupCode != null)
            {
                // Setup code present — use IIFE with statement mode
                string varName = ExtractVarName(forn.IteratorDeclaration);
                _sb.Append($"((System.Func<{QVNode}[]>)(() => {{ ");
                _sb.Append($"var __r = new System.Collections.Generic.List<{QVNode}>(); ");
                _sb.Append($"foreach ({forn.IteratorDeclaration} in {forn.CollectionExpression}) {{ ");
                var foreachCode = ApplyHookAliases(forn.SetupCode);
                foreachCode = ResolveAssetPaths(foreachCode);
                _sb.Append(foreachCode);
                _sb.Append(" __r.Add(");
                EmitBodyExpr(forn.Body);
                _sb.Append("); } return __r.ToArray(); }))()");
            }
            else
            {
                // No setup code — use LINQ Select (existing path)
                string varName = ExtractVarName(forn.IteratorDeclaration);
                _sb.Append($"({forn.CollectionExpression}).Select(({varName}) => ");

                if (forn.Body.IsEmpty)
                    _sb.Append($"({QVNode})null");
                else if (forn.Body.Length == 1)
                    EmitNode(forn.Body[0]);
                else
                {
                    _sb.Append("#error UITKX0025: @foreach body must have a single root element.");
                }

                _sb.Append(").ToArray()");
            }
        }

        private void EmitSwitchNode(SwitchNode sw)
        {
            // If any case has setup code, use statement-mode IIFE with switch statement
            bool hasSetupCode = false;
            foreach (var c in sw.Cases)
                if (c.SetupCode != null) { hasSetupCode = true; break; }

            // Pre-compute body fragment strings for fallthrough merging
            var bodyFrags = new string[sw.Cases.Length];
            for (int i = 0; i < sw.Cases.Length; i++)
            {
                int mark = _sb.Length;
                EmitBodyAsFragment(sw.Cases[i].Body);
                bodyFrags[i] = _sb.ToString(mark, _sb.Length - mark);
                _sb.Length = mark;
            }

            if (hasSetupCode)
            {
                _sb.Append($"((System.Func<{QVNode}>)(() => {{ ");
                _sb.Append($"switch ({sw.SwitchExpression}) {{ ");
                int i = 0;
                while (i < sw.Cases.Length)
                {
                    var c = sw.Cases[i];
                    // Merge consecutive no-setup, non-default cases with identical bodies
                    int groupEnd = i + 1;
                    if (c.SetupCode == null && c.ValueExpression != null)
                    {
                        while (groupEnd < sw.Cases.Length
                            && sw.Cases[groupEnd].SetupCode == null
                            && sw.Cases[groupEnd].ValueExpression != null
                            && bodyFrags[groupEnd] == bodyFrags[i])
                            groupEnd++;
                    }
                    for (int j = i; j < groupEnd; j++)
                        _sb.Append(sw.Cases[j].ValueExpression == null ? "default: " : $"case {sw.Cases[j].ValueExpression}: ");
                    if (c.SetupCode != null)
                    {
                        var code = ApplyHookAliases(c.SetupCode);
                        code = ResolveAssetPaths(code);
                        _sb.Append(code);
                        _sb.Append(" ");
                    }
                    _sb.Append("return ");
                    _sb.Append(bodyFrags[i]);
                    _sb.Append("; ");
                    i = groupEnd;
                }
                _sb.Append($"}} return ({QVNode})null; }}))()");
                return;
            }

            // No setup code — use switch expression with fallthrough via 'or' patterns
            _sb.Append("V.Fragment(key: null, __C(");
            _sb.Append($"({sw.SwitchExpression}) switch {{");

            int ci = 0;
            while (ci < sw.Cases.Length)
            {
                var c = sw.Cases[ci];
                // Merge consecutive non-default cases with identical bodies
                int groupEnd = ci + 1;
                if (c.ValueExpression != null)
                {
                    while (groupEnd < sw.Cases.Length
                        && sw.Cases[groupEnd].ValueExpression != null
                        && bodyFrags[groupEnd] == bodyFrags[ci])
                        groupEnd++;
                }

                if (c.ValueExpression == null)
                {
                    _sb.Append(" _ => ");
                }
                else if (groupEnd - ci > 1)
                {
                    _sb.Append(" ");
                    for (int j = ci; j < groupEnd; j++)
                    {
                        if (j > ci) _sb.Append(" or ");
                        _sb.Append(sw.Cases[j].ValueExpression);
                    }
                    _sb.Append(" => ");
                }
                else
                {
                    _sb.Append($" {c.ValueExpression} => ");
                }

                _sb.Append(bodyFrags[ci]);
                _sb.Append(",");
                ci = groupEnd;
            }

            if (sw.Cases.Length > 0 && sw.Cases[sw.Cases.Length - 1].ValueExpression != null)
                _sb.Append(" _ => V.Fragment(key: null),");

            _sb.Append(" }");
            _sb.Append("))");
        }

        // ── Leaf nodes ────────────────────────────────────────────────────────

        private void EmitTextNode(TextNode txt)
        {
            string s = txt.Content.Trim();
            if (string.IsNullOrEmpty(s))
            {
                _sb.Append($"({QVNode})null /* whitespace text */");
                return;
            }
            _sb.Append($"V.Text(\"{EscStr(s)}\")");
        }

        private void EmitExpressionNode(ExpressionNode ex)
        {
            // @(expr) — user is responsible for returning VirtualNode-compatible value
            _sb.Append($"(({QVNode})({ex.Expression}))");
        }

        // ── Body expression helpers ───────────────────────────────────────────

        /// <summary>
        /// Emits the body of an @if / @switch branch as a V.Fragment, always.
        /// This guarantees that the type of the value produced by every branch of a
        /// ternary / switch expression is always VirtualNodeType.Fragment, so the
        /// reconciler never needs to CommitPlacement after initial mount.
        /// </summary>
        private void EmitBodyAsFragment(ImmutableArray<AstNode> body)
        {
            if (body.IsEmpty)
            {
                _sb.Append($"({QVNode})null");
            }
            else if (body.Length == 1)
            {
                EmitNode(body[0]);
            }
            else
            {
                _sb.Append("#error UITKX0025: Control block branch must have a single root element.");
            }
        }

        /// <summary>
        /// Emits the body of a branch as a single expression.
        /// Multiple-child bodies are wrapped in V.Fragment.
        /// </summary>
        private void EmitBodyExpr(ImmutableArray<AstNode> body)
        {
            if (body.IsEmpty)
            {
                _sb.Append($"({QVNode})null");
            }
            else if (body.Length == 1)
            {
                EmitNode(body[0]);
            }
            else
            {
                _sb.Append("#error UITKX0025: Control block body must have a single root element.");
            }
        }

        /// <summary>
        /// Emits the argument list for a __C(...) call: one child per line,
        /// each preceded by a #line directive.
        /// </summary>
        private void EmitChildArgs(ImmutableArray<AstNode> children)
        {
            // UITKX0010 — warn on duplicate static string keys among siblings
            CheckDuplicateKeys(children);

            bool first = true;
            for (int i = 0; i < children.Length; i++)
            {
                // Comments emit nothing — skip to avoid dangling commas
                if (children[i] is CommentNode)
                    continue;

                if (!first)
                    _sb.Append(",");
                first = false;

                _sb.AppendLine();
                if (children[i].SourceLine > 0)
                {
                    _sb.AppendLine($"#line {children[i].SourceLine} \"{_linePath}\"");
                }
                _sb.Append(I4);
                EmitNode(children[i]);
            }
            if (!first)
            {
                _sb.AppendLine();
                _sb.Append(I4);
            }
        }

        // ── Attribute helpers ─────────────────────────────────────────────────

        private static bool HasKey(ImmutableArray<AttributeNode> attrs)
        {
            foreach (var a in attrs)
                if (IsKey(a.Name))
                    return true;
            return false;
        }

        private void CheckDuplicateKeys(ImmutableArray<AstNode> children)
        {
            var seen = new HashSet<string>(StringComparer.Ordinal);
            foreach (var child in children)
            {
                if (child is not ElementNode el)
                    continue;
                foreach (var attr in el.Attributes)
                {
                    if (!IsKey(attr.Name))
                        continue;
                    if (attr.Value is StringLiteralValue slv)
                    {
                        if (!seen.Add(slv.Value))
                        {
                            var loc = Location.Create(_filePath, default, default);
                            _diagnostics.Add(
                                Diagnostic.Create(
                                    UitkxDiagnostics.DuplicateSiblingKey,
                                    loc,
                                    slv.Value,
                                    _displayName
                                )
                            );
                        }
                    }
                }
            }
        }

        // ── Did-you-mean helpers ─────────────────────────────────────

        private static string? FindClosestMatch(string name, HashSet<string> candidates)
        {
            string? best = null;
            int bestDist = 3; // only suggest if within edit-distance 2
            foreach (var c in candidates)
            {
                int dist = LevenshteinDistance(name, c);
                if (dist < bestDist)
                {
                    bestDist = dist;
                    best = c;
                }
            }
            return best;
        }

        private static int LevenshteinDistance(string a, string b)
        {
            if (a.Length == 0)
                return b.Length;
            if (b.Length == 0)
                return a.Length;
            var d = new int[a.Length + 1, b.Length + 1];
            for (int i = 0; i <= a.Length; i++)
                d[i, 0] = i;
            for (int j = 0; j <= b.Length; j++)
                d[0, j] = j;
            for (int i = 1; i <= a.Length; i++)
            for (int j = 1; j <= b.Length; j++)
                d[i, j] = Math.Min(
                    Math.Min(d[i - 1, j] + 1, d[i, j - 1] + 1),
                    d[i - 1, j - 1]
                        + (
                            char.ToLowerInvariant(a[i - 1]) == char.ToLowerInvariant(b[j - 1])
                                ? 0
                                : 1
                        )
                );
            return d[a.Length, b.Length];
        }

        private string ExtractKey(ImmutableArray<AttributeNode> attrs)
        {
            foreach (var a in attrs)
                if (IsKey(a.Name))
                    return AttrVal(a.Value);
            return "null";
        }

        private string? GetAttrValue(ImmutableArray<AttributeNode> attrs, string name)
        {
            foreach (var a in attrs)
                if (string.Equals(a.Name, name, StringComparison.OrdinalIgnoreCase))
                    return AttrVal(a.Value);
            return null;
        }

        private string AttrVal(AttributeValue v) =>
            v switch
            {
                StringLiteralValue slv => $"\"{EscStr(slv.Value)}\"",
                // Apply setter-lambda sugar: setFoo(v => v+1) → setFoo.Set(v => v+1)
                CSharpExpressionValue cev => TransformExpression(cev.Expression),
                JsxExpressionValue jsx => EmitJsxToString(jsx.Element),
                BooleanShorthandValue => "true",
                _ => "null",
            };

        /// <summary>
        /// Emits a JSX <see cref="ElementNode"/> to a string by temporarily capturing
        /// <see cref="EmitElementNode"/> output from the shared <see cref="_sb"/>.
        /// </summary>
        private string EmitJsxToString(ElementNode? element)
        {
            if (element == null)
                return $"({QVNode})null";
            int startLen = _sb.Length;
            EmitElementNode(element);
            string result = _sb.ToString(startLen, _sb.Length - startLen);
            _sb.Length = startLen;
            return result;
        }

        // ── Setup-code JSX splice ─────────────────────────────────────────────

        /// <summary>
        /// Replaces embedded JSX markup spans inside <paramref name="setupCode"/>
        /// with their emitted C# VirtualNode call equivalents.
        /// Returns the setup code unchanged when there are no markup ranges.
        /// </summary>
        private string SpliceSetupCodeMarkup(string setupCode)
        {
            var markupRanges = _directives.SetupCodeMarkupRanges;
            var bareRanges = _directives.SetupCodeBareJsxRanges;

            bool hasMarkup = !markupRanges.IsDefaultOrEmpty;
            bool hasBare = !bareRanges.IsDefaultOrEmpty;
            if (!hasMarkup && !hasBare)
                return setupCode;

            // Merge both range lists and sort by absolute start position.
            var allRanges = new List<(int Start, int End, int Line)>();
            if (hasMarkup)
                foreach (var r in markupRanges) allRanges.Add(r);
            if (hasBare)
                foreach (var r in bareRanges) allRanges.Add(r);
            allRanges.Sort((a, b) => a.Start.CompareTo(b.Start));

            int fseOffset = _directives.FunctionSetupStartOffset;
            int gapOffset = _directives.FunctionSetupGapOffset;
            int gapLength = _directives.FunctionSetupGapLength;

            var spliced = new StringBuilder(setupCode.Length);
            int prev = 0;

            foreach (var (absStart, absEnd, line) in allRanges)
            {
                // Convert absolute source positions to setupCode-relative offsets.
                int relStart = AbsToSetupOffset(absStart, fseOffset, gapOffset, gapLength);
                int relEnd = AbsToSetupOffset(absEnd, fseOffset, gapOffset, gapLength);

                // Guard against out-of-range offsets.
                if (relStart < 0) relStart = 0;
                if (relEnd < 0) relEnd = 0;
                if (relStart > setupCode.Length) relStart = setupCode.Length;
                if (relEnd > setupCode.Length) relEnd = setupCode.Length;
                if (relEnd <= relStart) continue;

                // Append C# text before this JSX span.
                if (relStart > prev)
                    spliced.Append(setupCode, prev, relStart - prev);

                // Extract JSX fragment and parse it.
                string jsxText = setupCode.Substring(relStart, relEnd - relStart);
                var miniDirectives = new DirectiveSet(
                    Namespace: null,
                    ComponentName: null,
                    PropsTypeName: null,
                    DefaultKey: null,
                    Usings: _directives.Usings,
                    UssFiles: ImmutableArray<string>.Empty,
                    Injects: ImmutableArray<(string, string)>.Empty,
                    MarkupStartLine: line,
                    MarkupStartIndex: 0,
                    MarkupEndIndex: jsxText.Length
                );
                var miniDiags = new List<ParseDiagnostic>();
                var nodes = UitkxParser.Parse(jsxText, _filePath, miniDirectives, miniDiags);

                if (nodes.Length > 0)
                {
                    // Emit the parsed node(s) into a temporary buffer.
                    int savedLen = _sb.Length;
                    if (nodes.Length == 1)
                        EmitNode(nodes[0]);
                    else
                    {
                        _sb.Append("#error UITKX0025: Inline JSX expression must have a single root element.");
                    }
                    string emittedCs = _sb.ToString(savedLen, _sb.Length - savedLen);
                    _sb.Length = savedLen;
                    spliced.Append(emittedCs.Trim());
                }
                else
                {
                    // Parse failed — keep the original text (will cause a compile error
                    // from the C# compiler, which is better than silently dropping it).
                    spliced.Append(jsxText);
                }

                prev = relEnd;
            }

            if (prev < setupCode.Length)
                spliced.Append(setupCode, prev, setupCode.Length - prev);

            return spliced.ToString();
        }

        private static int AbsToSetupOffset(int absPos, int fseOffset, int gapOffset, int gapLength)
        {
            int relOffset = absPos - fseOffset;
            if (gapOffset >= 0 && relOffset >= gapOffset)
                relOffset -= gapLength;
            return relOffset;
        }

        private static bool IsKey(string name) =>
            string.Equals(name, "key", StringComparison.OrdinalIgnoreCase);

        private static bool IsRefAttr(string name) =>
            string.Equals(name, "ref", StringComparison.OrdinalIgnoreCase);

        private static string ToPropName(string attrName)
        {
            if (string.IsNullOrEmpty(attrName))
                return attrName;
            return char.ToUpperInvariant(attrName[0]) + attrName.Substring(1);
        }

        // ── String / variable helpers ─────────────────────────────────────────

        private static string EscStr(string s) =>
            s.Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\n", "\\n")
                .Replace("\r", "\\r")
                .Replace("\t", "\\t");

        private static string ExtractVarName(string declaration)
        {
            if (string.IsNullOrWhiteSpace(declaration))
                return "__item";
            var parts = declaration
                .Trim()
                .Split(new[] { ' ', '\t' }, StringSplitOptions.RemoveEmptyEntries);
            return parts.Length > 0 ? parts[parts.Length - 1] : "__item";
        }

        private static string NormalizeLinePath(string filePath)
        {
            string fullPath;
            try
            {
                fullPath = Path.GetFullPath(filePath);
            }
            catch
            {
                fullPath = filePath;
            }

            return fullPath.Replace('\\', '/').Replace("\"", "\\\"");
        }

        // ── Asset path resolution ─────────────────────────────────────────────

        /// <summary>
        /// Applies setter-lambda sugar and resolves relative asset paths.
        /// </summary>
        private string TransformExpression(string expr)
        {
            string result = s_setterLambdaRe.Replace(expr, "$1.Set(");
            if (result.Contains("Asset<") || result.Contains("Ast<"))
                result = ResolveAssetPaths(result);
            return result;
        }

        private string ResolveAssetPaths(string expression)
        {
            return s_assetCallRe.Replace(
                expression,
                match =>
                {
                    string requestedType = match.Groups[1].Value;
                    string rawPath = match.Groups[2].Value;
                    string resolved;
                    if (rawPath.StartsWith("./") || rawPath.StartsWith("../"))
                        resolved = ResolveRelativePath(rawPath);
                    else
                        resolved = rawPath;

                    // Validate file existence at compile time
                    string projectRoot = GetProjectRoot();
                    if (projectRoot != null)
                    {
                        string absolute = Path.Combine(
                            projectRoot,
                            resolved.Replace('/', Path.DirectorySeparatorChar)
                        );
                        if (!File.Exists(absolute))
                        {
                            var loc = Location.Create(_filePath, default, default);
                            _diagnostics.Add(
                                Diagnostic.Create(UitkxDiagnostics.AssetFileNotFound, loc, resolved)
                            );
                        }
                        else
                        {
                            // Type-mismatch check
                            string ext = Path.GetExtension(rawPath);
                            if (
                                !string.IsNullOrEmpty(ext)
                                && s_extensionValidTypes.TryGetValue(ext, out var validTypes)
                                && !validTypes.Contains(requestedType)
                            )
                            {
                                var loc = Location.Create(_filePath, default, default);
                                _diagnostics.Add(
                                    Diagnostic.Create(
                                        UitkxDiagnostics.AssetTypeMismatch,
                                        loc,
                                        requestedType,
                                        ext,
                                        string.Join(", ", validTypes)
                                    )
                                );
                            }
                        }
                    }

                    // Only rewrite relative paths
                    if (rawPath.StartsWith("./") || rawPath.StartsWith("../"))
                        return match.Value.Replace($"\"{rawPath}\"", $"\"{resolved}\"");
                    return match.Value;
                }
            );
        }

        private string ResolveRelativePath(string relativePath)
        {
            string uitkxDir = GetUitkxAssetDir();
            string combined = uitkxDir + "/" + relativePath;
            var parts = combined.Replace('\\', '/').Split('/');
            var stack = new List<string>();
            foreach (var p in parts)
            {
                if (p == "." || p == "")
                    continue;
                if (p == ".." && stack.Count > 0)
                    stack.RemoveAt(stack.Count - 1);
                else if (p != "..")
                    stack.Add(p);
            }
            return string.Join("/", stack);
        }

        /// <summary>
        /// Extracts the Unity asset directory (e.g. <c>Assets/UI</c>) from the
        /// absolute path of the <c>.uitkx</c> file being compiled.
        /// </summary>
        private string GetUitkxAssetDir()
        {
            string normalized = _filePath.Replace('\\', '/');
            int assetsIdx = normalized.IndexOf("/Assets/", StringComparison.OrdinalIgnoreCase);
            if (assetsIdx >= 0)
            {
                string assetPath = normalized.Substring(assetsIdx + 1); // "Assets/UI/File.uitkx"
                int lastSlash = assetPath.LastIndexOf('/');
                return lastSlash >= 0 ? assetPath.Substring(0, lastSlash) : "Assets";
            }
            // Fallback for non-Unity paths (test environments)
            string dir = Path.GetDirectoryName(_filePath)?.Replace('\\', '/') ?? "";
            return dir;
        }

        /// <summary>
        /// Extracts the Unity project root (parent of <c>Assets/</c>) from <see cref="_filePath"/>.
        /// Returns null when the path doesn't contain an <c>Assets/</c> segment.
        /// </summary>
        private string GetProjectRoot()
        {
            string normalized = _filePath.Replace('\\', '/');
            int assetsIdx = normalized.IndexOf("/Assets/", StringComparison.OrdinalIgnoreCase);
            if (assetsIdx >= 0)
                return normalized.Substring(0, assetsIdx);
            return null;
        }

        // ── StringBuilder helpers ─────────────────────────────────────────────

        private void L(string text) => _sb.AppendLine(text);
    }
}
