using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using ReactiveUITK.Language.Nodes;
using ReactiveUITK.Language.Parser;

namespace ReactiveUITK.SourceGenerator.Emitter
{
    /// <summary>
    /// Phase 4 — walks the AST produced by <see cref="UitkxParser"/> and emits a
    /// compilable C# partial-class source string.
    ///
    /// Output structure:
    /// <code>
    ///   // &lt;auto-generated /&gt;
    ///   namespace {Namespace}
    ///   {
    ///       public partial class {ComponentName}
    ///       {
    ///           private static VirtualNode[] __C(params object[] items) { ... }
    ///
    ///           public static VirtualNode Render(
    ///               Dictionary&lt;string,object&gt; __rawProps,
    ///               IReadOnlyList&lt;VirtualNode&gt; __children)
    ///           {
    ///               var props = ...;        // @props binding, if declared
    ///               // @code block content
    ///   #line N "File.uitkx"
    ///               return V.XXX(...);
    ///           }
    ///       }
    ///   }
    /// </code>
    ///
    /// The <c>#line</c> directives map generated C# lines back to the .uitkx source
    /// so that compiler errors and debugger breakpoints point at the template file.
    /// </summary>
    public static class CSharpEmitter
    {
        public static string Emit(
            string filePath,
            DirectiveSet directives,
            ImmutableArray<AstNode> rootNodes,
            PropsResolver resolver,
            IList<Diagnostic> diagnostics
        )
        {
            var ctx = new EmitContext(filePath, directives, resolver, diagnostics);
            return ctx.BuildSource(rootNodes);
        }
    }

    // ── Implementation ────────────────────────────────────────────────────────

    internal sealed class EmitContext
    {
        private readonly string _filePath;
        private readonly string _displayName; // bare filename for headers/diagnostics
        private readonly string _linePath; // normalized absolute path for #line directives
        private readonly DirectiveSet _directives;
        private readonly PropsResolver _resolver;
        private readonly IList<Diagnostic> _diagnostics;
        private readonly StringBuilder _sb = new StringBuilder(4096);

        // Indent constants
        private const string I2 = "        "; // 8sp — class member level
        private const string I3 = "            "; // 12sp — method body level
        private const string I4 = "                "; // 16sp — inside __C args

        private const string QVNode = "global::ReactiveUITK.Core.VirtualNode";

        internal EmitContext(
            string filePath,
            DirectiveSet directives,
            PropsResolver resolver,
            IList<Diagnostic> diagnostics
        )
        {
            _filePath = filePath;
            _directives = directives;
            _resolver = resolver;
            _diagnostics = diagnostics;
            _displayName = Path.GetFileName(filePath);
            _linePath = NormalizeLinePath(filePath);
        }

        // ── Top-level builder ─────────────────────────────────────────────────

        internal string BuildSource(ImmutableArray<AstNode> rootNodes)
        {
            // Separate @code blocks from markup
            var codeBlocks = ImmutableArray.CreateBuilder<CodeBlockNode>();
            var markupNodes = ImmutableArray.CreateBuilder<AstNode>();

            foreach (var n in rootNodes)
            {
                if (n is CodeBlockNode cb)
                    codeBlocks.Add(cb);
                else if (n is JsxCommentNode) { } // JSX comments are markup-only; skip in emitted C#
                else
                    markupNodes.Add(n);
            }

            // ── Header ───────────────────────────────────────────────────────
            L("// <auto-generated — do not edit — source: " + _displayName + " />");
            L("// Add class members or partial methods in the companion .cs file.");
            L("#nullable enable");
            L("#pragma warning disable CS0105  // duplicate using directives");
            L("#pragma warning disable CS8600  // null literal to non-nullable");
            L("#pragma warning disable CS8601  // null literal to nullable reference type");
            L("#pragma warning disable CS8602  // dereference of possibly null reference");
            L("#pragma warning disable CS8603  // possible null reference return");
            L("");

            // ── Usings ───────────────────────────────────────────────────────
            L("using System;");
            L("using System.Collections.Generic;");
            L("using System.Linq;");
            L("using ReactiveUITK;");
            L("using ReactiveUITK.Core;");
            L("using ReactiveUITK.Props.Typed;");
            foreach (var u in _directives.Usings)
                L($"using {u};");
            L("");

            // ── Namespace + class ────────────────────────────────────────────
            L($"namespace {_directives.Namespace}");
            L("{");
            L($"    [global::ReactiveUITK.UitkxElement(\"{_directives.ComponentName}\")]");
            L($"    public partial class {_directives.ComponentName}");
            L("    {");

            EmitHelperMethod();

            // ── @inject fields ────────────────────────────────────────────────
            // Each @inject directive emits a static field.  Set the value in the
            // companion (non-generated) partial class or via a static initialiser.
            if (!_directives.Injects.IsDefault && !_directives.Injects.IsEmpty)
            {
                L($"{I2}// @inject — set these fields before calling Render.");
                foreach (var inj in _directives.Injects)
                    L($"{I2}public static {inj.Type} {inj.Name};");
                L("");
            }

            // ── Render method signature ───────────────────────────────────────
            L($"{I2}public static {QVNode} Render(");
            L($"{I2}    global::ReactiveUITK.Core.IProps __rawProps,");
            L($"{I2}    IReadOnlyList<{QVNode}> __children)");
            L($"{I2}{{");

            // Props binding
            if (_directives.PropsTypeName is { } propsType)
            {
                L($"{I3}var props = (__rawProps as {propsType}) ?? new {propsType}();");
                L("");
            }

            // Function-style param variable bindings: var x = props.X;
            if (_directives.IsFunctionStyle
                && !_directives.FunctionParams.IsDefault
                && !_directives.FunctionParams.IsEmpty)
            {
                foreach (var fp in _directives.FunctionParams)
                {
                    string propName = ToPropName(fp.Name);
                    L($"{I3}var {fp.Name} = props.{propName};");
                }
                L("");
            }

            // @code block content (inside Render method, before return)
            var codeArr = codeBlocks.ToImmutable();
            foreach (var cb in codeArr)
                EmitCodeBlockContent(cb);

            // ── Return expression ─────────────────────────────────────────────
            var markup = markupNodes.ToImmutable();

            if (markup.IsEmpty)
            {
                L($"{I3}return ({QVNode})null;");
            }
            else if (markup.Length == 1)
            {
                // Single root — determine its #line
                int srcLine = markup[0].SourceLine;
                L($"#line {srcLine} \"{_linePath}\"");
                _sb.Append($"{I3}return ");
                EmitNode(markup[0]);
                _sb.AppendLine(";");
            }
            else
            {
                // Multiple roots — wrap in Fragment
                int srcLine = markup[0].SourceLine;
                L($"#line {srcLine} \"{_linePath}\"");
                _sb.Append($"{I3}return V.Fragment(key: null, __C(");
                EmitChildArgs(markup);
                _sb.AppendLine("));");
            }

            L($"{I2}}}"); // close Render

            // ── Auto-generated props class for function-style components ──────
            // Emitted as a NESTED type INSIDE the partial class, before its
            // closing brace (e.g. ComponentName.ComponentNameProps).
            if (_directives.IsFunctionStyle
                && !_directives.FunctionParams.IsDefault
                && !_directives.FunctionParams.IsEmpty)
            {
                EmitFunctionPropsClass();
            }

            L("    }"); // close class
            L("}"); // close namespace

            return _sb.ToString();
        }

        // ── @code block emission ──────────────────────────────────────────────

        /// <summary>
        /// Emits one <c>@code { }</c> block, splicing any embedded
        /// <c>return &lt;Tag .../&gt;</c> markup into their C# call equivalents.
        /// </summary>
        private void EmitCodeBlockContent(CodeBlockNode cb)
        {
            L($"#line {cb.SourceLine} \"{_linePath}\"");
            string codeText = cb.Code;

            if (!cb.ReturnMarkups.IsEmpty)
            {
                // Splice C# call expressions in place of each <Tag .../> markup
                var markups = cb.ReturnMarkups.OrderBy(m => m.StartOffsetInCodeBlock).ToArray();
                var spliced = new StringBuilder();
                int prev = 0;

                foreach (var m in markups)
                {
                    int start = m.StartOffsetInCodeBlock;
                    int end = m.EndOffsetInCodeBlock;

                    // Guard against out-of-range offsets
                    if (start < 0)
                        start = 0;
                    if (end < 0)
                        end = 0;
                    if (start > codeText.Length)
                        start = codeText.Length;
                    if (end > codeText.Length)
                        end = codeText.Length;

                    if (start > prev)
                        spliced.Append(codeText, prev, start - prev);

                    // Capture element C# emission without touching the main builder
                    int savedLen = _sb.Length;
                    EmitNode(m.Element);
                    string elemCs = _sb.ToString(savedLen, _sb.Length - savedLen);
                    _sb.Length = savedLen;

                    spliced.Append(elemCs.Trim());
                    prev = end;
                }

                if (prev < codeText.Length)
                    spliced.Append(codeText, prev, codeText.Length - prev);

                codeText = spliced.ToString();
            }

            // Apply React-style hook shorthand: useState( → Hooks.UseState( etc.
            codeText = ApplyHookAliases(codeText);

            foreach (var line in codeText.Split('\n'))
            {
                var trimmed = line.TrimEnd('\r');
                if (!string.IsNullOrEmpty(trimmed))
                    L($"{I3}{trimmed.TrimStart()}");
            }
            L("");
        }

        // ── Hook alias substitution ───────────────────────────────────────────

        private static readonly (string From, string To)[] s_hookAliases =
        {
            ("useState(", "Hooks.UseState("),
            ("useEffect(", "Hooks.UseEffect("),
            ("useLayoutEffect(", "Hooks.UseLayoutEffect("),
            ("useRef(", "Hooks.UseRef("),
            ("useCallback(", "Hooks.UseCallback("),
            ("useMemo(", "Hooks.UseMemo("),
            ("useContext(", "Hooks.UseContext("),
            ("useReducer(", "Hooks.UseReducer("),
            ("useSignal(", "Hooks.UseSignal("),
            ("useDeferredValue(", "Hooks.UseDeferredValue("),
            ("useTransition(", "Hooks.UseTransition("),
            ("provideContext(", "Hooks.ProvideContext("),
        };

        // Matches generic hook calls including up to 3 levels of nested type args:
        //   useContext<Color>(                         → level 1
        //   useRef<List<int>>(                         → level 2
        //   useMemo<Dictionary<string, List<Color>>>(  → level 3
        // The non-generic form is handled by s_hookAliases simple replacements above.
        private static readonly System.Text.RegularExpressions.Regex s_genericHookAliasRe =
            new System.Text.RegularExpressions.Regex(
                @"\b(useState|useEffect|useLayoutEffect|useRef|useCallback|useMemo|useContext|useReducer|useSignal|useDeferredValue|useTransition)(<(?:[^<>]|<(?:[^<>]|<[^<>]*>)*>)*>)\s*\(",
                System.Text.RegularExpressions.RegexOptions.Compiled
            );

        private static string ApplyHookAliases(string code)
        {
            // State-setter lambda sugar applies regardless of whether hooks are present:
            //   setFoo(v => v + 1)  →  setFoo.Set(v => v + 1)
            // Matches conventional React-style setter names: set followed by an
            // upper-case letter, called with a lambda argument.
            // Replacement: "$1.Set(" — group 1 is the setter name; the matched
            // opening "(" is consumed by "\(" in the pattern and rebuilt as ".Set(".
            code = s_setterLambdaRe.Replace(code, "$1.Set(");

            // Fast path: bail early if no lowercase hook names are present
            if (code.IndexOf("use", StringComparison.Ordinal) < 0)
                return code;
            // Handle generic hook calls (e.g. useContext<Color>() → Hooks.UseContext<Color>())
            code = s_genericHookAliasRe.Replace(
                code,
                m =>
                {
                    string hookName = m.Groups[1].Value;
                    string typeArgs = m.Groups[2].Value;
                    string pascalName = char.ToUpper(hookName[3]) + hookName.Substring(4);
                    return $"Hooks.Use{pascalName}{typeArgs}(";
                }
            );
            foreach (var (from, to) in s_hookAliases)
                code = code.Replace(from, to);

            return code;
        }

        // Matches:  setX(   setFoo(   setState(  followed immediately by a lambda
        // arg (single or multiple params), but NOT when it's setX.Set( already.
        private static readonly System.Text.RegularExpressions.Regex s_setterLambdaRe =
            new System.Text.RegularExpressions.Regex(
                @"\b(set[A-Z][a-zA-Z0-9_]*)\(\s*(?=[a-zA-Z_][a-zA-Z0-9_]*\s*=>|\([^)]*\)\s*=>)",
                System.Text.RegularExpressions.RegexOptions.Compiled
            );

        // ── __C helper method ─────────────────────────────────────────────────

        private void EmitHelperMethod()
        {
            // Generates a child-array builder that:
            //   • skips null VirtualNode entries (from @if without @else)
            //   • flattens VirtualNode[] arrays (from @foreach → .Select().ToArray())
            L($"{I2}private static {QVNode}[] __C(params object[] items)");
            L($"{I2}{{");
            L($"{I3}var list = new global::System.Collections.Generic.List<{QVNode}>();");
            L($"{I3}foreach (var __ci in items)");
            L($"{I3}{{");
            L($"{I4}if (__ci is {QVNode} __vn) {{ if (__vn != null) list.Add(__vn); }}");
            L(
                $"{I4}else if (__ci is global::System.Collections.Generic.IEnumerable<{QVNode}> __seq)"
            );
            L($"{I4}    foreach (var __sn in __seq) {{ if (__sn != null) list.Add(__sn); }}");
            L($"{I3}}}");
            L($"{I3}return list.ToArray();");
            L($"{I2}}}");
            L("");
        }

        // ── Node dispatch ─────────────────────────────────────────────────────

        private void EmitNode(AstNode node)
        {
            switch (node)
            {
                case ElementNode e:
                    EmitElementNode(e);
                    break;
                case TextNode t:
                    EmitTextNode(t);
                    break;
                case ExpressionNode x:
                    EmitExpressionNode(x);
                    break;
                case IfNode i:
                    EmitIfNode(i);
                    break;
                case ForeachNode f:
                    EmitForeachNode(f);
                    break;
                case ForNode fn:
                    EmitForNode(fn);
                    break;
                case WhileNode wn:
                    EmitWhileNode(wn);
                    break;
                case SwitchNode s:
                    EmitSwitchNode(s);
                    break;
                case BreakNode:
                case ContinueNode:
                    _sb.Append($"({QVNode})null /* loop-flow statement */");
                    break;
                case CodeBlockNode:
                    // @code blocks are hoisted before return; skip inline
                    _sb.Append($"({QVNode})null");
                    break;
                case JsxCommentNode:
                    // JSX comments emit nothing to C#
                    break;
                default:
                    _sb.Append($"({QVNode})null /* unhandled: {node.GetType().Name} */");
                    break;
            }
        }

        // ── ElementNode ───────────────────────────────────────────────────────

        private void EmitElementNode(ElementNode el)
        {
            // Include the declaring namespace so that sibling components (defined
            // in the same @namespace) are found without requiring an explicit @using.
            var searchNamespaces = string.IsNullOrEmpty(_directives.Namespace)
                ? _directives.Usings
                : _directives.Usings.Add(_directives.Namespace!);
            var res = _resolver.Resolve(el.TagName, searchNamespaces, out var diagDesc);

            if (diagDesc != null)
            {
                var loc = Location.Create(_filePath, default, default);
                _diagnostics.Add(Diagnostic.Create(diagDesc, loc, el.TagName));
            }

            string keyExpr = ExtractKey(el.Attributes);

            switch (res.Kind)
            {
                case TagResolutionKind.Fragment:
                    EmitFragment(keyExpr, el.Children);
                    break;

                case TagResolutionKind.BuiltinTyped:
                    EmitBuiltinTyped(res, el.Attributes, keyExpr, el.Children);
                    break;

                case TagResolutionKind.BuiltinDictionary:
                    EmitBuiltinDict(res, el.Attributes, keyExpr, el.Children);
                    break;

                case TagResolutionKind.BuiltinText:
                {
                    string txt = GetAttrValue(el.Attributes, "text") ?? "\"\"";
                    _sb.Append($"V.Text({txt}, key: {keyExpr})");
                    break;
                }

                case TagResolutionKind.BuiltinSuspense:
                    EmitSuspense(el.Attributes, keyExpr, el.Children);
                    break;

                case TagResolutionKind.FuncComponent:
                    EmitFuncComponent(res, el.Attributes, keyExpr, el.Children, searchNamespaces);
                    break;

                case TagResolutionKind.Unknown:
                    _sb.Append($"({QVNode})null /* unknown: {el.TagName} */");
                    break;
            }
        }

        private void EmitBuiltinTyped(
            TagResolution res,
            ImmutableArray<AttributeNode> attrs,
            string keyExpr,
            ImmutableArray<AstNode> children
        )
        {
            // UITKX0002 — validate attribute names against known Props properties
            if (res.PropsTypeName != null)
            {
                var knownProps = _resolver.GetPublicPropertyNames(res.PropsTypeName);
                if (knownProps.Count > 0)
                {
                    foreach (var attr in attrs)
                    {
                        if (IsKey(attr.Name))
                            continue;
                        string mapped = ToPropName(attr.Name);
                        if (!knownProps.Contains(mapped))
                        {
                            string? suggestion = FindClosestMatch(mapped, knownProps);
                            string hint =
                                suggestion != null ? $". Did you mean '{suggestion}'?" : "";
                            var loc = Location.Create(_filePath, default, default);
                            _diagnostics.Add(
                                Diagnostic.Create(
                                    UitkxDiagnostics.UnknownAttribute,
                                    loc,
                                    attr.Name,
                                    res.MethodName.ToLowerInvariant(),
                                    hint
                                )
                            );
                        }
                    }
                }
            }

            _sb.Append($"V.{res.MethodName}(new {res.PropsTypeName} {{");

            bool first = true;
            foreach (var attr in attrs)
            {
                if (IsKey(attr.Name))
                    continue;
                if (!first)
                    _sb.Append(", ");
                first = false;
                _sb.Append($" {ToPropName(attr.Name)} = {AttrVal(attr.Value)}");
            }

            _sb.Append(" }, key: ");
            _sb.Append(keyExpr);

            if (res.AcceptsChildren && !children.IsEmpty)
            {
                _sb.Append(", __C(");
                EmitChildArgs(children);
                _sb.Append(")");
            }

            _sb.Append(")");
        }

        private void EmitBuiltinDict(
            TagResolution res,
            ImmutableArray<AttributeNode> attrs,
            string keyExpr,
            ImmutableArray<AstNode> children
        )
        {
            bool hasNonKeyAttrs = false;
            foreach (var a in attrs)
            {
                if (!IsKey(a.Name))
                {
                    hasNonKeyAttrs = true;
                    break;
                }
            }

            if (hasNonKeyAttrs)
            {
                _sb.Append($"V.{res.MethodName}(new Dictionary<string, object>");
                _sb.Append(" {");
                bool first = true;
                foreach (var attr in attrs)
                {
                    if (IsKey(attr.Name))
                        continue;
                    if (!first)
                        _sb.Append(", ");
                    first = false;
                    _sb.Append($" {{ \"{attr.Name}\", {AttrVal(attr.Value)} }}");
                }
                _sb.Append(" }");
            }
            else
            {
                _sb.Append($"V.{res.MethodName}((Dictionary<string, object>)null");
            }

            _sb.Append($", key: {keyExpr}");

            if (!children.IsEmpty)
            {
                _sb.Append(", __C(");
                EmitChildArgs(children);
                _sb.Append(")");
            }

            _sb.Append(")");
        }

        private void EmitFuncComponent(
            TagResolution res,
            ImmutableArray<AttributeNode> attrs,
            string keyExpr,
            ImmutableArray<AstNode> children,
            ImmutableArray<string> searchNamespaces
        )
        {
            string typeName = res.FuncTypeName!;

            // Pull out a bare ref={x} attribute before the loop so it can be
            // routed to the component's MutableRef<T> param rather than rendered
            // as a literal "ref" property (which doesn't exist on any Props class).
            AttributeNode? refAttr = null;
            foreach (var a in attrs)
            {
                if (IsRefAttr(a.Name)) { refAttr = a; break; }
            }

            if (res.FuncPropsTypeName != null)
            {
                // ── Typed path: V.Func<PropsType>(TypeName.Render, new PropsType { ... }) ──
                string propsTypeName = res.FuncPropsTypeName;
                _sb.Append($"V.Func<{propsTypeName}>({typeName}.Render, new {propsTypeName} {{");

                bool first = true;
                foreach (var attr in attrs)
                {
                    if (IsKey(attr.Name) || IsRefAttr(attr.Name))
                        continue;
                    if (!first)
                        _sb.Append(", ");
                    first = false;
                    _sb.Append($" {ToPropName(attr.Name)} = {AttrVal(attr.Value)}");
                }

                // Route ref={x} to the component's MutableRef<T> parameter.
                if (refAttr != null)
                {
                    var lookupResult = _resolver.TryGetRefParamPropName(
                        typeName, propsTypeName, searchNamespaces, out string? refPropName
                    );
                    switch (lookupResult)
                    {
                        case PropsResolver.RefParamLookupResult.Found:
                            if (!first) _sb.Append(",");
                            _sb.Append($" {refPropName} = {AttrVal(refAttr.Value)}");
                            break;

                        case PropsResolver.RefParamLookupResult.None:
                        {
                            var loc = Location.Create(_filePath, default, default);
                            _diagnostics.Add(
                                Diagnostic.Create(
                                    UitkxDiagnostics.RefOnComponentWithNoRefParam,
                                    loc,
                                    typeName
                                )
                            );
                            break;
                        }

                        case PropsResolver.RefParamLookupResult.Ambiguous:
                        {
                            var loc = Location.Create(_filePath, default, default);
                            _diagnostics.Add(
                                Diagnostic.Create(
                                    UitkxDiagnostics.RefOnComponentWithAmbiguousRefParam,
                                    loc,
                                    typeName
                                )
                            );
                            break;
                        }
                    }
                }

                _sb.Append(" }");
            }
            else
            {
                // ── No-props path: V.Func(TypeName.Render, ...) ──
                // ref={x} on a no-props component has no route — emit UITKX0020.
                if (refAttr != null)
                {
                    var loc = Location.Create(_filePath, default, default);
                    _diagnostics.Add(
                        Diagnostic.Create(
                            UitkxDiagnostics.RefOnComponentWithNoRefParam,
                            loc,
                            typeName
                        )
                    );
                }
                _sb.Append($"V.Func({typeName}.Render");
            }

            _sb.Append($", key: {keyExpr}");

            if (!children.IsEmpty)
            {
                // Use named parameter to skip the optional 'bool memoize' and
                // 'Func<TProps,TProps,bool> memoCompare' slots that sit between
                // 'key' and 'children' in the V.Func<TProps> overload.
                _sb.Append(", children: __C(");
                EmitChildArgs(children);
                _sb.Append(")");
            }

            _sb.Append(")");
        }

        // ── Auto-generated props class ────────────────────────────────────────

        /// <summary>
        /// Emits a public sealed class <c>{ComponentName}Props : IProps</c> that
        /// holds one auto-property per entry in <see cref="DirectiveSet.FunctionParams"/>.
        ///
        /// Generated structure (inside the same namespace, after the partial class closing brace):
        /// <code>
        ///   public sealed class FooProps : global::ReactiveUITK.Core.IProps
        ///   {
        ///       public int X { get; set; } = 0;
        ///       public string Label { get; set; } = "hi";
        ///
        ///       public override bool Equals(object obj) { ... }
        ///       public override int GetHashCode() { ... }
        ///   }
        /// </code>
        /// </summary>
        private void EmitFunctionPropsClass()
        {
            string className = _directives.ComponentName + "Props";
            var fps = _directives.FunctionParams;

            L("");
            L($"    /// <summary>Auto-generated typed props for <see cref=\"{_directives.ComponentName}\"/>.</summary>");
            L($"    public sealed class {className} : global::ReactiveUITK.Core.IProps");
            L("    {");

            // Properties
            foreach (var fp in fps)
            {
                string propName = ToPropName(fp.Name);
                string def = string.IsNullOrWhiteSpace(fp.DefaultValue) ? "default" : fp.DefaultValue!;
                L($"        public {fp.Type} {propName} {{ get; set; }} = {def};");
            }

            L("");

            // Equals
            L("        public override bool Equals(object? obj)");
            L("        {");
            L($"            if (obj is not {className} other) return false;");
            bool firstEq = true;
            foreach (var fp in fps)
            {
                string propName = ToPropName(fp.Name);
                string conjunction = firstEq ? "            return " : "                && ";
                firstEq = false;
                L($"{conjunction}global::System.Collections.Generic.EqualityComparer<{fp.Type}>.Default.Equals({propName}, other.{propName})");
            }
            if (firstEq) // no params — always equal
                L("            return true;");
            else
                L("                ;"); // close the boolean chain with a dangling semicolon
            L("        }");

            L("");

            // GetHashCode
            L("        public override int GetHashCode()");
            L("        {");
            L("            unchecked");
            L("            {");
            L("                int hash = 17;");
            foreach (var fp in fps)
            {
                string propName = ToPropName(fp.Name);
                L($"                hash = hash * 31 + global::System.Collections.Generic.EqualityComparer<{fp.Type}>.Default.GetHashCode({propName}!);");
            }
            L("                return hash;");
            L("            }");
            L("        }");

            L("    }");
        }

        // ── Suspense built-in ─────────────────────────────────────────────────
        // Emits V.Suspense(isReady, [pendingTask,] fallback, key:..., children...)
        // from well-known attribute names: isReady / is-ready, pendingTask /
        // pending-task, and fallback.
        private void EmitSuspense(
            ImmutableArray<AttributeNode> attrs,
            string keyExpr,
            ImmutableArray<AstNode> children
        )
        {
            string? isReady      = GetAttrValue(attrs, "isReady") ?? GetAttrValue(attrs, "is-ready");
            string? pendingTask  = GetAttrValue(attrs, "pendingTask") ?? GetAttrValue(attrs, "pending-task");
            string? fallbackAttr = GetAttrValue(attrs, "fallback");

            string isReadyArg    = isReady      ?? "() => false";
            string fallbackArg   = fallbackAttr ?? $"({QVNode})null";

            _sb.Append("V.Suspense(");
            _sb.Append(isReadyArg);
            _sb.Append(", ");
            if (pendingTask != null)
            {
                _sb.Append(pendingTask);
                _sb.Append(", ");
            }
            _sb.Append(fallbackArg);
            _sb.Append($", key: {keyExpr}");

            if (!children.IsEmpty)
            {
                _sb.Append(", ");
                EmitChildArgs(children);
            }

            _sb.Append(")");
        }

        private void EmitFragment(string keyExpr, ImmutableArray<AstNode> children)
        {
            if (children.IsEmpty)
            {
                _sb.Append($"V.Fragment(key: {keyExpr})");
            }
            else
            {
                _sb.Append($"V.Fragment(key: {keyExpr}, __C(");
                EmitChildArgs(children);
                _sb.Append("))");
            }
        }

        // ── Control flow ──────────────────────────────────────────────────────

        private void EmitIfNode(IfNode ifn)
        {
            if (ifn.Branches.IsEmpty)
            {
                _sb.Append($"({QVNode})null");
                return;
            }

            // Stable-type strategy:
            // 1. The outer Fragment ensures the TYPE at THIS node's position in the parent
            //    children array is always Fragment (never label, never box).
            // 2. Each branch is ALSO wrapped in a Fragment (via EmitBodyAsFragment) so the
            //    ternary value that sits at position-0 of the outer Fragment is ALWAYS a
            //    Fragment regardless of which branch fires.
            //
            // Without (2), switching from a single-node branch (Label) to a multi-node
            // branch (Fragment) still changes the type at that inner position. The reconciler
            // would delete the old fiber and call CommitPlacement on the new one, which
            // only ever calls AppendChild — placing the new children at the END of the
            // host parent instead of at the correct index.
            _sb.Append("V.Fragment(key: null, __C(");

            // Build ternary chain:
            // (cond1) ? V.Fragment(...body1) : (cond2) ? V.Fragment(...body2) : V.Fragment()
            for (int i = 0; i < ifn.Branches.Length; i++)
            {
                var branch = ifn.Branches[i];

                if (branch.Condition == null)
                {
                    // @else — terminal branch, always a Fragment
                    EmitBodyAsFragment(branch.Body);
                    _sb.Append("))");
                    return;
                }

                _sb.Append($"({branch.Condition}) ? ");
                EmitBodyAsFragment(branch.Body);
                _sb.Append(" : ");

                // Last branch with no @else — emit an empty Fragment (not null) so the
                // type at position-0 of the outer Fragment is always Fragment.
                if (i == ifn.Branches.Length - 1)
                    _sb.Append("V.Fragment(key: null)");
            }
            _sb.Append("))");
        }

        private void EmitForNode(ForNode fn)
        {
            // Emit as IIFE building a list — keeps `i` properly in scope
            _sb.Append($"((System.Func<{QVNode}[]>)(() => {{ ");
            _sb.Append($"var __r = new System.Collections.Generic.List<{QVNode}>(); ");
            _sb.Append($"for ({fn.ForExpression}) {{ ");
            if (ContainsLoopFlow(fn.Body))
            {
                EmitLoopBodyStatements(fn.Body);
            }
            else
            {
                _sb.Append("__r.Add(");
                EmitBodyExpr(fn.Body);
                _sb.Append("); ");
            }
            _sb.Append("} return __r.ToArray(); }))()");
        }

        private void EmitWhileNode(WhileNode wn)
        {
            // Emit as IIFE building a list
            _sb.Append($"((System.Func<{QVNode}[]>)(() => {{ ");
            _sb.Append($"var __r = new System.Collections.Generic.List<{QVNode}>(); ");
            _sb.Append($"while ({wn.Condition}) {{ ");
            if (ContainsLoopFlow(wn.Body))
            {
                EmitLoopBodyStatements(wn.Body);
            }
            else
            {
                _sb.Append("__r.Add(");
                EmitBodyExpr(wn.Body);
                _sb.Append("); ");
            }
            _sb.Append("} return __r.ToArray(); }))()");
        }

        private void EmitForeachNode(ForeachNode forn)
        {
            // UITKX0009 — warn if direct element children lack a key attribute
            foreach (var bodyNode in forn.Body)
            {
                if (bodyNode is ElementNode elCheck && !HasKey(elCheck.Attributes))
                {
                    var loc = Location.Create(_filePath, default, default);
                    _diagnostics.Add(
                        Diagnostic.Create(
                            UitkxDiagnostics.ForeachMissingKey,
                            loc,
                            string.IsNullOrEmpty(elCheck.TagName) ? "fragment" : elCheck.TagName,
                            elCheck.SourceLine,
                            _displayName
                        )
                    );
                }
            }

            string varName = ExtractVarName(forn.IteratorDeclaration);
            _sb.Append($"({forn.CollectionExpression}).Select(({varName}) => ");

            if (forn.Body.IsEmpty)
                _sb.Append($"({QVNode})null");
            else if (forn.Body.Length == 1)
                EmitNode(forn.Body[0]);
            else
            {
                _sb.Append("V.Fragment(key: null, __C(");
                EmitChildArgs(forn.Body);
                _sb.Append("))");
            }

            _sb.Append(").ToArray()");
        }

        private void EmitSwitchNode(SwitchNode sw)
        {
            // Same stable-type strategy as EmitIfNode:
            // outer Fragment keeps parent position stable; each arm is also always a Fragment
            // so the switch expression result type never changes.
            _sb.Append("V.Fragment(key: null, __C(");
            _sb.Append($"({sw.SwitchExpression}) switch {{");

            foreach (var c in sw.Cases)
            {
                _sb.Append(c.ValueExpression == null ? " _ => " : $" {c.ValueExpression} => ");

                EmitBodyAsFragment(c.Body);
                _sb.Append(",");
            }

            // Ensure there is always a default to keep C# exhaustiveness happy.
            // Use an empty Fragment (not null) so the switch result is always Fragment.
            if (sw.Cases.Length > 0 && sw.Cases[sw.Cases.Length - 1].ValueExpression != null)
                _sb.Append(" _ => V.Fragment(key: null),");

            _sb.Append(" }");
            _sb.Append("))");
        }

        private void EmitLoopBodyStatements(ImmutableArray<AstNode> body)
        {
            foreach (var node in body)
                EmitLoopBodyStatement(node);
        }

        private void EmitLoopBodyStatement(AstNode node)
        {
            switch (node)
            {
                case JsxCommentNode:
                    return;

                case BreakNode:
                    _sb.Append("break; ");
                    return;

                case ContinueNode:
                    _sb.Append("continue; ");
                    return;

                case IfNode ifNode when ContainsLoopFlow(ifNode):
                    EmitLoopIfStatement(ifNode);
                    return;

                case ForNode:
                case WhileNode:
                case ForeachNode:
                    _sb.Append("__r.AddRange(");
                    EmitNode(node);
                    _sb.Append("); ");
                    return;

                default:
                    _sb.Append("__r.Add(");
                    EmitNode(node);
                    _sb.Append("); ");
                    return;
            }
        }

        private void EmitLoopIfStatement(IfNode ifn)
        {
            if (ifn.Branches.IsEmpty)
                return;

            for (int i = 0; i < ifn.Branches.Length; i++)
            {
                var branch = ifn.Branches[i];
                if (i == 0)
                {
                    _sb.Append($"if ({branch.Condition}) {{ ");
                }
                else if (branch.Condition != null)
                {
                    _sb.Append($"else if ({branch.Condition}) {{ ");
                }
                else
                {
                    _sb.Append("else { ");
                }

                EmitLoopBodyStatements(branch.Body);
                _sb.Append("} ");
            }
        }

        private static bool ContainsLoopFlow(ImmutableArray<AstNode> nodes)
        {
            foreach (var node in nodes)
                if (ContainsLoopFlow(node))
                    return true;
            return false;
        }

        private static bool ContainsLoopFlow(AstNode node)
        {
            switch (node)
            {
                case BreakNode:
                case ContinueNode:
                    return true;

                case IfNode ifn:
                    foreach (var branch in ifn.Branches)
                        if (ContainsLoopFlow(branch.Body))
                            return true;
                    return false;

                case ElementNode el:
                    return ContainsLoopFlow(el.Children);

                case ForeachNode fe:
                    return ContainsLoopFlow(fe.Body);

                case ForNode fn:
                    return ContainsLoopFlow(fn.Body);

                case WhileNode wn:
                    return ContainsLoopFlow(wn.Body);

                case SwitchNode sw:
                    foreach (var c in sw.Cases)
                        if (ContainsLoopFlow(c.Body))
                            return true;
                    return false;

                default:
                    return false;
            }
        }

        // ── Leaf nodes ────────────────────────────────────────────────────────

        private void EmitTextNode(TextNode txt)
        {
            string s = txt.Content.Trim();
            if (string.IsNullOrEmpty(s))
            {
                _sb.Append($"({QVNode})null /* whitespace text */");
                return;
            }
            _sb.Append($"V.Text(\"{EscStr(s)}\")");
        }

        private void EmitExpressionNode(ExpressionNode ex)
        {
            // @(expr) — user is responsible for returning VirtualNode-compatible value
            _sb.Append($"(({QVNode})({ex.Expression}))");
        }

        // ── Body expression helpers ───────────────────────────────────────────

        /// <summary>
        /// Emits the body of an @if / @switch branch as a V.Fragment, always.
        /// This guarantees that the type of the value produced by every branch of a
        /// ternary / switch expression is always VirtualNodeType.Fragment, so the
        /// reconciler never needs to CommitPlacement after initial mount.
        /// </summary>
        private void EmitBodyAsFragment(ImmutableArray<AstNode> body)
        {
            _sb.Append("V.Fragment(key: null, __C(");
            if (!body.IsEmpty)
                EmitChildArgs(body);
            _sb.Append("))");
        }

        /// <summary>
        /// Emits the body of a branch as a single expression.
        /// Multiple-child bodies are wrapped in V.Fragment.
        /// </summary>
        private void EmitBodyExpr(ImmutableArray<AstNode> body)
        {
            if (body.IsEmpty)
            {
                _sb.Append($"({QVNode})null");
            }
            else if (body.Length == 1)
            {
                EmitNode(body[0]);
            }
            else
            {
                _sb.Append("V.Fragment(key: null, __C(");
                EmitChildArgs(body);
                _sb.Append("))");
            }
        }

        /// <summary>
        /// Emits the argument list for a __C(...) call: one child per line,
        /// each preceded by a #line directive.
        /// </summary>
        private void EmitChildArgs(ImmutableArray<AstNode> children)
        {
            // UITKX0010 — warn on duplicate static string keys among siblings
            CheckDuplicateKeys(children);

            bool first = true;
            for (int i = 0; i < children.Length; i++)
            {
                // JSX comments emit nothing — skip to avoid dangling commas
                if (children[i] is JsxCommentNode)
                    continue;

                if (!first)
                    _sb.Append(",");
                first = false;

                _sb.AppendLine();
                if (children[i].SourceLine > 0)
                {
                    _sb.AppendLine($"#line {children[i].SourceLine} \"{_linePath}\"");
                }
                _sb.Append(I4);
                EmitNode(children[i]);
            }
            if (!first)
            {
                _sb.AppendLine();
                _sb.Append(I4);
            }
        }

        // ── Attribute helpers ─────────────────────────────────────────────────

        private static bool HasKey(ImmutableArray<AttributeNode> attrs)
        {
            foreach (var a in attrs)
                if (IsKey(a.Name))
                    return true;
            return false;
        }

        private void CheckDuplicateKeys(ImmutableArray<AstNode> children)
        {
            var seen = new HashSet<string>(StringComparer.Ordinal);
            foreach (var child in children)
            {
                if (child is not ElementNode el)
                    continue;
                foreach (var attr in el.Attributes)
                {
                    if (!IsKey(attr.Name))
                        continue;
                    if (attr.Value is StringLiteralValue slv)
                    {
                        if (!seen.Add(slv.Value))
                        {
                            var loc = Location.Create(_filePath, default, default);
                            _diagnostics.Add(
                                Diagnostic.Create(
                                    UitkxDiagnostics.DuplicateSiblingKey,
                                    loc,
                                    slv.Value,
                                    _displayName
                                )
                            );
                        }
                    }
                }
            }
        }

        // ── Did-you-mean helpers ─────────────────────────────────────

        private static string? FindClosestMatch(string name, HashSet<string> candidates)
        {
            string? best = null;
            int bestDist = 3; // only suggest if within edit-distance 2
            foreach (var c in candidates)
            {
                int dist = LevenshteinDistance(name, c);
                if (dist < bestDist)
                {
                    bestDist = dist;
                    best = c;
                }
            }
            return best;
        }

        private static int LevenshteinDistance(string a, string b)
        {
            if (a.Length == 0)
                return b.Length;
            if (b.Length == 0)
                return a.Length;
            var d = new int[a.Length + 1, b.Length + 1];
            for (int i = 0; i <= a.Length; i++)
                d[i, 0] = i;
            for (int j = 0; j <= b.Length; j++)
                d[0, j] = j;
            for (int i = 1; i <= a.Length; i++)
            for (int j = 1; j <= b.Length; j++)
                d[i, j] = Math.Min(
                    Math.Min(d[i - 1, j] + 1, d[i, j - 1] + 1),
                    d[i - 1, j - 1]
                        + (
                            char.ToLowerInvariant(a[i - 1]) == char.ToLowerInvariant(b[j - 1])
                                ? 0
                                : 1
                        )
                );
            return d[a.Length, b.Length];
        }

        private static string ExtractKey(ImmutableArray<AttributeNode> attrs)
        {
            foreach (var a in attrs)
                if (IsKey(a.Name))
                    return AttrVal(a.Value);
            return "null";
        }

        private static string? GetAttrValue(ImmutableArray<AttributeNode> attrs, string name)
        {
            foreach (var a in attrs)
                if (string.Equals(a.Name, name, StringComparison.OrdinalIgnoreCase))
                    return AttrVal(a.Value);
            return null;
        }

        private static string AttrVal(AttributeValue v) =>
            v switch
            {
                StringLiteralValue slv => $"\"{EscStr(slv.Value)}\"",
                // Apply setter-lambda sugar: setFoo(v => v+1) → setFoo.Set(v => v+1)
                CSharpExpressionValue cev => s_setterLambdaRe.Replace(cev.Expression, "$1.Set("),
                BooleanShorthandValue => "true",
                _ => "null",
            };

        private static bool IsKey(string name) =>
            string.Equals(name, "key", StringComparison.OrdinalIgnoreCase);

        private static bool IsRefAttr(string name) =>
            string.Equals(name, "ref", StringComparison.OrdinalIgnoreCase);

        private static string ToPropName(string attrName)
        {
            if (string.IsNullOrEmpty(attrName))
                return attrName;
            return char.ToUpperInvariant(attrName[0]) + attrName.Substring(1);
        }

        // ── String / variable helpers ─────────────────────────────────────────

        private static string EscStr(string s) =>
            s.Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\n", "\\n")
                .Replace("\r", "\\r")
                .Replace("\t", "\\t");

        private static string ExtractVarName(string declaration)
        {
            if (string.IsNullOrWhiteSpace(declaration))
                return "__item";
            var parts = declaration
                .Trim()
                .Split(new[] { ' ', '\t' }, StringSplitOptions.RemoveEmptyEntries);
            return parts.Length > 0 ? parts[parts.Length - 1] : "__item";
        }

        private static string NormalizeLinePath(string filePath)
        {
            string fullPath;
            try
            {
                fullPath = Path.GetFullPath(filePath);
            }
            catch
            {
                fullPath = filePath;
            }

            return fullPath.Replace('\\', '/').Replace("\"", "\\\"");
        }

        // ── StringBuilder helpers ─────────────────────────────────────────────

        private void L(string text) => _sb.AppendLine(text);
    }
}
