using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using ReactiveUITK.Language.Nodes;
using ReactiveUITK.Language.Parser;

namespace ReactiveUITK.SourceGenerator.Emitter
{
    /// <summary>
    /// Phase 4 — walks the AST produced by <see cref="UitkxParser"/> and emits a
    /// compilable C# partial-class source string.
    ///
    /// Output structure:
    /// <code>
    ///   // &lt;auto-generated /&gt;
    ///   namespace {Namespace}
    ///   {
    ///       public partial class {ComponentName}
    ///       {
    ///           private static VirtualNode[] __C(params object[] items) { ... }
    ///
    ///           public static VirtualNode Render(
    ///               Dictionary&lt;string,object&gt; __rawProps,
    ///               IReadOnlyList&lt;VirtualNode&gt; __children)
    ///           {
    ///               var props = ...;        // @props binding, if declared
    ///               // @code block content
    ///   #line N "File.uitkx"
    ///               return V.XXX(...);
    ///           }
    ///       }
    ///   }
    /// </code>
    ///
    /// The <c>#line</c> directives map generated C# lines back to the .uitkx source
    /// so that compiler errors and debugger breakpoints point at the template file.
    /// </summary>
    public static class CSharpEmitter
    {
        public static string Emit(
            string filePath,
            DirectiveSet directives,
            ImmutableArray<AstNode> rootNodes,
            PropsResolver resolver,
            IList<Diagnostic> diagnostics
        )
        {
            var ctx = new EmitContext(filePath, directives, resolver, diagnostics);
            return ctx.BuildSource(rootNodes);
        }
    }

    // ── Implementation ────────────────────────────────────────────────────────

    internal sealed class EmitContext
    {
        private readonly string _filePath;
        private readonly string _displayName; // bare filename for headers/diagnostics
        private readonly string _linePath; // normalized absolute path for #line directives
        private readonly DirectiveSet _directives;
        private readonly PropsResolver _resolver;
        private readonly IList<Diagnostic> _diagnostics;
        private readonly StringBuilder _sb = new StringBuilder(4096);

        // Indent constants
        private const string I2 = "        "; // 8sp — class member level
        private const string I3 = "            "; // 12sp — method body level
        private const string I4 = "                "; // 16sp — inside __C args

        private const string QVNode = "global::ReactiveUITK.Core.VirtualNode";

        internal EmitContext(
            string filePath,
            DirectiveSet directives,
            PropsResolver resolver,
            IList<Diagnostic> diagnostics
        )
        {
            _filePath = filePath;
            _directives = directives;
            _resolver = resolver;
            _diagnostics = diagnostics;
            _displayName = Path.GetFileName(filePath);
            _linePath = NormalizeLinePath(filePath);
        }

        // ── Top-level builder ─────────────────────────────────────────────────

        internal string BuildSource(ImmutableArray<AstNode> rootNodes)
        {
            // Separate @code blocks from markup
            var codeBlocks = ImmutableArray.CreateBuilder<CodeBlockNode>();
            var markupNodes = ImmutableArray.CreateBuilder<AstNode>();

            foreach (var n in rootNodes)
            {
                if (n is CodeBlockNode cb)
                    codeBlocks.Add(cb);
                else if (n is JsxCommentNode) { } // JSX comments are markup-only; skip in emitted C#
                else
                    markupNodes.Add(n);
            }

            // ── Header ───────────────────────────────────────────────────────
            L("// <auto-generated — do not edit — source: " + _displayName + " />");
            L("// Add class members or partial methods in the companion .cs file.");
            L("#nullable enable");
            L("#pragma warning disable CS0105  // duplicate using directives");
            L("#pragma warning disable CS8600  // null literal to non-nullable");
            L("#pragma warning disable CS8603  // possible null reference return");
            L("");

            // ── Usings ───────────────────────────────────────────────────────
            L("using System;");
            L("using System.Collections.Generic;");
            L("using System.Linq;");
            L("using ReactiveUITK;");
            L("using ReactiveUITK.Core;");
            L("using ReactiveUITK.Props.Typed;");
            foreach (var u in _directives.Usings)
                L($"using {u};");
            L("");

            // ── Namespace + class ────────────────────────────────────────────
            L($"namespace {_directives.Namespace}");
            L("{");
            L($"    [global::ReactiveUITK.UitkxElement(\"{_directives.ComponentName}\")]");
            L($"    public partial class {_directives.ComponentName}");
            L("    {");

            EmitHelperMethod();

            // ── @inject fields ────────────────────────────────────────────────
            // Each @inject directive emits a static field.  Set the value in the
            // companion (non-generated) partial class or via a static initialiser.
            if (!_directives.Injects.IsDefault && !_directives.Injects.IsEmpty)
            {
                L($"{I2}// @inject — set these fields before calling Render.");
                foreach (var inj in _directives.Injects)
                    L($"{I2}public static {inj.Type} {inj.Name};");
                L("");
            }

            // ── Render method signature ───────────────────────────────────────
            L($"{I2}public static {QVNode} Render(");
            L($"{I2}    Dictionary<string, object> __rawProps,");
            L($"{I2}    IReadOnlyList<{QVNode}> __children)");
            L($"{I2}{{");

            // Props binding
            if (_directives.PropsTypeName is { } propsType)
            {
                L($"{I3}var props = __rawProps != null");
                L($"{I3}    && __rawProps.TryGetValue(\"__typed\", out var __tp)");
                L($"{I3}    && __tp is {propsType} __p");
                L($"{I3}    ? __p : new {propsType}();");
                L("");
            }

            // @code block content (inside Render method, before return)
            var codeArr = codeBlocks.ToImmutable();
            foreach (var cb in codeArr)
                EmitCodeBlockContent(cb);

            // ── Return expression ─────────────────────────────────────────────
            var markup = markupNodes.ToImmutable();

            if (markup.IsEmpty)
            {
                L($"{I3}return ({QVNode})null;");
            }
            else if (markup.Length == 1)
            {
                // Single root — determine its #line
                int srcLine = markup[0].SourceLine;
                L($"#line {srcLine} \"{_linePath}\"");
                _sb.Append($"{I3}return ");
                EmitNode(markup[0]);
                _sb.AppendLine(";");
            }
            else
            {
                // Multiple roots — wrap in Fragment
                int srcLine = markup[0].SourceLine;
                L($"#line {srcLine} \"{_linePath}\"");
                _sb.Append($"{I3}return V.Fragment(key: null, __C(");
                EmitChildArgs(markup);
                _sb.AppendLine("));");
            }

            L($"{I2}}}"); // close Render
            L("    }"); // close class
            L("}"); // close namespace

            return _sb.ToString();
        }

        // ── @code block emission ──────────────────────────────────────────────

        /// <summary>
        /// Emits one <c>@code { }</c> block, splicing any embedded
        /// <c>return &lt;Tag .../&gt;</c> markup into their C# call equivalents.
        /// </summary>
        private void EmitCodeBlockContent(CodeBlockNode cb)
        {
            L($"#line {cb.SourceLine} \"{_linePath}\"");
            string codeText = cb.Code;

            if (!cb.ReturnMarkups.IsEmpty)
            {
                // Splice C# call expressions in place of each <Tag .../> markup
                var markups = cb.ReturnMarkups.OrderBy(m => m.StartOffsetInCodeBlock).ToArray();
                var spliced = new StringBuilder();
                int prev = 0;

                foreach (var m in markups)
                {
                    int start = m.StartOffsetInCodeBlock;
                    int end = m.EndOffsetInCodeBlock;

                    // Guard against out-of-range offsets
                    if (start < 0)
                        start = 0;
                    if (end < 0)
                        end = 0;
                    if (start > codeText.Length)
                        start = codeText.Length;
                    if (end > codeText.Length)
                        end = codeText.Length;

                    if (start > prev)
                        spliced.Append(codeText, prev, start - prev);

                    // Capture element C# emission without touching the main builder
                    int savedLen = _sb.Length;
                    EmitNode(m.Element);
                    string elemCs = _sb.ToString(savedLen, _sb.Length - savedLen);
                    _sb.Length = savedLen;

                    spliced.Append(elemCs.Trim());
                    prev = end;
                }

                if (prev < codeText.Length)
                    spliced.Append(codeText, prev, codeText.Length - prev);

                codeText = spliced.ToString();
            }

            // Apply React-style hook shorthand: useState( → Hooks.UseState( etc.
            codeText = ApplyHookAliases(codeText);

            foreach (var line in codeText.Split('\n'))
            {
                var trimmed = line.TrimEnd('\r');
                if (!string.IsNullOrEmpty(trimmed))
                    L($"{I3}{trimmed.TrimStart()}");
            }
            L("");
        }

        // ── Hook alias substitution ───────────────────────────────────────────

        private static readonly (string From, string To)[] s_hookAliases =
        {
            ("useState(", "Hooks.UseState("),
            ("useEffect(", "Hooks.UseEffect("),
            ("useRef(", "Hooks.UseRef("),
            ("useCallback(", "Hooks.UseCallback("),
            ("useMemo(", "Hooks.UseMemo("),
            ("useContext(", "Hooks.UseContext("),
            ("useReducer(", "Hooks.UseReducer("),
            ("useSignal(", "Hooks.UseSignal("),
            ("useDeferredValue(", "Hooks.UseDeferredValue("),
            ("useTransition(", "Hooks.UseTransition("),
        };

        private static string ApplyHookAliases(string code)
        {
            // Fast path: bail early if no lowercase hook names are present
            if (code.IndexOf("use", StringComparison.Ordinal) < 0)
                return code;
            foreach (var (from, to) in s_hookAliases)
                code = code.Replace(from, to);
            return code;
        }

        // ── __C helper method ─────────────────────────────────────────────────

        private void EmitHelperMethod()
        {
            // Generates a child-array builder that:
            //   • skips null VirtualNode entries (from @if without @else)
            //   • flattens VirtualNode[] arrays (from @foreach → .Select().ToArray())
            L($"{I2}private static {QVNode}[] __C(params object[] items)");
            L($"{I2}{{");
            L($"{I3}var list = new global::System.Collections.Generic.List<{QVNode}>();");
            L($"{I3}foreach (var __ci in items)");
            L($"{I3}{{");
            L($"{I4}if (__ci is {QVNode} __vn) {{ if (__vn != null) list.Add(__vn); }}");
            L(
                $"{I4}else if (__ci is global::System.Collections.Generic.IEnumerable<{QVNode}> __seq)"
            );
            L($"{I4}    foreach (var __sn in __seq) {{ if (__sn != null) list.Add(__sn); }}");
            L($"{I3}}}");
            L($"{I3}return list.ToArray();");
            L($"{I2}}}");
            L("");
        }

        // ── Node dispatch ─────────────────────────────────────────────────────

        private void EmitNode(AstNode node)
        {
            switch (node)
            {
                case ElementNode e:
                    EmitElementNode(e);
                    break;
                case TextNode t:
                    EmitTextNode(t);
                    break;
                case ExpressionNode x:
                    EmitExpressionNode(x);
                    break;
                case IfNode i:
                    EmitIfNode(i);
                    break;
                case ForeachNode f:
                    EmitForeachNode(f);
                    break;
                case ForNode fn:
                    EmitForNode(fn);
                    break;
                case WhileNode wn:
                    EmitWhileNode(wn);
                    break;
                case SwitchNode s:
                    EmitSwitchNode(s);
                    break;
                case CodeBlockNode:
                    // @code blocks are hoisted before return; skip inline
                    _sb.Append($"({QVNode})null");
                    break;
                case JsxCommentNode:
                    // JSX comments emit nothing to C#
                    break;
                default:
                    _sb.Append($"({QVNode})null /* unhandled: {node.GetType().Name} */");
                    break;
            }
        }

        // ── ElementNode ───────────────────────────────────────────────────────

        private void EmitElementNode(ElementNode el)
        {
            var res = _resolver.Resolve(el.TagName, _directives.Usings, out var diagDesc);

            if (diagDesc != null)
            {
                var loc = Location.Create(_filePath, default, default);
                _diagnostics.Add(Diagnostic.Create(diagDesc, loc, el.TagName));
            }

            string keyExpr = ExtractKey(el.Attributes);

            switch (res.Kind)
            {
                case TagResolutionKind.Fragment:
                    EmitFragment(keyExpr, el.Children);
                    break;

                case TagResolutionKind.BuiltinTyped:
                    EmitBuiltinTyped(res, el.Attributes, keyExpr, el.Children);
                    break;

                case TagResolutionKind.BuiltinDictionary:
                    EmitBuiltinDict(res, el.Attributes, keyExpr, el.Children);
                    break;

                case TagResolutionKind.BuiltinText:
                {
                    string txt = GetAttrValue(el.Attributes, "text") ?? "\"\"";
                    _sb.Append($"V.Text({txt}, key: {keyExpr})");
                    break;
                }

                case TagResolutionKind.FuncComponent:
                    EmitFuncComponent(res, el.Attributes, keyExpr, el.Children);
                    break;

                case TagResolutionKind.Unknown:
                    _sb.Append($"({QVNode})null /* unknown: {el.TagName} */");
                    break;
            }
        }

        private void EmitBuiltinTyped(
            TagResolution res,
            ImmutableArray<AttributeNode> attrs,
            string keyExpr,
            ImmutableArray<AstNode> children
        )
        {
            // UITKX0002 — validate attribute names against known Props properties
            if (res.PropsTypeName != null)
            {
                var knownProps = _resolver.GetPublicPropertyNames(res.PropsTypeName);
                if (knownProps.Count > 0)
                {
                    foreach (var attr in attrs)
                    {
                        if (IsKey(attr.Name))
                            continue;
                        string mapped = ToPropName(attr.Name);
                        if (!knownProps.Contains(mapped))
                        {
                            string? suggestion = FindClosestMatch(mapped, knownProps);
                            string hint =
                                suggestion != null ? $". Did you mean '{suggestion}'?" : "";
                            var loc = Location.Create(_filePath, default, default);
                            _diagnostics.Add(
                                Diagnostic.Create(
                                    UitkxDiagnostics.UnknownAttribute,
                                    loc,
                                    attr.Name,
                                    res.MethodName.ToLowerInvariant(),
                                    hint
                                )
                            );
                        }
                    }
                }
            }

            _sb.Append($"V.{res.MethodName}(new {res.PropsTypeName} {{");

            bool first = true;
            foreach (var attr in attrs)
            {
                if (IsKey(attr.Name))
                    continue;
                if (!first)
                    _sb.Append(", ");
                first = false;
                _sb.Append($" {ToPropName(attr.Name)} = {AttrVal(attr.Value)}");
            }

            _sb.Append(" }, key: ");
            _sb.Append(keyExpr);

            if (res.AcceptsChildren && !children.IsEmpty)
            {
                _sb.Append(", __C(");
                EmitChildArgs(children);
                _sb.Append(")");
            }

            _sb.Append(")");
        }

        private void EmitBuiltinDict(
            TagResolution res,
            ImmutableArray<AttributeNode> attrs,
            string keyExpr,
            ImmutableArray<AstNode> children
        )
        {
            bool hasNonKeyAttrs = false;
            foreach (var a in attrs)
            {
                if (!IsKey(a.Name))
                {
                    hasNonKeyAttrs = true;
                    break;
                }
            }

            if (hasNonKeyAttrs)
            {
                _sb.Append($"V.{res.MethodName}(new Dictionary<string, object>");
                _sb.Append(" {");
                bool first = true;
                foreach (var attr in attrs)
                {
                    if (IsKey(attr.Name))
                        continue;
                    if (!first)
                        _sb.Append(", ");
                    first = false;
                    _sb.Append($" {{ \"{attr.Name}\", {AttrVal(attr.Value)} }}");
                }
                _sb.Append(" }");
            }
            else
            {
                _sb.Append($"V.{res.MethodName}((Dictionary<string, object>)null");
            }

            _sb.Append($", key: {keyExpr}");

            if (!children.IsEmpty)
            {
                _sb.Append(", __C(");
                EmitChildArgs(children);
                _sb.Append(")");
            }

            _sb.Append(")");
        }

        private void EmitFuncComponent(
            TagResolution res,
            ImmutableArray<AttributeNode> attrs,
            string keyExpr,
            ImmutableArray<AstNode> children
        )
        {
            string typeName = res.FuncTypeName!;

            bool hasAttrs = false;
            foreach (var a in attrs)
            {
                if (!IsKey(a.Name))
                {
                    hasAttrs = true;
                    break;
                }
            }

            if (hasAttrs)
            {
                _sb.Append($"V.Func({typeName}.Render, new Dictionary<string, object>");
                _sb.Append(" {");
                bool first = true;
                foreach (var attr in attrs)
                {
                    if (IsKey(attr.Name))
                        continue;
                    if (!first)
                        _sb.Append(", ");
                    first = false;
                    _sb.Append($" {{ \"{attr.Name}\", {AttrVal(attr.Value)} }}");
                }
                _sb.Append(" }");
            }
            else
            {
                _sb.Append($"V.Func({typeName}.Render, (Dictionary<string, object>)null");
            }

            _sb.Append($", key: {keyExpr}");

            if (!children.IsEmpty)
            {
                _sb.Append(", __C(");
                EmitChildArgs(children);
                _sb.Append(")");
            }

            _sb.Append(")");
        }

        private void EmitFragment(string keyExpr, ImmutableArray<AstNode> children)
        {
            if (children.IsEmpty)
            {
                _sb.Append($"V.Fragment(key: {keyExpr})");
            }
            else
            {
                _sb.Append($"V.Fragment(key: {keyExpr}, __C(");
                EmitChildArgs(children);
                _sb.Append("))");
            }
        }

        // ── Control flow ──────────────────────────────────────────────────────

        private void EmitIfNode(IfNode ifn)
        {
            if (ifn.Branches.IsEmpty)
            {
                _sb.Append($"({QVNode})null");
                return;
            }

            // Stable-type strategy:
            // 1. The outer Fragment ensures the TYPE at THIS node's position in the parent
            //    children array is always Fragment (never label, never box).
            // 2. Each branch is ALSO wrapped in a Fragment (via EmitBodyAsFragment) so the
            //    ternary value that sits at position-0 of the outer Fragment is ALWAYS a
            //    Fragment regardless of which branch fires.
            //
            // Without (2), switching from a single-node branch (Label) to a multi-node
            // branch (Fragment) still changes the type at that inner position. The reconciler
            // would delete the old fiber and call CommitPlacement on the new one, which
            // only ever calls AppendChild — placing the new children at the END of the
            // host parent instead of at the correct index.
            _sb.Append("V.Fragment(key: null, __C(");

            // Build ternary chain:
            // (cond1) ? V.Fragment(...body1) : (cond2) ? V.Fragment(...body2) : V.Fragment()
            for (int i = 0; i < ifn.Branches.Length; i++)
            {
                var branch = ifn.Branches[i];

                if (branch.Condition == null)
                {
                    // @else — terminal branch, always a Fragment
                    EmitBodyAsFragment(branch.Body);
                    _sb.Append("))");
                    return;
                }

                _sb.Append($"({branch.Condition}) ? ");
                EmitBodyAsFragment(branch.Body);
                _sb.Append(" : ");

                // Last branch with no @else — emit an empty Fragment (not null) so the
                // type at position-0 of the outer Fragment is always Fragment.
                if (i == ifn.Branches.Length - 1)
                    _sb.Append("V.Fragment(key: null)");
            }
            _sb.Append("))");
        }

        private void EmitForNode(ForNode fn)
        {
            // Emit as IIFE building a list — keeps `i` properly in scope
            _sb.Append($"((System.Func<{QVNode}[]>)(() => {{ ");
            _sb.Append($"var __r = new System.Collections.Generic.List<{QVNode}>(); ");
            _sb.Append($"for ({fn.ForExpression}) {{ __r.Add(");
            EmitBodyExpr(fn.Body);
            _sb.Append("); } return __r.ToArray(); }))()");
        }

        private void EmitWhileNode(WhileNode wn)
        {
            // Emit as IIFE building a list
            _sb.Append($"((System.Func<{QVNode}[]>)(() => {{ ");
            _sb.Append($"var __r = new System.Collections.Generic.List<{QVNode}>(); ");
            _sb.Append($"while ({wn.Condition}) {{ __r.Add(");
            EmitBodyExpr(wn.Body);
            _sb.Append("); } return __r.ToArray(); }))()");
        }

        private void EmitForeachNode(ForeachNode forn)
        {
            // UITKX0009 — warn if direct element children lack a key attribute
            foreach (var bodyNode in forn.Body)
            {
                if (bodyNode is ElementNode elCheck && !HasKey(elCheck.Attributes))
                {
                    var loc = Location.Create(_filePath, default, default);
                    _diagnostics.Add(
                        Diagnostic.Create(
                            UitkxDiagnostics.ForeachMissingKey,
                            loc,
                            string.IsNullOrEmpty(elCheck.TagName) ? "fragment" : elCheck.TagName,
                            elCheck.SourceLine,
                            _displayName
                        )
                    );
                }
            }

            string varName = ExtractVarName(forn.IteratorDeclaration);
            _sb.Append($"({forn.CollectionExpression}).Select(({varName}) => ");

            if (forn.Body.IsEmpty)
                _sb.Append($"({QVNode})null");
            else if (forn.Body.Length == 1)
                EmitNode(forn.Body[0]);
            else
            {
                _sb.Append("V.Fragment(key: null, __C(");
                EmitChildArgs(forn.Body);
                _sb.Append("))");
            }

            _sb.Append(").ToArray()");
        }

        private void EmitSwitchNode(SwitchNode sw)
        {
            // Same stable-type strategy as EmitIfNode:
            // outer Fragment keeps parent position stable; each arm is also always a Fragment
            // so the switch expression result type never changes.
            _sb.Append("V.Fragment(key: null, __C(");
            _sb.Append($"({sw.SwitchExpression}) switch {{");

            foreach (var c in sw.Cases)
            {
                _sb.Append(c.ValueExpression == null ? " _ => " : $" {c.ValueExpression} => ");

                EmitBodyAsFragment(c.Body);
                _sb.Append(",");
            }

            // Ensure there is always a default to keep C# exhaustiveness happy.
            // Use an empty Fragment (not null) so the switch result is always Fragment.
            if (sw.Cases.Length > 0 && sw.Cases[sw.Cases.Length - 1].ValueExpression != null)
                _sb.Append(" _ => V.Fragment(key: null),");

            _sb.Append(" }");
            _sb.Append("))");
        }

        // ── Leaf nodes ────────────────────────────────────────────────────────

        private void EmitTextNode(TextNode txt)
        {
            string s = txt.Content.Trim();
            if (string.IsNullOrEmpty(s))
            {
                _sb.Append($"({QVNode})null /* whitespace text */");
                return;
            }
            _sb.Append($"V.Text(\"{EscStr(s)}\")");
        }

        private void EmitExpressionNode(ExpressionNode ex)
        {
            // @(expr) — user is responsible for returning VirtualNode-compatible value
            _sb.Append($"(({QVNode})({ex.Expression}))");
        }

        // ── Body expression helpers ───────────────────────────────────────────

        /// <summary>
        /// Emits the body of an @if / @switch branch as a V.Fragment, always.
        /// This guarantees that the type of the value produced by every branch of a
        /// ternary / switch expression is always VirtualNodeType.Fragment, so the
        /// reconciler never needs to CommitPlacement after initial mount.
        /// </summary>
        private void EmitBodyAsFragment(ImmutableArray<AstNode> body)
        {
            _sb.Append("V.Fragment(key: null, __C(");
            if (!body.IsEmpty)
                EmitChildArgs(body);
            _sb.Append("))");
        }

        /// <summary>
        /// Emits the body of a branch as a single expression.
        /// Multiple-child bodies are wrapped in V.Fragment.
        /// </summary>
        private void EmitBodyExpr(ImmutableArray<AstNode> body)
        {
            if (body.IsEmpty)
            {
                _sb.Append($"({QVNode})null");
            }
            else if (body.Length == 1)
            {
                EmitNode(body[0]);
            }
            else
            {
                _sb.Append("V.Fragment(key: null, __C(");
                EmitChildArgs(body);
                _sb.Append("))");
            }
        }

        /// <summary>
        /// Emits the argument list for a __C(...) call: one child per line,
        /// each preceded by a #line directive.
        /// </summary>
        private void EmitChildArgs(ImmutableArray<AstNode> children)
        {
            // UITKX0010 — warn on duplicate static string keys among siblings
            CheckDuplicateKeys(children);

            bool first = true;
            for (int i = 0; i < children.Length; i++)
            {
                // JSX comments emit nothing — skip to avoid dangling commas
                if (children[i] is JsxCommentNode)
                    continue;

                if (!first)
                    _sb.Append(",");
                first = false;

                _sb.AppendLine();
                if (children[i].SourceLine > 0)
                {
                    _sb.AppendLine($"#line {children[i].SourceLine} \"{_linePath}\"");
                }
                _sb.Append(I4);
                EmitNode(children[i]);
            }
            if (!first)
            {
                _sb.AppendLine();
                _sb.Append(I4);
            }
        }

        // ── Attribute helpers ─────────────────────────────────────────────────

        private static bool HasKey(ImmutableArray<AttributeNode> attrs)
        {
            foreach (var a in attrs)
                if (IsKey(a.Name))
                    return true;
            return false;
        }

        private void CheckDuplicateKeys(ImmutableArray<AstNode> children)
        {
            var seen = new HashSet<string>(StringComparer.Ordinal);
            foreach (var child in children)
            {
                if (child is not ElementNode el)
                    continue;
                foreach (var attr in el.Attributes)
                {
                    if (!IsKey(attr.Name))
                        continue;
                    if (attr.Value is StringLiteralValue slv)
                    {
                        if (!seen.Add(slv.Value))
                        {
                            var loc = Location.Create(_filePath, default, default);
                            _diagnostics.Add(
                                Diagnostic.Create(
                                    UitkxDiagnostics.DuplicateSiblingKey,
                                    loc,
                                    slv.Value,
                                    _displayName
                                )
                            );
                        }
                    }
                }
            }
        }

        // ── Did-you-mean helpers ─────────────────────────────────────

        private static string? FindClosestMatch(string name, HashSet<string> candidates)
        {
            string? best = null;
            int bestDist = 3; // only suggest if within edit-distance 2
            foreach (var c in candidates)
            {
                int dist = LevenshteinDistance(name, c);
                if (dist < bestDist)
                {
                    bestDist = dist;
                    best = c;
                }
            }
            return best;
        }

        private static int LevenshteinDistance(string a, string b)
        {
            if (a.Length == 0)
                return b.Length;
            if (b.Length == 0)
                return a.Length;
            var d = new int[a.Length + 1, b.Length + 1];
            for (int i = 0; i <= a.Length; i++)
                d[i, 0] = i;
            for (int j = 0; j <= b.Length; j++)
                d[0, j] = j;
            for (int i = 1; i <= a.Length; i++)
            for (int j = 1; j <= b.Length; j++)
                d[i, j] = Math.Min(
                    Math.Min(d[i - 1, j] + 1, d[i, j - 1] + 1),
                    d[i - 1, j - 1]
                        + (
                            char.ToLowerInvariant(a[i - 1]) == char.ToLowerInvariant(b[j - 1])
                                ? 0
                                : 1
                        )
                );
            return d[a.Length, b.Length];
        }

        private static string ExtractKey(ImmutableArray<AttributeNode> attrs)
        {
            foreach (var a in attrs)
                if (IsKey(a.Name))
                    return AttrVal(a.Value);
            return "null";
        }

        private static string? GetAttrValue(ImmutableArray<AttributeNode> attrs, string name)
        {
            foreach (var a in attrs)
                if (string.Equals(a.Name, name, StringComparison.OrdinalIgnoreCase))
                    return AttrVal(a.Value);
            return null;
        }

        private static string AttrVal(AttributeValue v) =>
            v switch
            {
                StringLiteralValue slv => $"\"{EscStr(slv.Value)}\"",
                CSharpExpressionValue cev => cev.Expression,
                BooleanShorthandValue => "true",
                _ => "null",
            };

        private static bool IsKey(string name) =>
            string.Equals(name, "key", StringComparison.OrdinalIgnoreCase);

        private static string ToPropName(string attrName)
        {
            if (string.IsNullOrEmpty(attrName))
                return attrName;
            return char.ToUpperInvariant(attrName[0]) + attrName.Substring(1);
        }

        // ── String / variable helpers ─────────────────────────────────────────

        private static string EscStr(string s) =>
            s.Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\n", "\\n")
                .Replace("\r", "\\r")
                .Replace("\t", "\\t");

        private static string ExtractVarName(string declaration)
        {
            if (string.IsNullOrWhiteSpace(declaration))
                return "__item";
            var parts = declaration
                .Trim()
                .Split(new[] { ' ', '\t' }, StringSplitOptions.RemoveEmptyEntries);
            return parts.Length > 0 ? parts[parts.Length - 1] : "__item";
        }

        private static string NormalizeLinePath(string filePath)
        {
            string fullPath;
            try
            {
                fullPath = Path.GetFullPath(filePath);
            }
            catch
            {
                fullPath = filePath;
            }

            return fullPath.Replace('\\', '/').Replace("\"", "\\\"");
        }

        // ── StringBuilder helpers ─────────────────────────────────────────────

        private void L(string text) => _sb.AppendLine(text);
    }
}
