using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Text;
using Microsoft.CodeAnalysis;
using ReactiveUITK.Language.Parser;

namespace ReactiveUITK.SourceGenerator.Emitter
{
    /// <summary>
    /// Emits the per-file <c>__Exports</c> container for a NEW-MODE (plain-declaration) .uitkx
    /// file (ES-modules campaign, U-02 / plan §4.2):
    /// <list type="bullet">
    ///   <item><description>value → <c>static {Type} {name} = {init};</c> with
    ///   <c>[UitkxHmrSwap]</c> (synthesized as <c>static readonly</c> and routed through
    ///   <see cref="ModuleBodyRewriter"/> so the HMR static swapper refreshes the slot on every
    ///   edit — the exact legacy module <c>static readonly</c> behavior);</description></item>
    ///   <item><description>util → HMR-swappable trampoline via <see cref="ModuleBodyRewriter"/>
    ///   (the legacy module-method shape);</description></item>
    ///   <item><description>hook → the hook-container trampoline + <c>[HookSignature]</c> via
    ///   <see cref="HookEmitter.EmitSingleHook"/>, plus the editor-only refresh companion with
    ///   family keys <c>{ns}.__Exports::{hook}</c> (U-06);</description></item>
    ///   <item><description>aliased/default member imports → typed BRIDGES into this consumer's
    ///   <c>__Exports</c> (U-03: <c>internal static {Ret} b(...) =&gt;
    ///   global::{targetNs}.__Exports.a(...);</c> — never exports of the consumer).</description></item>
    /// </list>
    /// Exported members are <c>public</c>, non-exported <c>internal</c> (G-06; see risk R11 for
    /// the documented same-assembly softness).
    /// </summary>
    public static class ExportsEmitter
    {
        public static string Emit(
            string filePath,
            DirectiveSet directives,
            IList<Diagnostic> diagnostics,
            IReadOnlyDictionary<string, string>? hookKeyMap = null,
            ImmutableArray<PeerExportsInfo>? peerExports = null)
        {
            bool hasMembers = !directives.MemberDeclarations.IsDefaultOrEmpty;
            var bridges = CollectBridges(directives, filePath, peerExports);
            if (!hasMembers && bridges.Count == 0)
                return string.Empty;

            var sb = new StringBuilder(4096);
            string displayName = Path.GetFileName(filePath);
            string linePath = NormalizeLinePath(filePath);

            // ── Header ───────────────────────────────────────────────────────
            sb.AppendLine("// <auto-generated — do not edit — source: " + displayName + " />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("#pragma warning disable CS0105, CS8600, CS8601, CS8602, CS8603, CS8604");
            sb.AppendLine();

            // ── Usings (byte-identical baseline to ModuleEmitter/HookEmitter, incl. the
            //    Unity 6.3 #if alias block pinned by Unity63AliasEmissionTests) ──
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Collections.Concurrent;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using ReactiveUITK;");
            sb.AppendLine("using ReactiveUITK.Core;");
            sb.AppendLine("using ReactiveUITK.Core.Animation;");
            sb.AppendLine("using ReactiveUITK.Router;");
            sb.AppendLine("using ReactiveUITK.Props.Typed;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using static ReactiveUITK.Props.Typed.StyleKeys;");
            sb.AppendLine("using static ReactiveUITK.Props.Typed.CssHelpers;");
            sb.AppendLine("using static ReactiveUITK.AssetHelpers;");
            sb.AppendLine("using UColor = UnityEngine.Color;");
            foreach (var u in directives.Usings)
                sb.AppendLine($"using {u};");
            sb.AppendLine("using Color = UnityEngine.Color;");
            sb.AppendLine("using EasingFunction = UnityEngine.UIElements.EasingFunction;");
            sb.AppendLine("using EasingMode = UnityEngine.UIElements.EasingMode;");
            sb.AppendLine("using BackgroundRepeat = UnityEngine.UIElements.BackgroundRepeat;");
            sb.AppendLine("using BackgroundPosition = UnityEngine.UIElements.BackgroundPosition;");
            sb.AppendLine("using BackgroundSize = UnityEngine.UIElements.BackgroundSize;");
            sb.AppendLine("using TransformOrigin = UnityEngine.UIElements.TransformOrigin;");
            sb.AppendLine("using BackgroundPositionKeyword = UnityEngine.UIElements.BackgroundPositionKeyword;");
            sb.AppendLine("using BackgroundSizeType = UnityEngine.UIElements.BackgroundSizeType;");
            sb.AppendLine("using Repeat = UnityEngine.UIElements.Repeat;");
            sb.AppendLine("using Length = UnityEngine.UIElements.Length;");
            sb.AppendLine("using StyleKeyword = UnityEngine.UIElements.StyleKeyword;");
            sb.AppendLine("using TextAutoSizeMode = UnityEngine.UIElements.TextAutoSizeMode;");
            // Unity 6.3+ types — preprocessor-guarded so pre-6.3 builds compile clean.
            sb.AppendLine("#if UNITY_6000_3_OR_NEWER");
            sb.AppendLine("using FilterFunction = UnityEngine.UIElements.FilterFunction;");
            sb.AppendLine("using Ratio = UnityEngine.UIElements.Ratio;");
            sb.AppendLine("using StyleRatio = UnityEngine.UIElements.StyleRatio;");
            sb.AppendLine("using MaterialDefinition = UnityEngine.UIElements.MaterialDefinition;");
            sb.AppendLine("using StyleMaterialDefinition = UnityEngine.UIElements.StyleMaterialDefinition;");
            sb.AppendLine("#endif");
            sb.AppendLine();

            string ns = !string.IsNullOrEmpty(directives.Namespace)
                ? directives.Namespace!
                : "ReactiveUITK.Generated";

            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine($"    [global::ReactiveUITK.UitkxSource(@\"{filePath.Replace("\"", "\"\"")}\")]");
            sb.AppendLine("    public static partial class __Exports");
            sb.AppendLine("    {");

            if (hasMembers)
                foreach (var m in directives.MemberDeclarations)
                    EmitMember(sb, m, filePath, linePath, diagnostics);

            foreach (var bridge in bridges)
                sb.AppendLine(bridge);

            sb.AppendLine("    }"); // close __Exports

            EmitHookRefreshCompanion(sb, directives, ns, hookKeyMap);

            sb.AppendLine("}"); // close namespace
            return sb.ToString();
        }

        private static void EmitMember(
            StringBuilder sb,
            MemberDeclaration m,
            string filePath,
            string linePath,
            IList<Diagnostic> diagnostics)
        {
            string access = m.IsExported ? "public" : "internal";
            sb.AppendLine();

            switch (m.Kind)
            {
                case DeclKind.Hook:
                {
                    var hook = new HookDeclaration(
                        Name: m.Name,
                        GenericParams: null,
                        Params: m.Params,
                        ReturnType: NormalizeVoid(m.ReturnTypeText),
                        Body: m.IsExpressionBodied ? "return " + m.BodyText + ";" : m.BodyText,
                        DeclarationLine: m.DeclarationLine,
                        BodyStartLine: m.BodyStartLine,
                        BodyStartOffset: m.BodyStartOffset,
                        BodyEndOffset: m.BodyEndOffset);
                    HookEmitter.EmitSingleHook(sb, hook, linePath, diagnostics, access);
                    break;
                }

                case DeclKind.Value:
                {
                    // Synthesize the legacy `static readonly` shape and route it through
                    // ModuleBodyRewriter: StaticReadonlyStripper strips the readonly and stamps
                    // [UitkxHmrSwap], so the HMR static swapper refreshes the value on every
                    // edit-save — exactly what legacy module styles got. Type comes from the
                    // declaration, or from the `new T` initializer (inference sugar, G-04; the
                    // parser already rejected inference without `new T` as UITKX2322).
                    string init = EmitContext.ResolveAssetPaths(m.BodyText, filePath, diagnostics);
                    string typeText = m.ReturnTypeText ?? ExtractInitializerTypeName(init) ?? "object";
                    string synthesized = $"{access} static readonly {typeText} {m.Name} = {init};";
                    AppendViaModuleRewriter(sb, synthesized, m, linePath, diagnostics);
                    break;
                }

                default: // DeclKind.Util
                {
                    string body = EmitContext.ResolveAssetPaths(m.BodyText, filePath, diagnostics);
                    string ret = NormalizeVoid(m.ReturnTypeText) ?? "void";
                    string paramsText = m.ParamsText ?? string.Empty;
                    string synthesized = m.IsExpressionBodied
                        ? $"{access} static {ret} {m.Name}({paramsText}) => {body};"
                        : $"{access} static {ret} {m.Name}({paramsText})\n{{\n{body}\n}}";
                    AppendViaModuleRewriter(sb, synthesized, m, linePath, diagnostics);
                    break;
                }
            }
        }

        /// <summary>Routes one synthesized member through <see cref="ModuleBodyRewriter"/> (the
        /// legacy module-member HMR machinery: method trampolines + static-readonly strip). Line
        /// mapping anchors at the member's own declaration line — head columns shift vs. source
        /// (the `export` keyword became a C# modifier) but lines hold, matching the accuracy the
        /// legacy module path provides.</summary>
        private static void AppendViaModuleRewriter(
            StringBuilder sb,
            string synthesizedMember,
            MemberDeclaration m,
            string linePath,
            IList<Diagnostic> diagnostics)
        {
            var rewrite = ModuleBodyRewriter.Rewrite(
                synthesizedMember, "__Exports", m.DeclarationLine, linePath);
            if (rewrite.ParseFailed)
            {
                diagnostics.Add(Diagnostic.Create(
                    UitkxDiagnostics.ModuleBodyParseFailed,
                    Location.None,
                    m.Name,
                    rewrite.FailureReason ?? "unknown parse failure"));
                sb.AppendLine($"#line {m.DeclarationLine} \"{linePath}\"");
                sb.AppendLine("        " + synthesizedMember);
                sb.AppendLine("#line hidden");
                return;
            }
            sb.Append(rewrite.TransformedBody);
        }

        /// <summary>Extracts <c>T</c> from a <c>new T {...}</c> / <c>new T(...)</c> initializer
        /// (G-04 inference sugar). Null when the initializer is not new-shaped — the parser
        /// already reported UITKX2322 in that case; the <c>object</c> fallback merely keeps the
        /// emitted file syntactically parseable next to the #error.</summary>
        internal static string? ExtractInitializerTypeName(string initText)
        {
            string t = initText.TrimStart();
            if (!t.StartsWith("new", StringComparison.Ordinal))
                return null;
            int p = 3;
            while (p < t.Length && (t[p] == ' ' || t[p] == '\t')) p++;
            int start = p;
            int depth = 0;
            while (p < t.Length)
            {
                char c = t[p];
                if (c == '<') { depth++; p++; continue; }
                if (c == '>') { depth--; p++; continue; }
                if (depth == 0 && (c == '{' || c == '(' || c == ' ' || c == '\t' || c == '\r' || c == '\n'))
                    break;
                if (depth == 0 && c == '[')
                {
                    // Array type: consume the [] pairs as part of the type.
                    while (p < t.Length && t[p] != ']') p++;
                    if (p < t.Length) p++;
                    continue;
                }
                p++;
            }
            string name = t.Substring(start, p - start).Trim();
            return name.Length > 0 ? name : null;
        }

        private static string? NormalizeVoid(string? returnTypeText)
            => string.Equals(returnTypeText?.Trim(), "void", StringComparison.Ordinal)
                ? null
                : returnTypeText;

        // ── Bridges (U-03: rename-on-import / default member imports) ────────

        private static List<string> CollectBridges(
            DirectiveSet directives,
            string filePath,
            ImmutableArray<PeerExportsInfo>? peerExports)
        {
            var result = new List<string>();
            if (directives.Imports.IsDefaultOrEmpty || peerExports == null || peerExports.Value.IsDefaultOrEmpty)
                return result;

            static string Norm(string p) => p.Replace('\\', '/').TrimEnd('/');
            var byPath = new Dictionary<string, PeerExportsInfo>(StringComparer.OrdinalIgnoreCase);
            foreach (var pe in peerExports.Value)
                byPath[Norm(pe.SourceFilePath)] = pe;

            string importerDir = Norm(Path.GetDirectoryName(filePath) ?? string.Empty);
            string rootDir = ReactiveUITK.Language.EffectiveNamespace.UiSourceRootDir(filePath) ?? importerDir;

            foreach (var imp in directives.Imports)
            {
                bool anyAlias = !imp.Aliases.IsDefaultOrEmpty;
                if (!anyAlias && !imp.IsDefault)
                    continue;

                string? target = ReactiveUITK.Language.ImportResolver.MapSpecifierToPath(
                    importerDir, imp.Specifier, rootDir, out _);
                if (target == null || !byPath.TryGetValue(Norm(target), out var pe))
                    continue;

                if (imp.IsDefault && imp.DefaultAlias != null && pe.DefaultExportName != null)
                {
                    // Component defaults lower to a using-alias (ImportScopeFacts), not a bridge.
                    if (!pe.ExportedComponentNames.Contains(pe.DefaultExportName))
                    {
                        var target_ = FindMember(pe, pe.DefaultExportName);
                        if (target_ != null)
                            AppendBridge(result, imp.DefaultAlias, target_, pe.Namespace);
                    }
                    continue;
                }

                if (!anyAlias)
                    continue;
                for (int k = 0; k < imp.Names.Length && k < imp.Aliases.Length; k++)
                {
                    string? alias = imp.Aliases[k];
                    if (alias == null)
                        continue;
                    // Aliased COMPONENT imports lower to a using-alias; only members bridge.
                    var member = FindMember(pe, imp.Names[k]);
                    if (member != null)
                        AppendBridge(result, alias, member, pe.Namespace);
                }
            }
            return result;
        }

        private static MemberDeclaration? FindMember(PeerExportsInfo pe, string name)
        {
            if (pe.Members.IsDefaultOrEmpty)
                return null;
            foreach (var m in pe.Members)
                if (m.IsExported && m.Name == name)
                    return m;
            return null;
        }

        private static void AppendBridge(
            List<string> result, string alias, MemberDeclaration target, string targetNs)
        {
            if (target.Kind == DeclKind.Value)
            {
                string type = target.ReturnTypeText
                    ?? ExtractInitializerTypeName(target.BodyText) ?? "object";
                result.Add(
                    $"        internal static {type} {alias} => global::{targetNs}.__Exports.{target.Name};");
                return;
            }

            // Method-shaped (util/hook): re-state the signature and forward. R5 constraint:
            // ref/out/in/params modifiers are forwarded explicitly via the parsed param types
            // (TryReadTypeName keeps them as part of the type text when written).
            string ret = target.ReturnTypeText ?? "void";
            string paramList = BuildParamList(target.Params);
            string argNames = BuildArgNames(target.Params);
            result.Add(
                $"        internal static {ret} {alias}({paramList}) => global::{targetNs}.__Exports.{target.Name}({argNames});");
        }

        private static string BuildParamList(ImmutableArray<FunctionParam> ps)
        {
            if (ps.IsDefaultOrEmpty) return string.Empty;
            var sb = new StringBuilder();
            for (int i = 0; i < ps.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append(ps[i].Type).Append(' ').Append(ps[i].Name);
                if (ps[i].DefaultValue != null)
                    sb.Append(" = ").Append(ps[i].DefaultValue);
            }
            return sb.ToString();
        }

        private static string BuildArgNames(ImmutableArray<FunctionParam> ps)
        {
            if (ps.IsDefaultOrEmpty) return string.Empty;
            var sb = new StringBuilder();
            for (int i = 0; i < ps.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append(ps[i].Name);
            }
            return sb.ToString();
        }

        // ── Hook refresh companion (family keys {ns}.__Exports::{hook}, U-06) ──

        private static void EmitHookRefreshCompanion(
            StringBuilder sb,
            DirectiveSet directives,
            string ns,
            IReadOnlyDictionary<string, string>? hookKeyMap)
        {
            bool anyHook = false;
            if (!directives.MemberDeclarations.IsDefaultOrEmpty)
                foreach (var m in directives.MemberDeclarations)
                    if (m.Kind == DeclKind.Hook) { anyHook = true; break; }
            if (!anyHook)
                return;

            sb.AppendLine();
            sb.AppendLine("#if UNITY_EDITOR");
            sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
            sb.AppendLine("    [global::System.Runtime.CompilerServices.CompilerGenerated]");
            sb.AppendLine("    internal static class __Exports__UitkxHookRefresh");
            sb.AppendLine("    {");
            sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
            sb.AppendLine("        internal static void __Register()");
            sb.AppendLine("        {");
            foreach (var m in directives.MemberDeclarations)
            {
                if (m.Kind != DeclKind.Hook)
                    continue;
                string body = m.IsExpressionBodied ? "return " + m.BodyText + ";" : m.BodyText;
                string sig = EmitContext.ExtractHookSignature(body) ?? string.Empty;
                string[] hookCustomKeys = EmitContext.ExtractCustomHookFamilyKeys(body);
                string familyKey = $"{ns}.__Exports::{m.Name}";
                string keysLit = EmitContext.RenderCustomHookFamilyKeysLiteral(
                    HookEmitter.QualifyKeys(hookCustomKeys, hookKeyMap));
                sb.AppendLine(
                    "            global::ReactiveUITK.Refresh.RefreshRuntime.RegisterHook(" +
                    $"\"{EscapeStringLiteral(familyKey)}\", " +
                    $"\"{EscapeStringLiteral(sig)}\", " +
                    $"{keysLit});");
            }
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("#endif // UNITY_EDITOR");
        }

        private static string EscapeStringLiteral(string s)
        {
            if (string.IsNullOrEmpty(s)) return string.Empty;
            return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        private static string NormalizeLinePath(string filePath)
        {
            return (filePath ?? string.Empty).Replace('\\', '/');
        }
    }
}
