using System;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System.Collections.Immutable;
using System.IO;
using System.Text;
using Microsoft.CodeAnalysis;
using ReactiveUITK.Language.Parser;

namespace ReactiveUITK.SourceGenerator.Emitter
{
    /// <summary>
    /// Emits C# source for <c>hook</c> declarations parsed from .uitkx files.
    ///
    /// Each hook generates:
    /// <list type="bullet">
    ///   <item><description>Non-generic: <c>Func&lt;...&gt;</c> delegate field for HMR + trampoline + body method</description></item>
    ///   <item><description>Generic: <c>MethodInfo</c> field + <c>ConcurrentDictionary</c> cache for HMR + trampoline + body method</description></item>
    /// </list>
    ///
    /// All HMR indirection is wrapped in <c>#if UNITY_EDITOR</c> guards — zero overhead in builds.
    /// </summary>
    public static class HookEmitter
    {
        public static string Emit(
            string filePath,
            DirectiveSet directives,
            IList<Diagnostic> diagnostics
        )
        {
            if (directives.HookDeclarations.IsDefaultOrEmpty)
                return string.Empty;

            var sb = new StringBuilder(4096);
            string displayName = Path.GetFileName(filePath);
            string linePath = NormalizeLinePath(filePath);

            // ── Header ───────────────────────────────────────────────────────
            sb.AppendLine("// <auto-generated — do not edit — source: " + displayName + " />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("#pragma warning disable CS0105, CS8600, CS8601, CS8602, CS8603, CS8604");
            sb.AppendLine();

            // ── Usings ───────────────────────────────────────────────────────
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Collections.Concurrent;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using ReactiveUITK;");
            sb.AppendLine("using ReactiveUITK.Core;");
            sb.AppendLine("using ReactiveUITK.Core.Animation;");
            sb.AppendLine("using ReactiveUITK.Props.Typed;");
            sb.AppendLine("using static ReactiveUITK.Props.Typed.StyleKeys;");
            sb.AppendLine("using static ReactiveUITK.Props.Typed.CssHelpers;");
            sb.AppendLine("using static ReactiveUITK.AssetHelpers;");
            sb.AppendLine("using UColor = UnityEngine.Color;");
            foreach (var u in directives.Usings)
                sb.AppendLine($"using {u};");
            sb.AppendLine("using Color = UnityEngine.Color;");
            sb.AppendLine("using EasingFunction = UnityEngine.UIElements.EasingFunction;");
            sb.AppendLine("using EasingMode = UnityEngine.UIElements.EasingMode;");
            sb.AppendLine("using BackgroundRepeat = UnityEngine.UIElements.BackgroundRepeat;");
            sb.AppendLine("using BackgroundPosition = UnityEngine.UIElements.BackgroundPosition;");
            sb.AppendLine("using BackgroundSize = UnityEngine.UIElements.BackgroundSize;");
            sb.AppendLine("using TransformOrigin = UnityEngine.UIElements.TransformOrigin;");
            sb.AppendLine("using BackgroundPositionKeyword = UnityEngine.UIElements.BackgroundPositionKeyword;");
            sb.AppendLine("using BackgroundSizeType = UnityEngine.UIElements.BackgroundSizeType;");
            sb.AppendLine("using Repeat = UnityEngine.UIElements.Repeat;");
            sb.AppendLine("using Length = UnityEngine.UIElements.Length;");
            sb.AppendLine("using StyleKeyword = UnityEngine.UIElements.StyleKeyword;");
            sb.AppendLine("using TextAutoSizeMode = UnityEngine.UIElements.TextAutoSizeMode;");
            sb.AppendLine();

            // ── Namespace ────────────────────────────────────────────────────
            string ns = !string.IsNullOrEmpty(directives.Namespace)
                ? directives.Namespace!
                : "ReactiveUITK.Generated";

            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");

            // Derive container class name from filename
            string containerClass = DeriveContainerClassName(filePath);
            sb.AppendLine($"    [global::ReactiveUITK.UitkxSource(@\"{filePath.Replace("\"", "\"\"")}\")]");
            sb.AppendLine($"    public static partial class {containerClass}");
            sb.AppendLine("    {");

            foreach (var hook in directives.HookDeclarations)
            {
                EmitSingleHook(sb, hook, linePath);
            }

            sb.AppendLine("    }"); // close class
            sb.AppendLine("}"); // close namespace

            return sb.ToString();
        }

        private static void EmitSingleHook(StringBuilder sb, HookDeclaration hook, string linePath)
        {
            bool isGeneric = !string.IsNullOrEmpty(hook.GenericParams);
            bool isVoid = string.IsNullOrEmpty(hook.ReturnType);
            string paramList = BuildParamList(hook.Params);
            string paramNames = BuildParamNames(hook.Params);
            string genericSuffix = hook.GenericParams ?? string.Empty;
            string bodyMethodName = $"__{hook.Name}_body";
            string hmrFieldName = $"__hmr_{hook.Name}";
            string returnType = isVoid ? "void" : hook.ReturnType!;

            // Apply hook aliases to body
            string transformedBody = EmitContext.ApplyHookAliases(hook.Body);

            // Extract hook signature for [HookSignature] attribute
            string hookSig = EmitContext.ExtractHookSignature(hook.Body);

            sb.AppendLine();

            if (isGeneric)
            {
                // ── Generic hook: MethodInfo + ConcurrentDictionary cache ─────
                sb.AppendLine("#if UNITY_EDITOR");
                sb.AppendLine($"        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
                sb.AppendLine($"        internal static global::System.Reflection.MethodInfo {hmrFieldName} = null;");
                sb.AppendLine($"        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
                sb.AppendLine($"        internal static readonly global::System.Collections.Concurrent.ConcurrentDictionary<global::System.Type, global::System.Delegate> {hmrFieldName}_cache = new();");
                sb.AppendLine("#endif");
                sb.AppendLine();

                // Trampoline
                if (!string.IsNullOrEmpty(hookSig))
                    sb.AppendLine($"        [global::ReactiveUITK.HookSignature(\"{hookSig}\")]");
                sb.AppendLine($"        public static {returnType} {hook.Name}{genericSuffix}({paramList})");
                sb.AppendLine("        {");
                sb.AppendLine("#if UNITY_EDITOR");
                sb.AppendLine($"            if (global::ReactiveUITK.Core.HmrState.IsActive && {hmrFieldName} != null)");
                sb.AppendLine("            {");

                // Build Func/Action type for the delegate
                string delegateType = BuildDelegateType(hook.Params, hook.ReturnType);
                sb.AppendLine($"                var __del = ({delegateType}){hmrFieldName}_cache");
                sb.AppendLine($"                    .GetOrAdd(typeof({BuildTypeofArgs(hook.GenericParams)}), __t =>");
                sb.AppendLine("                    {");
                sb.AppendLine($"                        var __closed = {hmrFieldName}.MakeGenericMethod(__t);");
                sb.AppendLine($"                        return global::System.Delegate.CreateDelegate(typeof({delegateType}), __closed);");
                sb.AppendLine("                    });");
                if (isVoid)
                    sb.AppendLine($"                __del({paramNames}); return;");
                else
                    sb.AppendLine($"                return __del({paramNames});");
                sb.AppendLine("            }");
                sb.AppendLine("#endif");
                if (isVoid)
                    sb.AppendLine($"            {bodyMethodName}{genericSuffix}({paramNames});");
                else
                    sb.AppendLine($"            return {bodyMethodName}{genericSuffix}({paramNames});");
                sb.AppendLine("        }");
            }
            else
            {
                // ── Non-generic hook: Func/Action delegate field ──────────────
                string delegateType = BuildDelegateType(hook.Params, hook.ReturnType);

                sb.AppendLine("#if UNITY_EDITOR");
                sb.AppendLine($"        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
                sb.AppendLine($"        internal static {delegateType} {hmrFieldName} = {bodyMethodName};");
                sb.AppendLine("#endif");
                sb.AppendLine();

                // Trampoline
                if (!string.IsNullOrEmpty(hookSig))
                    sb.AppendLine($"        [global::ReactiveUITK.HookSignature(\"{hookSig}\")]");
                sb.AppendLine($"        public static {returnType} {hook.Name}({paramList})");
                sb.AppendLine("        {");
                sb.AppendLine("#if UNITY_EDITOR");
                sb.AppendLine($"            if (global::ReactiveUITK.Core.HmrState.IsActive)");
                if (isVoid)
                {
                    sb.AppendLine($"            {{ {hmrFieldName}({paramNames}); return; }}");
                }
                else
                {
                    sb.AppendLine($"                return {hmrFieldName}({paramNames});");
                }
                sb.AppendLine("#endif");
                if (isVoid)
                    sb.AppendLine($"            {bodyMethodName}({paramNames});");
                else
                    sb.AppendLine($"            return {bodyMethodName}({paramNames});");
                sb.AppendLine("        }");
            }

            // ── Body method ──────────────────────────────────────────────────
            sb.AppendLine();
            sb.AppendLine($"        private static {returnType} {bodyMethodName}{genericSuffix}({paramList})");
            sb.AppendLine("        {");
            sb.AppendLine($"#line {hook.BodyStartLine} \"{linePath}\"");
            sb.AppendLine($"            {transformedBody}");
            sb.AppendLine("#line hidden");
            sb.AppendLine("        }");
        }

        // ── Helpers ──────────────────────────────────────────────────────────

        /// <summary>
        /// Builds a comma-separated parameter list for method signatures:
        /// <c>int initial = 0, string label = ""</c>
        /// </summary>
        private static string BuildParamList(ImmutableArray<FunctionParam> hookParams)
        {
            if (hookParams.IsDefaultOrEmpty)
                return string.Empty;

            var sb = new StringBuilder();
            for (int i = 0; i < hookParams.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                var p = hookParams[i];
                sb.Append(p.Type).Append(' ').Append(p.Name);
                if (p.DefaultValue != null)
                    sb.Append(" = ").Append(p.DefaultValue);
            }
            return sb.ToString();
        }

        /// <summary>
        /// Builds a comma-separated list of parameter names for call forwarding:
        /// <c>initial, label</c>
        /// </summary>
        private static string BuildParamNames(ImmutableArray<FunctionParam> hookParams)
        {
            if (hookParams.IsDefaultOrEmpty)
                return string.Empty;

            var sb = new StringBuilder();
            for (int i = 0; i < hookParams.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append(hookParams[i].Name);
            }
            return sb.ToString();
        }

        /// <summary>
        /// Builds the delegate type for a hook:
        /// <c>global::System.Func&lt;int, (int, Action)&gt;</c> for non-void,
        /// <c>global::System.Action&lt;int&gt;</c> for void.
        /// </summary>
        private static string BuildDelegateType(ImmutableArray<FunctionParam> hookParams, string? returnType)
        {
            bool isVoid = string.IsNullOrEmpty(returnType);
            var sb = new StringBuilder();

            if (isVoid)
            {
                if (hookParams.IsDefaultOrEmpty)
                {
                    sb.Append("global::System.Action");
                }
                else
                {
                    sb.Append("global::System.Action<");
                    for (int i = 0; i < hookParams.Length; i++)
                    {
                        if (i > 0) sb.Append(", ");
                        sb.Append(hookParams[i].Type);
                    }
                    sb.Append('>');
                }
            }
            else
            {
                sb.Append("global::System.Func<");
                if (!hookParams.IsDefaultOrEmpty)
                {
                    for (int i = 0; i < hookParams.Length; i++)
                    {
                        sb.Append(hookParams[i].Type).Append(", ");
                    }
                }
                sb.Append(returnType);
                sb.Append('>');
            }

            return sb.ToString();
        }

        /// <summary>
        /// Extracts type argument names from a generic params string for typeof():
        /// <c>&lt;T&gt;</c> → <c>T</c>, <c>&lt;TKey, TValue&gt;</c> → <c>TKey, TValue</c>.
        /// For single type param returns the name; for multiple wraps in tuple-style typeof.
        /// </summary>
        private static string BuildTypeofArgs(string? genericParams)
        {
            if (string.IsNullOrEmpty(genericParams))
                return "object";

            // Strip < and >
            string inner = genericParams!.TrimStart('<').TrimEnd('>').Trim();
            return inner;
        }

        /// <summary>
        /// Derives the container class name from the .uitkx filename:
        /// <c>useCounter.uitkx</c> → <c>UseCounterHooks</c>,
        /// <c>Counter.hooks.uitkx</c> → <c>CounterHooks</c>,
        /// <c>Counter.anything.uitkx</c> → <c>CounterHooks</c>.
        /// </summary>
        internal static string DeriveContainerClassName(string filePath)
        {
            string fileName = Path.GetFileNameWithoutExtension(filePath);
            // Strip any dot-suffix (e.g. .hooks, .style, .whatever) — the
            // file type is determined by content, not filename convention.
            int dot = fileName.IndexOf('.');
            if (dot > 0)
                fileName = fileName.Substring(0, dot);

            // PascalCase the first letter
            if (fileName.Length > 0 && char.IsLower(fileName[0]))
                fileName = char.ToUpper(fileName[0]) + fileName.Substring(1);

            return fileName + "Hooks";
        }

        private static string NormalizeLinePath(string filePath)
        {
            return (filePath ?? string.Empty).Replace('\\', '/');
        }
    }
}
