using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Text;
using Microsoft.CodeAnalysis;
using ReactiveUITK.Language.Parser;

namespace ReactiveUITK.SourceGenerator.Emitter
{
    /// <summary>
    /// Emits C# source for <c>module</c> declarations parsed from .uitkx files.
    ///
    /// Each module generates a <c>partial class</c>:
    /// <list type="bullet">
    ///   <item><description>If the module name matches a component, it extends that component's partial class.</description></item>
    ///   <item><description>Otherwise, it creates a standalone <c>public partial class</c>.</description></item>
    /// </list>
    /// </summary>
    public static class ModuleEmitter
    {
        public static string Emit(
            string filePath,
            DirectiveSet directives,
            IList<Diagnostic> diagnostics,
            ImmutableArray<PeerComponentInfo>? peerComponents = null
        )
        {
            if (directives.ModuleDeclarations.IsDefaultOrEmpty)
                return string.Empty;

            var sb = new StringBuilder(4096);
            string displayName = Path.GetFileName(filePath);
            string linePath = NormalizeLinePath(filePath);

            // ── Header ───────────────────────────────────────────────────────
            sb.AppendLine("// <auto-generated — do not edit — source: " + displayName + " />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("#pragma warning disable CS0105, CS8600, CS8601, CS8602, CS8603, CS8604");
            sb.AppendLine();

            // ── Usings ───────────────────────────────────────────────────────
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using ReactiveUITK;");
            sb.AppendLine("using ReactiveUITK.Core;");
            sb.AppendLine("using ReactiveUITK.Core.Animation;");
            sb.AppendLine("using ReactiveUITK.Props.Typed;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using static ReactiveUITK.Props.Typed.StyleKeys;");
            sb.AppendLine("using static ReactiveUITK.Props.Typed.CssHelpers;");
            sb.AppendLine("using static ReactiveUITK.AssetHelpers;");
            sb.AppendLine("using UColor = UnityEngine.Color;");
            foreach (var u in directives.Usings)
                sb.AppendLine($"using {u};");
            sb.AppendLine("using Color = UnityEngine.Color;");
            sb.AppendLine("using EasingFunction = UnityEngine.UIElements.EasingFunction;");
            sb.AppendLine("using EasingMode = UnityEngine.UIElements.EasingMode;");
            sb.AppendLine("using BackgroundRepeat = UnityEngine.UIElements.BackgroundRepeat;");
            sb.AppendLine("using BackgroundPosition = UnityEngine.UIElements.BackgroundPosition;");
            sb.AppendLine("using BackgroundSize = UnityEngine.UIElements.BackgroundSize;");
            sb.AppendLine("using TransformOrigin = UnityEngine.UIElements.TransformOrigin;");
            sb.AppendLine("using BackgroundPositionKeyword = UnityEngine.UIElements.BackgroundPositionKeyword;");
            sb.AppendLine("using BackgroundSizeType = UnityEngine.UIElements.BackgroundSizeType;");
            sb.AppendLine("using Repeat = UnityEngine.UIElements.Repeat;");
            sb.AppendLine("using Length = UnityEngine.UIElements.Length;");
            sb.AppendLine("using StyleKeyword = UnityEngine.UIElements.StyleKeyword;");
            sb.AppendLine("using TextAutoSizeMode = UnityEngine.UIElements.TextAutoSizeMode;");
            // Unity 6.3+ types — preprocessor-guarded so pre-6.3 builds compile clean.
            sb.AppendLine("#if UNITY_6000_3_OR_NEWER");
            sb.AppendLine("using FilterFunction = UnityEngine.UIElements.FilterFunction;");
            sb.AppendLine("using Ratio = UnityEngine.UIElements.Ratio;");
            sb.AppendLine("using StyleRatio = UnityEngine.UIElements.StyleRatio;");
            sb.AppendLine("using MaterialDefinition = UnityEngine.UIElements.MaterialDefinition;");
            sb.AppendLine("using StyleMaterialDefinition = UnityEngine.UIElements.StyleMaterialDefinition;");
            sb.AppendLine("#endif");
            sb.AppendLine();

            // ── Namespace ────────────────────────────────────────────────────
            string ns = !string.IsNullOrEmpty(directives.Namespace)
                ? directives.Namespace!
                : "ReactiveUITK.Generated";

            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");

            foreach (var module in directives.ModuleDeclarations)
            {
                // Resolve relative Asset<T>("./x") / Ast<T>("../x") paths to absolute
                // Unity registry keys. Without this, runtime UitkxAssetRegistry.Get<T>
                // misses because the registry indexes by resolved path while the
                // emitted literal would still be the original relative string.
                string transformedBody = EmitContext.ResolveAssetPaths(
                    module.Body, filePath, diagnostics);

                // Roslyn-rewrite each top-level static method into the
                // HMR-swappable trampoline + delegate field + body method
                // pattern. Non-method members (consts, fields, nested types)
                // emit verbatim. On parse failure we fall back to verbatim
                // emit and surface UITKX0150 (Info severity — non-blocking).
                var rewriteResult = ModuleBodyRewriter.Rewrite(
                    transformedBody,
                    module.Name,
                    module.BodyStartLine,
                    linePath);

                if (rewriteResult.ParseFailed)
                {
                    diagnostics.Add(Diagnostic.Create(
                        UitkxDiagnostics.ModuleBodyParseFailed,
                        Location.None,
                        module.Name,
                        rewriteResult.FailureReason ?? "unknown parse failure"));
                }
                // Don't emit [UitkxSource] — the module may extend a component
                // class that already has it, and the attribute isn't allowed
                // to appear twice on the same type.
                //
                // Accessibility (§6): a module that MERGES with a same-named component partial emits
                // NO modifier (that component's partial is the authority — a mismatched modifier would
                // be CS0262); otherwise export → public, else internal. If the merging parts disagree
                // on exportedness → UITKX2311. Standalone exported modules stay `public` (byte-identical
                // to before), so the migrated Samples are unaffected.
                bool mergesWithComponent = false;
                bool componentIsExported = false;
                if (!directives.ComponentDeclarations.IsDefaultOrEmpty)
                    foreach (var comp in directives.ComponentDeclarations)
                        if (comp.Name == module.Name)
                        {
                            mergesWithComponent = true;
                            componentIsExported = comp.IsExported;
                            break;
                        }
                // Cross-file merge (the common companion pattern: Foo.uitkx `component Foo`
                // + Foo.style.uitkx `module Foo`). A same-named component in ANY file that
                // resolves to the same effective namespace becomes the same partial type, so
                // the module part must defer its access modifier to the component — otherwise a
                // non-exported component (internal) + an exported module (public) are two
                // partials of one type with conflicting EXPLICIT modifiers → CS0262, which the
                // same-file-only check never caught.
                if (!mergesWithComponent && peerComponents != null)
                    foreach (var pc in peerComponents.Value)
                        if (pc.Name == module.Name
                            && string.Equals(pc.Namespace, ns, StringComparison.Ordinal))
                        {
                            mergesWithComponent = true;
                            componentIsExported = pc.IsExported;
                            break;
                        }

                if (mergesWithComponent && componentIsExported != module.IsExported)
                {
                    // Warning, not Error: the module now emits no modifier and DEFERS to the
                    // component's accessibility (so there is no CS0262 to break the build) — the
                    // module's own `export`/non-export was just ignored. Advise the user to align
                    // them. (Surfaced via #warning by the pipeline — Location.None alone is dropped.)
                    diagnostics.Add(Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "UITKX2311", "Export accessibility mismatch",
                            $"Export mismatch merging into '{module.Name}': the component's accessibility is used; align the module's export.",
                            "ReactiveUITK.Imports", DiagnosticSeverity.Warning, true),
                        Location.None));
                }

                // Accessibility gated behind StrictImports (additive-then-flip): flag OFF → legacy
                // `public ` always; flag ON → no-modifier when merging with a same-named component
                // partial (that part is the authority), else export → public, else internal.
                string moduleAccess =
                    !ReactiveUITK.Language.UitkxFeatureFlags.StrictImports
                        ? "public "
                        : mergesWithComponent
                            ? string.Empty
                            : (module.IsExported ? "public " : "internal ");
                sb.AppendLine($"    {moduleAccess}partial class {module.Name}");
                sb.AppendLine("    {");
                if (rewriteResult.ParseFailed)
                {
                    // Verbatim fallback path — preserve historical emit shape.
                    sb.AppendLine($"#line {module.BodyStartLine} \"{linePath}\"");
                    sb.AppendLine($"        {rewriteResult.OriginalBody}");
                    sb.AppendLine("#line hidden");
                }
                else
                {
                    // Rewritten body already contains its own #line directives
                    // for each emitted member.
                    sb.Append(rewriteResult.TransformedBody);
                }
                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}"); // close namespace

            return sb.ToString();
        }

        private static string NormalizeLinePath(string filePath)
        {
            return (filePath ?? string.Empty).Replace('\\', '/');
        }
    }
}
