using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Text;
using Microsoft.CodeAnalysis;
using ReactiveUITK.Language.Parser;

namespace ReactiveUITK.SourceGenerator.Emitter
{
    /// <summary>
    /// Emits C# source for <c>module</c> declarations parsed from .uitkx files.
    ///
    /// Each module generates a <c>partial class</c>:
    /// <list type="bullet">
    ///   <item><description>If the module name matches a component, it extends that component's partial class.</description></item>
    ///   <item><description>Otherwise, it creates a standalone <c>public partial class</c>.</description></item>
    /// </list>
    /// </summary>
    public static class ModuleEmitter
    {
        public static string Emit(
            string filePath,
            DirectiveSet directives,
            IList<Diagnostic> diagnostics
        )
        {
            if (directives.ModuleDeclarations.IsDefaultOrEmpty)
                return string.Empty;

            var sb = new StringBuilder(4096);
            string displayName = Path.GetFileName(filePath);
            string linePath = NormalizeLinePath(filePath);

            // ── Header ───────────────────────────────────────────────────────
            sb.AppendLine("// <auto-generated — do not edit — source: " + displayName + " />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("#pragma warning disable CS0105, CS8600, CS8601, CS8602, CS8603, CS8604");
            sb.AppendLine();

            // ── Usings ───────────────────────────────────────────────────────
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using ReactiveUITK;");
            sb.AppendLine("using ReactiveUITK.Core;");
            sb.AppendLine("using ReactiveUITK.Core.Animation;");
            sb.AppendLine("using ReactiveUITK.Props.Typed;");
            sb.AppendLine("using static ReactiveUITK.Props.Typed.StyleKeys;");
            sb.AppendLine("using static ReactiveUITK.Props.Typed.CssHelpers;");
            sb.AppendLine("using static ReactiveUITK.AssetHelpers;");
            sb.AppendLine("using UColor = UnityEngine.Color;");
            foreach (var u in directives.Usings)
                sb.AppendLine($"using {u};");
            sb.AppendLine("using Color = UnityEngine.Color;");
            sb.AppendLine("using EasingFunction = UnityEngine.UIElements.EasingFunction;");
            sb.AppendLine("using EasingMode = UnityEngine.UIElements.EasingMode;");
            sb.AppendLine("using BackgroundRepeat = UnityEngine.UIElements.BackgroundRepeat;");
            sb.AppendLine("using BackgroundPosition = UnityEngine.UIElements.BackgroundPosition;");
            sb.AppendLine("using BackgroundSize = UnityEngine.UIElements.BackgroundSize;");
            sb.AppendLine("using TransformOrigin = UnityEngine.UIElements.TransformOrigin;");
            sb.AppendLine("using BackgroundPositionKeyword = UnityEngine.UIElements.BackgroundPositionKeyword;");
            sb.AppendLine("using BackgroundSizeType = UnityEngine.UIElements.BackgroundSizeType;");
            sb.AppendLine("using Repeat = UnityEngine.UIElements.Repeat;");
            sb.AppendLine("using Length = UnityEngine.UIElements.Length;");
            sb.AppendLine("using StyleKeyword = UnityEngine.UIElements.StyleKeyword;");
            sb.AppendLine("using TextAutoSizeMode = UnityEngine.UIElements.TextAutoSizeMode;");
            sb.AppendLine();

            // ── Namespace ────────────────────────────────────────────────────
            string ns = !string.IsNullOrEmpty(directives.Namespace)
                ? directives.Namespace!
                : "ReactiveUITK.Generated";

            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");

            foreach (var module in directives.ModuleDeclarations)
            {
                // Resolve relative Asset<T>("./x") / Ast<T>("../x") paths to absolute
                // Unity registry keys. Without this, runtime UitkxAssetRegistry.Get<T>
                // misses because the registry indexes by resolved path while the
                // emitted literal would still be the original relative string.
                string transformedBody = EmitContext.ResolveAssetPaths(
                    module.Body, filePath, diagnostics);

                // Don't emit [UitkxSource] — the module may extend a component
                // class that already has it, and the attribute isn't allowed
                // to appear twice on the same type.
                sb.AppendLine($"    public partial class {module.Name}");
                sb.AppendLine("    {");
                sb.AppendLine($"#line {module.BodyStartLine} \"{linePath}\"");
                sb.AppendLine($"        {transformedBody}");
                sb.AppendLine("#line hidden");
                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}"); // close namespace

            return sb.ToString();
        }

        private static string NormalizeLinePath(string filePath)
        {
            return (filePath ?? string.Empty).Replace('\\', '/');
        }
    }
}
