using ReactiveUITK.Core;
using ReactiveUITK.Samples.FunctionalComponents;
using UnityEngine;
using UnityEngine.UIElements;

namespace ReactiveUITK.Samples.Showcase.Runtime
{
    [RequireComponent(typeof(RootRenderer))]
    public class RuntimeUitkxDemoBootstrap : MonoBehaviour
    {
        [SerializeField]
        private UIDocument uiDocument;
        private RootRenderer rootRenderer;

        private void Awake()
        {
            rootRenderer = GetComponent<RootRenderer>();
            if (rootRenderer == null || uiDocument == null || uiDocument.rootVisualElement == null)
            {
                Debug.LogError("RuntimeUitkxDemoBootstrap: Missing RootRenderer or UIDocument");
                return;
            }
            rootRenderer.Initialize(uiDocument.rootVisualElement);
            // UitkxCounterFunc.Render is generated by the UITKX source generator
            // from UitkxCounterFunc.uitkx — same calling convention as a hand-written Func component.
            rootRenderer.Render(V.Func(UitkxCounterFunc.Render));
        }
    }
}
