// <auto-generated/>
// ═══════════════════════════════════════════════════════════════════
//  ReactiveUITK.SourceGenerator  —  PHASE 2 PLACEHOLDER
//  Source  : C:\Yanivs\GameDev\UnityComponents\Assets\ReactiveUIToolKit\Samples\Test.uitkx
// ───────────────────────────────────────────────────────────────────
//  Directives:
//    @namespace  MyApp.UI
//    @component  Test
//    @props      (none)
//    @key        (none)
// ───────────────────────────────────────────────────────────────────
//  Parse result: 1 root node(s), 0 error(s)
//  Root nodes:
//    <MyButton> (0 child(ren))
// ───────────────────────────────────────────────────────────────────
//  Next: Phase 3 — PropsResolver, Phase 4 — CSharpEmitter
// ═══════════════════════════════════════════════════════════════════
