export const EXAMPLE_UITKX = `@namespace MyGame.UI
@using UnityEngine.UIElements

component PlayerCard {
  @props { PlayerInfo player }

  var healthColor = player.Health > player.MaxHealth / 2
    ? PlayerCardStyles.HealthGreen
    : PlayerCardStyles.DamageRed;

  return (
    <VisualElement>
      <Label text={player.Name} />
      <Label text={PlayerCardUtils.FormatHealth(player.Health, player.MaxHealth)}
             style:color={healthColor} />
      <Label text={PlayerCardUtils.RankLabel(player.Rank)} />
    </VisualElement>
  );
}`

export const EXAMPLE_GENERATED_CLASS = `// Auto-generated by the source generator (simplified):
namespace MyGame.UI                    // ← from @namespace
{
    public partial class PlayerCard    // ← from component name
    {
        public static VisualElement Render(PlayerInfo player) { ... }
    }
}`

export const EXAMPLE_DIRECTORY = `Assets/
  UI/
    PlayerCard/
      PlayerCard.uitkx          ← component template
      PlayerCard.styles.cs      ← optional: style constants & helpers
      PlayerCard.types.cs       ← optional: enums, structs, DTOs
      PlayerCard.utils.cs       ← optional: pure helper functions`

export const EXAMPLE_STYLES = `// PlayerCard.styles.cs
using UnityEngine.UIElements;

namespace MyGame.UI
{
    public static class PlayerCardStyles
    {
        public static readonly StyleColor HealthGreen = new(new Color(0.2f, 0.8f, 0.3f));
        public static readonly StyleColor DamageRed   = new(new Color(0.9f, 0.2f, 0.2f));
        public static readonly StyleLength AvatarSize  = new(64);
    }
}`

export const EXAMPLE_TYPES = `// PlayerCard.types.cs
namespace MyGame.UI
{
    public enum PlayerRank { Bronze, Silver, Gold, Diamond }

    public readonly struct PlayerInfo
    {
        public string Name { get; init; }
        public int Health { get; init; }
        public int MaxHealth { get; init; }
        public PlayerRank Rank { get; init; }
    }
}`

export const EXAMPLE_UTILS = `// PlayerCard.utils.cs
namespace MyGame.UI
{
    public static class PlayerCardUtils
    {
        public static string FormatHealth(int current, int max)
            => $"{current} / {max} HP";

        public static string RankLabel(PlayerRank rank) => rank switch
        {
            PlayerRank.Diamond => "★ Diamond",
            PlayerRank.Gold    => "● Gold",
            PlayerRank.Silver  => "○ Silver",
            _                  => "· Bronze",
        };
    }
}`

export const EXAMPLE_PARTIAL = `// PlayerCard.extra.cs — extending the generated partial class
namespace MyGame.UI                    // ← must match @namespace
{
    public partial class PlayerCard    // ← must match component name
    {
        // Add fields, methods, or interfaces to the generated class
        private static readonly Color GoldColor = new(1f, 0.84f, 0f);
    }
}`
