export const EXAMPLE_UITKX = `@namespace MyGame.UI
@using UnityEngine
@using static ReactiveUITK.Props.Typed.StyleKeys

component PlayerCard(PlayerInfo player) {
  var healthColor = player.Health > player.MaxHealth / 2
    ? HealthGreen
    : DamageRed;

  return (
    <VisualElement>
      <Label text={player.Name} />
      <Label text={FormatHealth(player.Health, player.MaxHealth)}
             style={new Style { (Color, healthColor) }} />
      <Label text={RankLabel(player.Rank)} />
    </VisualElement>
  );
}`

export const EXAMPLE_GENERATED_CLASS = `// Auto-generated by the source generator (simplified):
namespace MyGame.UI                    // ← from @namespace
{
    public partial class PlayerCard    // ← from component name
    {
        public static VisualElement Render(PlayerInfo player) { ... }
    }
}`

export const EXAMPLE_DIRECTORY = `Assets/
  UI/
    PlayerCard/
      PlayerCard.uitkx           ← component
      PlayerCard.hooks.uitkx     ← custom hooks (optional)
      PlayerCard.style.uitkx     ← styles module (optional)
      PlayerCard.utils.uitkx     ← utilities module (optional)`

export const EXAMPLE_HOOKS = `// PlayerCard.hooks.uitkx
@namespace MyGame.UI

hook usePlayerAnimation(PlayerInfo player) -> (float, bool) {
  var (opacity, setOpacity) = useState(1f);
  var (isFlashing, setFlashing) = useState(false);

  useEffect(() => {
    if (player.Health <= 0) {
      setFlashing(true);
      setOpacity(0.5f);
    }
    return null;
  }, player.Health);

  return (opacity, isFlashing);
}`

export const EXAMPLE_STYLES = `// PlayerCard.style.uitkx
@namespace MyGame.UI

module PlayerCard {
  public static readonly Color HealthGreen = new(0.2f, 0.8f, 0.3f);
  public static readonly Color DamageRed   = new(0.9f, 0.2f, 0.2f);
  public static readonly float AvatarSize  = 64f;

  public static Style CardStyle => new Style {
    (FlexDirection, "row"),
    (Padding, Px(8)),
    (BackgroundColor, Hex("#1a1a2e"))
  };
}`

export const EXAMPLE_TYPES = `// PlayerCard.types.uitkx
@namespace MyGame.UI

module PlayerCard {
  public enum PlayerRank { Bronze, Silver, Gold, Diamond }

  public readonly struct PlayerInfo {
    public string Name { get; init; }
    public int Health { get; init; }
    public int MaxHealth { get; init; }
    public PlayerRank Rank { get; init; }
  }
}`

export const EXAMPLE_UTILS = `// PlayerCard.utils.uitkx
@namespace MyGame.UI

module PlayerCard {
  public static string FormatHealth(int current, int max)
    => $"{current} / {max} HP";

  public static string RankLabel(PlayerRank rank) => rank switch {
    PlayerRank.Diamond => "★ Diamond",
    PlayerRank.Gold    => "● Gold",
    PlayerRank.Silver  => "○ Silver",
    _                  => "· Bronze",
  };
}`

export const EXAMPLE_STANDALONE = `// SharedColors.uitkx — standalone module, not tied to a specific component
@namespace MyGame.UI

module SharedColors {
  public static readonly Color Gold = new(1f, 0.84f, 0f);
  public static readonly Color Silver = new(0.75f, 0.75f, 0.75f);
}`
