export const EXAMPLE_UITKX = `import { usePlayerAnimation } from "./PlayerCard.hooks"
import { HealthGreen, DamageRed, CardStyle } from "./PlayerCard.style"
import { FormatHealth, RankLabel } from "./PlayerCard.utils"

export VirtualNode PlayerCard(PlayerInfo player) {
  var healthColor = player.Health > player.MaxHealth / 2
    ? HealthGreen
    : DamageRed;

  return (
    <VisualElement style={CardStyle}>
      <Label text={player.Name} />
      <Label text={FormatHealth(player.Health, player.MaxHealth)}
             style={new Style { (Color, healthColor) }} />
      <Label text={RankLabel(player.Rank)} />
    </VisualElement>
  );
}`

export const EXAMPLE_GENERATED_CLASS = `// Auto-generated by the source generator (simplified):
namespace MyGame.UI.PlayerCard.PlayerCard    // ← file-keyed: folders + FILE STEM
{
    public partial class PlayerCard          // ← 'export' → public; no export → internal
    {
        public static VirtualNode Render(PlayerInfo player) { ... }
    }
}
// Each companion file is its OWN module with its own namespace — its members live on a
// per-file __Exports container and are brought in by the imports above (the legacy
// same-name partial-class merge is deprecated: UITKX2107).`

export const EXAMPLE_DIRECTORY = `Assets/
  UI/
    PlayerCard/
      PlayerCard.uitkx           ← component
      PlayerCard.hooks.uitkx     ← custom hooks (optional)
      PlayerCard.style.uitkx     ← style values (optional)
      PlayerCard.utils.uitkx     ← utility functions (optional)`

export const EXAMPLE_HOOKS = `// PlayerCard.hooks.uitkx
export (float, bool) usePlayerAnimation(PlayerInfo player) {
  var (opacity, setOpacity) = useState(1f);
  var (isFlashing, setFlashing) = useState(false);

  useEffect(() => {
    if (player.Health <= 0) {
      setFlashing(true);
      setOpacity(0.5f);
    }
    return null;
  }, player.Health);

  return (opacity, isFlashing);
}`

export const EXAMPLE_STYLES = `// PlayerCard.style.uitkx — plain value exports, no wrapper
export Color HealthGreen = new(0.2f, 0.8f, 0.3f);
export Color DamageRed   = new(0.9f, 0.2f, 0.2f);
export float AvatarSize  = 64f;

export Style CardStyle = new Style {
  (FlexDirection, "row"),
  (Padding, Px(8)),
  (BackgroundColor, Hex("#1a1a2e"))
};`

export const EXAMPLE_TYPES = `// Nested types (enums, structs, classes) have no plain-declaration form —
// declare them in a hand-written .cs beside the components (ambient C# is never
// policed), or keep a legacy module file through the deprecation window:
// PlayerCardTypes.cs
namespace MyGame.UI {
  public enum PlayerRank { Bronze, Silver, Gold, Diamond }

  public readonly struct PlayerInfo {
    public string Name { get; init; }
    public int Health { get; init; }
    public int MaxHealth { get; init; }
    public PlayerRank Rank { get; init; }
  }
}`

export const EXAMPLE_UTILS = `// PlayerCard.utils.uitkx — plain function exports
export string FormatHealth(int current, int max)
  => $"{current} / {max} HP";

export string RankLabel(PlayerRank rank) => rank switch {
  PlayerRank.Diamond => "★ Diamond",
  PlayerRank.Gold    => "● Gold",
  PlayerRank.Silver  => "○ Silver",
  _                  => "· Bronze",
};`

export const EXAMPLE_STANDALONE = `// SharedColors.uitkx — any file's exports are importable anywhere in the asmdef
export Color Gold = new(1f, 0.84f, 0f);
export Color Silver = new(0.75f, 0.75f, 0.75f);

// consumers:
//   import { Gold, Silver } from "../shared/SharedColors"
//   import * as SharedColors from "../shared/SharedColors"   // then SharedColors.Gold`
