#if UNITY_EDITOR
using System;
using System.IO;
using UnityEditor;

namespace ReactiveUITK.Editor
{
    /// <summary>
    /// Watches for any .uitkx asset change and forces Unity to recompile scripts.
    ///
    /// WHY THIS IS NEEDED
    /// ──────────────────
    /// Unity only triggers Roslyn (and therefore source generators) when a .cs
    /// file changes.  Saving a .uitkx file alone does not cause a recompile, so
    /// the source generator would never see the updated content.
    ///
    /// HOW IT WORKS
    /// ────────────
    /// Whenever one or more .uitkx files are imported / saved / deleted / moved,
    /// this postprocessor writes a fresh timestamp into a tiny stub .cs file
    /// (UITKX_GeneratorTrigger.cs).  Because that .cs file changes, Unity
    /// schedules a recompilation which re-runs the source generator and picks up
    /// the latest .uitkx content.
    ///
    /// The stub file is written via <c>EditorApplication.delayCall</c> so it
    /// executes outside the current import callback, avoiding any risk of a
    /// recursive import loop.
    /// </summary>
    public sealed class UitkxChangeWatcher : AssetPostprocessor
    {
        // Path relative to the project root (same folder as this file)
        private const string TriggerAssetPath =
            "Assets/ReactiveUIToolKit/Editor/UITKX_GeneratorTrigger.cs";

        private static void OnPostprocessAllAssets(
            string[] importedAssets,
            string[] deletedAssets,
            string[] movedAssets,
            string[] movedFromAssetPaths
        )
        {
            if (
                !AnyUitkxFile(importedAssets)
                && !AnyUitkxFile(deletedAssets)
                && !AnyUitkxFile(movedAssets)
                && !AnyUitkxFile(movedFromAssetPaths)
            )
                return;

            // Defer the write to avoid executing inside the import callback.
            EditorApplication.delayCall += WriteTriggerFile;
        }

        private static void WriteTriggerFile()
        {
            string absolutePath = Path.GetFullPath(TriggerAssetPath);

            string content =
                "// <auto-generated/>\n"
                + "// This file is rewritten by UitkxChangeWatcher each time a\n"
                + "// .uitkx file is saved, forcing Unity to recompile and re-run\n"
                + "// the ReactiveUITK source generator. Do not edit.\n"
                + $"// Last trigger: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss.fff} UTC\n"
                + "namespace ReactiveUITK.Editor.Generated { }\n";

            File.WriteAllText(absolutePath, content);
            AssetDatabase.ImportAsset(TriggerAssetPath, ImportAssetOptions.ForceUpdate);
        }

        private static bool AnyUitkxFile(string[] paths)
        {
            foreach (string p in paths)
                if (p.EndsWith(".uitkx", StringComparison.OrdinalIgnoreCase))
                    return true;
            return false;
        }
    }
}
#endif
