#if UNITY_EDITOR
using System;
using System.IO;
using UnityEditor;
using UnityEditor.Compilation;
using UnityEngine;

namespace ReactiveUITK.Editor
{
    /// <summary>
    /// Watches for any .uitkx asset change and forces Unity to recompile scripts.
    ///
    /// WHY THIS IS NEEDED
    /// ──────────────────
    /// Unity only triggers Roslyn (and therefore source generators) when a .cs
    /// file changes.  Saving a .uitkx file alone does not cause a recompile, so
    /// the source generator would never see the updated content.
    ///
    /// HOW IT WORKS
    /// ────────────
    /// Whenever one or more .uitkx files are imported / saved / deleted / moved,
    /// this postprocessor writes a fresh timestamp into a tiny stub .cs file
    /// (UITKX_GeneratorTrigger.cs).  Because that .cs file changes, Unity
    /// schedules a recompilation which re-runs the source generator and picks up
    /// the latest .uitkx content.
    ///
    /// The stub file is written via <c>EditorApplication.delayCall</c> so it
    /// executes outside the current import callback, avoiding any risk of a
    /// recursive import loop.
    /// </summary>
    public sealed class UitkxChangeWatcher : AssetPostprocessor
    {
        // Written into the consuming project's own Assets/ folder so it works
        // both when the package lives in Assets/ (dev) and when it is UPM-
        // installed under Packages/ (read-only in consumer projects).
        private const string TriggerRelativePath = "ReactiveUITK/UITKX_GeneratorTrigger.cs";
        private static string TriggerAssetPath => "Assets/" + TriggerRelativePath;

        private static void OnPostprocessAllAssets(
            string[] importedAssets,
            string[] deletedAssets,
            string[] movedAssets,
            string[] movedFromAssetPaths
        )
        {
            if (
                !AnyUitkxFile(importedAssets)
                && !AnyUitkxFile(deletedAssets)
                && !AnyUitkxFile(movedAssets)
                && !AnyUitkxFile(movedFromAssetPaths)
            )
                return;

            // Defer the write to avoid executing inside the import callback.
            EditorApplication.delayCall += WriteTriggerFile;

            // Sync asset registry entries for changed .uitkx files.
            var imported = importedAssets;
            EditorApplication.delayCall += () => UitkxAssetRegistrySync.SyncChangedFiles(imported);
        }

        private static void WriteTriggerFile()
        {
            // Build the absolute path under Application.dataPath so the
            // directory is always writable regardless of how the package is
            // installed (Assets/ vs Packages/).
            string triggerDir = Path.Combine(Application.dataPath, "ReactiveUITK");
            if (!Directory.Exists(triggerDir))
                Directory.CreateDirectory(triggerDir);

            string absolutePath = Path.Combine(triggerDir, "UITKX_GeneratorTrigger.cs");

            string content =
                "// <auto-generated/>\n"
                + "// This file is rewritten by UitkxChangeWatcher each time a\n"
                + "// .uitkx file is saved, forcing Unity to recompile and re-run\n"
                + "// the ReactiveUITK source generator. Do not edit.\n"
                + $"// Last trigger: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss.fff} UTC\n"
                + "namespace ReactiveUITK.Editor.Generated { }\n";

            File.WriteAllText(absolutePath, content);

            // ImportAsset tells Unity this .cs changed, scheduling a recompile.
            AssetDatabase.ImportAsset(TriggerAssetPath, ImportAssetOptions.ForceUpdate);

            // Request a script compilation so Roslyn re-reads AdditionalTexts
            // (.uitkx files) for the source generator. We deliberately do NOT
            // pass RequestScriptCompilationOptions.CleanBuildCache here: that
            // wipes Roslyn's incremental compilation cache and forces every
            // analyzer/source generator in the project to run from cold,
            // which on a fresh HMR Stop produced a 30-40 second stall even on
            // tiny projects. The trigger-file write above already invalidates
            // the .cs side of the cache; Roslyn's AdditionalTextsProvider is
            // content-hashed and will pick up modified .uitkx files via
            // normal incremental recompilation.
            CompilationPipeline.RequestScriptCompilation();
        }

        private static bool AnyUitkxFile(string[] paths)
        {
            foreach (string p in paths)
                if (p.EndsWith(".uitkx", StringComparison.OrdinalIgnoreCase))
                    return true;
            return false;
        }
    }
}
#endif
