using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Text.RegularExpressions;
using System.Threading;
using Microsoft.CodeAnalysis;

namespace ReactiveUITK.SourceGenerator
{
    /// <summary>
    /// Entry point for the UITKX Roslyn Source Generator.
    ///
    /// Registered as an IIncrementalGenerator so Unity only re-runs the pipeline
    /// for files that have actually changed — essential for Unity's frequent
    /// recompilation cycles.
    ///
    /// PIPELINE (Phase 1 — skeleton, not yet wired to real parser/emitter):
    ///   AdditionalTextsProvider (.uitkx files)
    ///     → Combine with CompilationProvider (for PropsResolver in Phase 3)
    ///     → UitkxPipeline.Run  (parse + resolve + emit)
    ///     → RegisterSourceOutput
    ///
    /// The .uitkx files reach this generator as AdditionalTexts because the
    /// UitkxCsprojPostprocessor (Editor assembly) injects an <AdditionalFiles>
    /// element for every .uitkx file into each Unity-generated .csproj.
    /// Unity's compilation pipeline reads those entries and passes the files here.
    /// </summary>
    [Generator]
    public sealed class UitkxGenerator : IIncrementalGenerator
    {
        // Belt-and-suspenders: ensure the assembly resolver is registered as soon
        // as the generator type is loaded, regardless of [ModuleInitializer] support.
        // This fires on ALL runtimes (Mono, CoreCLR) before Initialize() is called.
        static UitkxGenerator() => LanguageLibResolver.EnsureRegistered();

        // Emitted once per assembly to confirm the generator DLL loaded.
        private static readonly DiagnosticDescriptor s_generatorAlive = new DiagnosticDescriptor(
            id: "UITKX0000",
            title: "ReactiveUITK.SourceGenerator is active",
            messageFormat: "ReactiveUITK.SourceGenerator loaded for assembly '{0}'. "
                + "Found {1} .uitkx file(s) via disk scan.",
            category: "ReactiveUITK.SourceGenerator",
            defaultSeverity: DiagnosticSeverity.Warning,
            isEnabledByDefault: true
        );

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // ── Unconditional marker: confirms DLL loaded for every assembly ───
            context.RegisterPostInitializationOutput(static ctx =>
            {
                ctx.AddSource(
                    "UITKX_Loaded.g.cs",
                    "// <auto-generated/>\n"
                        + "// ReactiveUITK.SourceGenerator is loaded and running.\n"
                );
            });

            // ── (A) Collect .uitkx additional texts ────────────────────────────
            // Including these in the incremental pipeline means Roslyn will
            // re-run RegisterSourceOutput whenever a .uitkx file is added,
            // removed, or its content changes — even if no .cs files changed.
            IncrementalValueProvider<System.Collections.Immutable.ImmutableArray<AdditionalText>> uitkxTexts =
                context
                    .AdditionalTextsProvider.Where(static f =>
                        f.Path.EndsWith(".uitkx", StringComparison.OrdinalIgnoreCase)
                    )
                    .Collect();

            // ── (B) Locate project root ────────────────────────────────────────
            // Strategy 1 (Unity runtime): Unity passes {assembly}.UnityAdditionalFile.txt
            //   as /additionalfile: — its content is the project root path.
            // Strategy 2 (IDE / VS / Rider): walk up from a syntax tree file until
            //   we find a directory containing an "Assets" sub-folder.
            IncrementalValueProvider<string?> projectRoot = context
                .AdditionalTextsProvider.Where(static f =>
                    f.Path.EndsWith("UnityAdditionalFile.txt", StringComparison.OrdinalIgnoreCase)
                )
                .Collect()
                .Combine(context.CompilationProvider)
                .Select(
                    static (pair, ct) =>
                    {
                        foreach (var txt in pair.Left)
                        {
                            string? content = txt.GetText(ct)?.ToString()?.Trim();
                            if (!string.IsNullOrEmpty(content) && Directory.Exists(content))
                                return content;
                        }
                        foreach (var tree in pair.Right.SyntaxTrees)
                        {
                            // Unity's csproj can contain relative Compile paths;
                            // resolve to absolute so the "Assets" ancestor walk works.
                            string treePath = tree.FilePath;
                            if (!string.IsNullOrEmpty(treePath)
                                && !Path.IsPathRooted(treePath))
                            {
                                try { treePath = Path.GetFullPath(treePath); }
                                catch { /* ignore resolution failures */ }
                            }

                            string? dir = Path.GetDirectoryName(treePath);
                            while (!string.IsNullOrEmpty(dir))
                            {
                                if (Directory.Exists(Path.Combine(dir, "Assets")))
                                    return dir;
                                dir = Path.GetDirectoryName(dir);
                            }
                        }
                        return null;
                    }
                );

            // ── (C) Combine all three inputs ───────────────────────────────────
            // Changing any of: project root, .uitkx file contents, or compilation
            // will cause RegisterSourceOutput to re-run.
            var combined = projectRoot.Combine(uitkxTexts).Combine(context.CompilationProvider);

            // ── (D) Run the pipeline ───────────────────────────────────────────
            context.RegisterSourceOutput(
                combined,
                static (spc, pair) =>
                {
                    string? root = pair.Left.Left;
                    System.Collections.Immutable.ImmutableArray<AdditionalText> uitkxFiles =
                        pair.Left.Right;
                    Compilation compilation = pair.Right;
                    string assemblyName = compilation.AssemblyName ?? "unknown";
                    CancellationToken ct = spc.CancellationToken;

                    var results = new List<UitkxPipelineResult>();

                    // ── Pre-scan: build the set of component type names from all .uitkx
                    // files so that PropsResolver can suppress UITKX0008 for peer components
                    // that exist in this batch but are not yet compiled into the Roslyn
                    // snapshot (Roslyn source generators cannot see types generated in the
                    // same pass via GetTypeByMetadataName).
                    var peerNamesBuilder      = ImmutableHashSet.CreateBuilder<string>(StringComparer.Ordinal);
                    var peerPropsNamesBuilder = ImmutableHashSet.CreateBuilder<string>(StringComparer.Ordinal);
                    foreach (var txt in uitkxFiles)
                    {
                        ct.ThrowIfCancellationRequested();
                        if (IsInsideIgnoredFolder(txt.Path))
                            continue;
                        string? src = txt.GetText(ct)?.ToString();
                        if (src == null)
                            continue;
                        string? name = ExtractComponentName(src);
                        if (name != null)
                        {
                            peerNamesBuilder.Add(name);
                            if (HasFunctionStyleParams(src))
                                peerPropsNamesBuilder.Add(name);
                        }
                    }
                    ImmutableHashSet<string> peerComponentNames      = peerNamesBuilder.ToImmutable();
                    ImmutableHashSet<string> peerPropsComponentNames = peerPropsNamesBuilder.ToImmutable();

                    // ── Primary path: use AdditionalTexts (incremental-cache-aware) ─
                    // The .uitkx files are injected as <AdditionalFiles> by
                    // UitkxCsprojPostprocessor, so they arrive here as AdditionalTexts.
                    foreach (var txt in uitkxFiles)
                    {
                        ct.ThrowIfCancellationRequested();
                        if (IsInsideIgnoredFolder(txt.Path))
                            continue;
                        string? source = txt.GetText(ct)?.ToString();
                        if (source == null)
                            continue;
                        results.Add(UitkxPipeline.Run(source, txt.Path, compilation, ct, peerComponentNames, peerPropsComponentNames));
                    }

                    // ── Fallback path: disk scan ───────────────────────────────────
                    // Used when UitkxCsprojPostprocessor has not yet run (first install
                    // or fresh project) and no .uitkx AdditionalTexts are available.
                    if (results.Count == 0 && !string.IsNullOrEmpty(root))
                    {
                        string assetsDir = Path.Combine(root, "Assets");
                        if (Directory.Exists(assetsDir))
                        {
                            var diskFiles = Directory.GetFiles(
                                assetsDir, "*.uitkx", SearchOption.AllDirectories);

                            // Pre-scan for peer component names (same as the AdditionalTexts path)
                            var diskPeerBuilder      = ImmutableHashSet.CreateBuilder<string>(StringComparer.Ordinal);
                            var diskPeerPropsBuilder = ImmutableHashSet.CreateBuilder<string>(StringComparer.Ordinal);
                            foreach (string fp in diskFiles)
                            {
                                if (IsInsideIgnoredFolder(fp)) continue;
                                string raw = File.ReadAllText(fp);
                                string? n = ExtractComponentName(raw);
                                if (n != null)
                                {
                                    diskPeerBuilder.Add(n);
                                    if (HasFunctionStyleParams(raw))
                                        diskPeerPropsBuilder.Add(n);
                                }
                            }
                            ImmutableHashSet<string> diskPeerNames      = diskPeerBuilder.ToImmutable();
                            ImmutableHashSet<string> diskPeerPropsNames = diskPeerPropsBuilder.ToImmutable();

                            foreach (string filePath in diskFiles)
                            {
                                ct.ThrowIfCancellationRequested();
                                if (IsInsideIgnoredFolder(filePath))
                                    continue;
                                string source = File.ReadAllText(filePath);
                                results.Add(UitkxPipeline.Run(source, filePath, compilation, ct, diskPeerNames, diskPeerPropsNames));
                            }
                        }
                    }

                    // UITKX0001 — confirms generator ran for this assembly
                    spc.ReportDiagnostic(
                        Diagnostic.Create(
                            s_generatorAlive,
                            Location.None,
                            assemblyName,
                            results.Count
                        )
                    );

                    foreach (var result in results)
                    {
                        foreach (var diag in result.Diagnostics)
                            spc.ReportDiagnostic(diag);
                        if (result.Source is not null)
                            spc.AddSource(result.HintName, result.Source);
                    }
                }
            );
        }

        private static bool IsInsideIgnoredFolder(string path)
        {
            foreach (
                string part in path.Split(
                    new[] { Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar }
                )
            )
            {
                if (part.EndsWith("~", StringComparison.Ordinal))
                    return true;
            }
            return false;
        }

        // Matches the component-name declaration in a .uitkx file in both styles:
        //   function style:  component FooBarFunc {
        //   directive style: @component FooBarFunc
        private static readonly Regex s_componentNameRe = new Regex(
            @"(?:^component\s+|@component\s+)([A-Z][a-zA-Z0-9_]*)",
            RegexOptions.Multiline | RegexOptions.Compiled
        );

        // Matches a function-style component that declares at least one typed param:
        //   component FooBar(type param = default) {
        // Used to distinguish props-bearing components from no-params ones so that
        // PropsResolver only generates a typed V.Func<T> call when a Props class
        // will actually be emitted for the peer component.
        private static readonly Regex s_funcParamsRe = new Regex(
            @"^component\s+[A-Z][a-zA-Z0-9_]*\s*\(\s*[a-zA-Z]",
            RegexOptions.Multiline | RegexOptions.Compiled
        );

        /// <summary>
        /// Quickly extracts the declared component type name from raw .uitkx source text.
        /// Returns null if no component declaration is found.
        /// </summary>
        private static string? ExtractComponentName(string source)
        {
            var m = s_componentNameRe.Match(source);
            return m.Success ? m.Groups[1].Value : null;
        }

        /// <summary>
        /// Returns true when the source declares a function-style component with at
        /// least one typed param — i.e. a <c>XxxProps</c> class will be generated.
        /// </summary>
        private static bool HasFunctionStyleParams(string source)
            => s_funcParamsRe.IsMatch(source);
    }
}
