using System;
using System.Collections.Generic;
using System.IO;
using System.Threading;
using Microsoft.CodeAnalysis;

namespace ReactiveUITK.SourceGenerator
{
    /// <summary>
    /// Entry point for the UITKX Roslyn Source Generator.
    ///
    /// Registered as an IIncrementalGenerator so Unity only re-runs the pipeline
    /// for files that have actually changed — essential for Unity's frequent
    /// recompilation cycles.
    ///
    /// PIPELINE (Phase 1 — skeleton, not yet wired to real parser/emitter):
    ///   AdditionalTextsProvider (.uitkx files)
    ///     → Combine with CompilationProvider (for PropsResolver in Phase 3)
    ///     → UitkxPipeline.Run  (parse + resolve + emit)
    ///     → RegisterSourceOutput
    ///
    /// The .uitkx files reach this generator as AdditionalTexts because the
    /// UitkxCsprojPostprocessor (Editor assembly) injects an <AdditionalFiles>
    /// element for every .uitkx file into each Unity-generated .csproj.
    /// Unity's compilation pipeline reads those entries and passes the files here.
    /// </summary>
    [Generator]
    public sealed class UitkxGenerator : IIncrementalGenerator
    {
        // Emitted once per assembly to confirm the generator DLL loaded.
        private static readonly DiagnosticDescriptor s_generatorAlive = new DiagnosticDescriptor(
            id: "UITKX0000",
            title: "ReactiveUITK.SourceGenerator is active",
            messageFormat: "ReactiveUITK.SourceGenerator loaded for assembly '{0}'. "
                + "Found {1} .uitkx file(s) via disk scan.",
            category: "ReactiveUITK.SourceGenerator",
            defaultSeverity: DiagnosticSeverity.Warning,
            isEnabledByDefault: true
        );

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // ── Unconditional marker: confirms DLL loaded for every assembly ───
            context.RegisterPostInitializationOutput(static ctx =>
            {
                ctx.AddSource(
                    "UITKX_Loaded.g.cs",
                    "// <auto-generated/>\n"
                        + "// ReactiveUITK.SourceGenerator is loaded and running.\n"
                );
            });

            // ── (A) Collect .uitkx additional texts ────────────────────────────
            // Including these in the incremental pipeline means Roslyn will
            // re-run RegisterSourceOutput whenever a .uitkx file is added,
            // removed, or its content changes — even if no .cs files changed.
            IncrementalValueProvider<System.Collections.Immutable.ImmutableArray<AdditionalText>> uitkxTexts =
                context
                    .AdditionalTextsProvider.Where(static f =>
                        f.Path.EndsWith(".uitkx", StringComparison.OrdinalIgnoreCase)
                    )
                    .Collect();

            // ── (B) Locate project root ────────────────────────────────────────
            // Strategy 1 (Unity runtime): Unity passes {assembly}.UnityAdditionalFile.txt
            //   as /additionalfile: — its content is the project root path.
            // Strategy 2 (IDE / VS / Rider): walk up from a syntax tree file until
            //   we find a directory containing an "Assets" sub-folder.
            IncrementalValueProvider<string?> projectRoot = context
                .AdditionalTextsProvider.Where(static f =>
                    f.Path.EndsWith("UnityAdditionalFile.txt", StringComparison.OrdinalIgnoreCase)
                )
                .Collect()
                .Combine(context.CompilationProvider)
                .Select(
                    static (pair, ct) =>
                    {
                        foreach (var txt in pair.Left)
                        {
                            string? content = txt.GetText(ct)?.ToString()?.Trim();
                            if (!string.IsNullOrEmpty(content) && Directory.Exists(content))
                                return content;
                        }
                        foreach (var tree in pair.Right.SyntaxTrees)
                        {
                            string? dir = Path.GetDirectoryName(tree.FilePath);
                            while (!string.IsNullOrEmpty(dir))
                            {
                                if (Directory.Exists(Path.Combine(dir, "Assets")))
                                    return dir;
                                dir = Path.GetDirectoryName(dir);
                            }
                        }
                        return null;
                    }
                );

            // ── (C) Combine all three inputs ───────────────────────────────────
            // Changing any of: project root, .uitkx file contents, or compilation
            // will cause RegisterSourceOutput to re-run.
            var combined = projectRoot.Combine(uitkxTexts).Combine(context.CompilationProvider);

            // ── (D) Run the pipeline ───────────────────────────────────────────
            context.RegisterSourceOutput(
                combined,
                static (spc, pair) =>
                {
                    string? root = pair.Left.Left;
                    System.Collections.Immutable.ImmutableArray<AdditionalText> uitkxFiles =
                        pair.Left.Right;
                    Compilation compilation = pair.Right;
                    string assemblyName = compilation.AssemblyName ?? "unknown";
                    CancellationToken ct = spc.CancellationToken;

                    var results = new List<UitkxPipelineResult>();

                    // ── Primary path: use AdditionalTexts (incremental-cache-aware) ─
                    // The .uitkx files are injected as <AdditionalFiles> by
                    // UitkxCsprojPostprocessor, so they arrive here as AdditionalTexts.
                    foreach (var txt in uitkxFiles)
                    {
                        ct.ThrowIfCancellationRequested();
                        if (IsInsideIgnoredFolder(txt.Path))
                            continue;
                        string? source = txt.GetText(ct)?.ToString();
                        if (source == null)
                            continue;
                        results.Add(UitkxPipeline.Run(source, txt.Path, compilation, ct));
                    }

                    // ── Fallback path: disk scan ───────────────────────────────────
                    // Used when UitkxCsprojPostprocessor has not yet run (first install
                    // or fresh project) and no .uitkx AdditionalTexts are available.
                    if (results.Count == 0 && !string.IsNullOrEmpty(root))
                    {
                        string assetsDir = Path.Combine(root, "Assets");
                        if (Directory.Exists(assetsDir))
                        {
                            foreach (
                                string filePath in Directory.GetFiles(
                                    assetsDir,
                                    "*.uitkx",
                                    SearchOption.AllDirectories
                                )
                            )
                            {
                                ct.ThrowIfCancellationRequested();
                                if (IsInsideIgnoredFolder(filePath))
                                    continue;
                                string source = File.ReadAllText(filePath);
                                results.Add(UitkxPipeline.Run(source, filePath, compilation, ct));
                            }
                        }
                    }

                    // UITKX0001 — confirms generator ran for this assembly
                    spc.ReportDiagnostic(
                        Diagnostic.Create(
                            s_generatorAlive,
                            Location.None,
                            assemblyName,
                            results.Count
                        )
                    );

                    foreach (var result in results)
                    {
                        foreach (var diag in result.Diagnostics)
                            spc.ReportDiagnostic(diag);
                        if (result.Source is not null)
                            spc.AddSource(result.HintName, result.Source);
                    }
                }
            );
        }

        private static bool IsInsideIgnoredFolder(string path)
        {
            foreach (
                string part in path.Split(
                    new[] { Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar }
                )
            )
            {
                if (part.EndsWith("~", StringComparison.Ordinal))
                    return true;
            }
            return false;
        }
    }
}
