using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using Microsoft.CodeAnalysis;
using ReactiveUITK.Language;
using ReactiveUITK.Language.Parser;

namespace ReactiveUITK.SourceGenerator
{
    /// <summary>
    /// Entry point for the UITKX Roslyn Source Generator.
    ///
    /// Registered as an IIncrementalGenerator so Unity only re-runs the pipeline
    /// for files that have actually changed — essential for Unity's frequent
    /// recompilation cycles.
    ///
    /// PIPELINE (Phase 1 — skeleton, not yet wired to real parser/emitter):
    ///   AdditionalTextsProvider (.uitkx files)
    ///     → Combine with CompilationProvider (for PropsResolver in Phase 3)
    ///     → UitkxPipeline.Run  (parse + resolve + emit)
    ///     → RegisterSourceOutput
    ///
    /// The .uitkx files reach this generator as AdditionalTexts because the
    /// UitkxCsprojPostprocessor (Editor assembly) injects an <AdditionalFiles>
    /// element for every .uitkx file into each Unity-generated .csproj.
    /// Unity's compilation pipeline reads those entries and passes the files here.
    /// </summary>
    [Generator]
    public sealed class UitkxGenerator : IIncrementalGenerator
    {
        // Belt-and-suspenders: ensure the assembly resolver is registered as soon
        // as the generator type is loaded, regardless of [ModuleInitializer] support.
        // This fires on ALL runtimes (Mono, CoreCLR) before Initialize() is called.
        static UitkxGenerator() => LanguageLibResolver.EnsureRegistered();

        // Emitted once per assembly to confirm the generator DLL loaded.
        // U-22: verified (empirically, across this audit's own dotnet build/test output)
        // that this fires as a real build-log warning on every compile — pure informational
        // noise ("the generator is alive") does not warrant Warning severity, which
        // surfaces in build summaries and the Error List panel like a real issue.
        private static readonly DiagnosticDescriptor s_generatorAlive = new DiagnosticDescriptor(
            id: "UITKX0000",
            title: "ReactiveUITK.SourceGenerator is active",
            messageFormat: "ReactiveUITK.SourceGenerator loaded for assembly '{0}'. "
                + "Found {1} .uitkx file(s) via disk scan.",
            category: "ReactiveUITK.SourceGenerator",
            defaultSeverity: DiagnosticSeverity.Info,
            isEnabledByDefault: true
        );

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // ── Unconditional marker: confirms DLL loaded for every assembly ───
            context.RegisterPostInitializationOutput(static ctx =>
            {
                ctx.AddSource(
                    "UITKX_Loaded.g.cs",
                    "// <auto-generated/>\n"
                        + "// ReactiveUITK.SourceGenerator is loaded and running.\n"
                );

                // ── ModuleInitializerAttribute polyfill (editor-only) ──────
                // The SG emits [ModuleInitializer] methods only inside the
                // editor-only UITKX Fast Refresh block (see CSharpEmitter --
                // the RefreshRuntime.Register call site is wrapped in
                // #if UNITY_EDITOR). Player builds have no [ModuleInitializer]
                // consumer, so the polyfill itself is also wrapped in
                // #if UNITY_EDITOR to keep player assemblies free of any
                // attribute type that doesn't ship with their target TFM.
                // The inner #if !NET5_0_OR_GREATER guard remains as
                // future-proofing for Unity moving to .NET 5+.
                ctx.AddSource(
                    "UITKX_ModuleInitializerPolyfill.g.cs",
                    "// <auto-generated/>\n"
                        + "#if UNITY_EDITOR\n"
                        + "#if !NET5_0_OR_GREATER\n"
                        + "namespace System.Runtime.CompilerServices\n"
                        + "{\n"
                        + "    [global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false)]\n"
                        + "    internal sealed class ModuleInitializerAttribute : global::System.Attribute { }\n"
                        + "}\n"
                        + "#endif\n"
                        + "#endif // UNITY_EDITOR\n"
                );
            });

            // ── (A) Collect .uitkx additional texts ────────────────────────────
            // Including these in the incremental pipeline means Roslyn will
            // re-run RegisterSourceOutput whenever a .uitkx file is added,
            // removed, or its content changes — even if no .cs files changed.
            IncrementalValueProvider<System.Collections.Immutable.ImmutableArray<AdditionalText>> uitkxTexts =
                context
                    .AdditionalTextsProvider.Where(static f =>
                        f.Path.EndsWith(".uitkx", StringComparison.OrdinalIgnoreCase)
                    )
                    .Collect();

            // ── (B) Locate project root ────────────────────────────────────────
            // Strategy 1 (Unity runtime): Unity passes {assembly}.UnityAdditionalFile.txt
            //   as /additionalfile: — its content is the project root path.
            // Strategy 2 (IDE / VS / Rider): walk up from a syntax tree file until
            //   we find a directory containing an "Assets" sub-folder.
            IncrementalValueProvider<string?> projectRoot = context
                .AdditionalTextsProvider.Where(static f =>
                    f.Path.EndsWith("UnityAdditionalFile.txt", StringComparison.OrdinalIgnoreCase)
                )
                .Collect()
                .Combine(context.CompilationProvider)
                .Select(
                    static (pair, ct) =>
                    {
                        foreach (var txt in pair.Left)
                        {
                            string? content = txt.GetText(ct)?.ToString()?.Trim();
                            if (!string.IsNullOrEmpty(content) && Directory.Exists(content))
                                return content;
                        }
                        foreach (var tree in pair.Right.SyntaxTrees)
                        {
                            // Unity's csproj can contain relative Compile paths;
                            // resolve to absolute so the "Assets" ancestor walk works.
                            string treePath = tree.FilePath;
                            if (!string.IsNullOrEmpty(treePath)
                                && !Path.IsPathRooted(treePath))
                            {
                                try { treePath = Path.GetFullPath(treePath); }
                                catch { /* ignore resolution failures */ }
                            }

                            string? dir = Path.GetDirectoryName(treePath);
                            while (!string.IsNullOrEmpty(dir))
                            {
                                if (Directory.Exists(Path.Combine(dir, "Assets")))
                                    return dir;
                                dir = Path.GetDirectoryName(dir);
                            }
                        }
                        return null;
                    }
                );

            // ── (C) Combine all three inputs ───────────────────────────────────
            // Changing any of: project root, .uitkx file contents, or compilation
            // will cause RegisterSourceOutput to re-run.
            var combined = projectRoot.Combine(uitkxTexts).Combine(context.CompilationProvider);

            // ── (D) Run the pipeline ───────────────────────────────────────────
            context.RegisterSourceOutput(
                combined,
                static (spc, pair) =>
                {
                    string? root = pair.Left.Left;
                    System.Collections.Immutable.ImmutableArray<AdditionalText> uitkxFiles =
                        pair.Left.Right;
                    Compilation compilation = pair.Right;
                    string assemblyName = compilation.AssemblyName ?? "unknown";
                    CancellationToken ct = spc.CancellationToken;

                    var results = new List<UitkxPipelineResult>();

                    // ── Pre-scan: build the set of component type names from all .uitkx
                    // files so that PropsResolver can suppress UITKX0008 for peer components
                    // that exist in this batch but are not yet compiled into the Roslyn
                    // snapshot (Roslyn source generators cannot see types generated in the
                    // same pass via GetTypeByMetadataName).
                    var peerComponentsBuilder = ImmutableArray.CreateBuilder<PeerComponentInfo>();
                    var peerHookContainersBuilder = ImmutableArray.CreateBuilder<PeerHookContainerInfo>();
                    var peerModulesBuilder = ImmutableArray.CreateBuilder<PeerModuleInfo>();
                    var peerExportsBuilder = ImmutableArray.CreateBuilder<PeerExportsInfo>();
                    var importsByFile = new List<(string File, List<(string[] Names, string Specifier)> Imports)>();
                    foreach (var txt in uitkxFiles)
                    {
                        ct.ThrowIfCancellationRequested();
                        if (IsInsideIgnoredFolder(txt.Path))
                            continue;
                        if (!UitkxPipeline.IsOwnedByCompilation(txt.Path, compilation.AssemblyName))
                            continue;
                        string? src = ReadUitkxSource(txt, ct);
                        if (src == null)
                            continue;
                        CollectPeerComponentInfos(src, txt.Path, peerComponentsBuilder);
                        if (TryBuildPeerHookContainerInfo(src, txt.Path, out var hookInfo))
                            peerHookContainersBuilder.Add(hookInfo);
                        CollectPeerModuleInfos(src, txt.Path, peerModulesBuilder);
                        if (TryBuildPeerExportsInfo(src, txt.Path, out var exportsInfo))
                            peerExportsBuilder.Add(exportsInfo);
                        importsByFile.Add((txt.Path, ExtractImportsForCycle(src)));
                    }
                    ImmutableArray<PeerComponentInfo> peerComponents =
                        peerComponentsBuilder.ToImmutable();
                    ImmutableArray<PeerHookContainerInfo> peerHookContainers =
                        peerHookContainersBuilder.ToImmutable();
                    ImmutableArray<PeerModuleInfo> peerModules =
                        peerModulesBuilder.ToImmutable();
                    ImmutableArray<PeerExportsInfo> peerExports =
                        peerExportsBuilder.ToImmutable();
                    var valueCycles = UitkxFeatureFlags.StrictImports
                        ? BuildValueCycleMap(importsByFile, peerHookContainers, peerModules, peerExports)
                        : null;

                    // ── Primary path: use AdditionalTexts (incremental-cache-aware) ─
                    // The .uitkx files are injected as <AdditionalFiles> by
                    // UitkxCsprojPostprocessor, so they arrive here as AdditionalTexts.
                    // Content is read disk-authoritative (see ReadUitkxSource) so a
                    // stale AdditionalText from Unity doesn't produce stale output.
                    foreach (var txt in uitkxFiles)
                    {
                        ct.ThrowIfCancellationRequested();
                        if (IsInsideIgnoredFolder(txt.Path))
                            continue;
                        string? source = ReadUitkxSource(txt, ct);
                        if (source == null)
                            continue;
                        results.Add(UitkxPipeline.Run(source, txt.Path, compilation, ct, peerComponents, peerHookContainers, peerModules, valueCycles, peerExports));
                    }

                    // ── Fallback path: disk scan ───────────────────────────────────
                    // Used when UitkxCsprojPostprocessor has not yet run (first install
                    // or fresh project) and no .uitkx AdditionalTexts are available.
                    if (results.Count == 0 && !string.IsNullOrEmpty(root))
                    {
                        string assetsDir = Path.Combine(root, "Assets");
                        if (Directory.Exists(assetsDir))
                        {
                            var diskFiles = Directory.GetFiles(
                                assetsDir, "*.uitkx", SearchOption.AllDirectories);

                            // Pre-scan for peer component names (same as the AdditionalTexts path)
                            var diskPeerBuilder = ImmutableArray.CreateBuilder<PeerComponentInfo>();
                            var diskHookBuilder = ImmutableArray.CreateBuilder<PeerHookContainerInfo>();
                            var diskModuleBuilder = ImmutableArray.CreateBuilder<PeerModuleInfo>();
                            var diskExportsBuilder = ImmutableArray.CreateBuilder<PeerExportsInfo>();
                            var diskImportsByFile = new List<(string File, List<(string[] Names, string Specifier)> Imports)>();
                            foreach (string fp in diskFiles)
                            {
                                if (IsInsideIgnoredFolder(fp)) continue;
                                if (!UitkxPipeline.IsOwnedByCompilation(fp, compilation.AssemblyName))
                                    continue;
                                string raw = File.ReadAllText(fp);
                                CollectPeerComponentInfos(raw, fp, diskPeerBuilder);
                                if (TryBuildPeerHookContainerInfo(raw, fp, out var hookInfo))
                                    diskHookBuilder.Add(hookInfo);
                                CollectPeerModuleInfos(raw, fp, diskModuleBuilder);
                                if (TryBuildPeerExportsInfo(raw, fp, out var exportsInfo))
                                    diskExportsBuilder.Add(exportsInfo);
                                diskImportsByFile.Add((fp, ExtractImportsForCycle(raw)));
                            }
                            ImmutableArray<PeerComponentInfo> diskPeerComponents =
                                diskPeerBuilder.ToImmutable();
                            ImmutableArray<PeerHookContainerInfo> diskPeerHookContainers =
                                diskHookBuilder.ToImmutable();
                            ImmutableArray<PeerModuleInfo> diskPeerModules =
                                diskModuleBuilder.ToImmutable();
                            ImmutableArray<PeerExportsInfo> diskPeerExports =
                                diskExportsBuilder.ToImmutable();
                            var diskValueCycles = UitkxFeatureFlags.StrictImports
                                ? BuildValueCycleMap(diskImportsByFile, diskPeerHookContainers, diskPeerModules, diskPeerExports)
                                : null;

                            foreach (string filePath in diskFiles)
                            {
                                ct.ThrowIfCancellationRequested();
                                if (IsInsideIgnoredFolder(filePath))
                                    continue;
                                string source = File.ReadAllText(filePath);
                                results.Add(UitkxPipeline.Run(source, filePath, compilation, ct, diskPeerComponents, diskPeerHookContainers, diskPeerModules, diskValueCycles, diskPeerExports));
                            }
                        }
                    }

                    // UITKX0000 — confirms generator ran for this assembly (U-22: comment
                    // previously said "UITKX0001", which doesn't match s_generatorAlive's id)
                    spc.ReportDiagnostic(
                        Diagnostic.Create(
                            s_generatorAlive,
                            Location.None,
                            assemblyName,
                            results.Count
                        )
                    );

                    foreach (var result in results)
                    {
                        foreach (var diag in result.Diagnostics)
                            spc.ReportDiagnostic(diag);
                        if (result.Source is not null)
                            spc.AddSource(result.HintName, result.Source);
                        // Mixed-decl / multi-component files emit one additional
                        // standalone compilation unit per extra section (see
                        // UitkxPipelineResult.ExtraSources) — each merges as a
                        // partial across CUs, so they must NOT be concatenated.
                        if (!result.ExtraSources.IsDefaultOrEmpty)
                            foreach (var (extraHint, extraSource) in result.ExtraSources)
                                spc.AddSource(extraHint, extraSource);
                    }
                }
            );
        }

        private static bool IsInsideIgnoredFolder(string path)
        {
            foreach (
                string part in path.Split(
                    new[] { Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar }
                )
            )
            {
                if (part.EndsWith("~", StringComparison.Ordinal))
                    return true;
            }
            return false;
        }

        // Reads the .uitkx source for generation, treating the ON-DISK file as the
        // source of truth. Under Unity, the AdditionalText handed to the (reused)
        // driver on a .uitkx-ONLY edit with Play/HMR off can lag the file on disk:
        // the incremental pipeline re-runs (the Compilation changes every compile),
        // but reads the STALE AdditionalText content, so the regenerated component
        // still shows the pre-edit markup — a full reimport / Library clear / any
        // .cs edit "fixes" it only because those force Unity to re-read the file.
        // The generator's incremental cache itself is correct (verified with a
        // reused-driver ReplaceAdditionalText probe: an AdditionalText content
        // change DOES invalidate and re-emit), so the defect is the stale content
        // Unity delivers, and the fix belongs here: when the on-disk content differs
        // from what Unity provided, disk wins.
        //
        // Safe for the IDE (VS/Rider) path: those hosts update the AdditionalText to
        // the saved buffer before compiling, so disk == AdditionalText and this is a
        // no-op. On any read failure (file locked mid-save, path gone) it falls back
        // to the AdditionalText content, and the next compile self-corrects.
        private static string? ReadUitkxSource(AdditionalText txt, CancellationToken ct)
        {
            string? additional = txt.GetText(ct)?.ToString();
            try
            {
                if (!string.IsNullOrEmpty(txt.Path) && File.Exists(txt.Path))
                {
                    string disk = File.ReadAllText(txt.Path);
                    if (!string.Equals(disk, additional, StringComparison.Ordinal))
                        return disk;
                }
            }
            catch
            {
                // Keep the AdditionalText content on any disk-read failure.
            }
            return additional;
        }

        // Matches the component-name declaration in a .uitkx file:
        //   component FooBarFunc {
        private static readonly Regex s_componentNameRe = new Regex(
            @"^component\s+([A-Z][a-zA-Z0-9_]*)",
            RegexOptions.Multiline | RegexOptions.Compiled
        );

        // Matches a function-style component that declares at least one typed param:
        //   component FooBar(type param = default) {
        // Used to distinguish props-bearing components from no-params ones so that
        // PropsResolver only generates a typed V.Func<T> call when a Props class
        // will actually be emitted for the peer component.
        private static readonly Regex s_funcParamsRe = new Regex(
            @"^component\s+[A-Z][a-zA-Z0-9_]*\s*\(\s*[a-zA-Z]",
            RegexOptions.Multiline | RegexOptions.Compiled
        );

        /// <summary>
        /// Quickly extracts the declared component type name from raw .uitkx source text.
        /// Returns null if no component declaration is found.
        /// </summary>
        private static string? ExtractComponentName(string source)
        {
            var m = s_componentNameRe.Match(source);
            return m.Success ? m.Groups[1].Value : null;
        }

        /// <summary>
        /// Returns true when the source declares a function-style component with at
        /// least one typed param — i.e. a <c>XxxProps</c> class will be generated.
        /// </summary>
        private static bool HasFunctionStyleParams(string source)
            => s_funcParamsRe.IsMatch(source);

        /// <summary>
        /// Adds a <see cref="PeerComponentInfo"/> for EVERY component declared in the file
        /// (not just the first) so the shared resolver + strict-import tables see all of a
        /// multi-component file's components. Registering only the first left references to a
        /// same-file sibling component resolving as unknown (false UITKX0008) and made those
        /// siblings un-importable / invisible to the value-cycle detector.
        /// </summary>
        private static void CollectPeerComponentInfos(
            string source,
            string filePath,
            ImmutableArray<PeerComponentInfo>.Builder builder
        )
        {
            var throwawayDiags = new List<ParseDiagnostic>();
            var ds = DirectiveParser.Parse(source, filePath, throwawayDiags);
            // All components in one file share the file's effective namespace (resolved
            // through the same seam the emitter uses, so peer namespaces match the emit).
            string? ns = UitkxPipeline.ResolveEffectiveNamespace(ds, filePath);
            if (string.IsNullOrEmpty(ns))
                return;

            if (!ds.ComponentDeclarations.IsDefaultOrEmpty)
            {
                foreach (var cd in ds.ComponentDeclarations)
                {
                    if (string.IsNullOrEmpty(cd.Name))
                        continue;
                    builder.Add(new PeerComponentInfo(
                        cd.Name,
                        ns!,
                        !cd.FunctionParams.IsDefaultOrEmpty,
                        cd.FunctionParams.IsDefault
                            ? ImmutableArray<FunctionParam>.Empty
                            : cd.FunctionParams)
                    {
                        SourceFilePath = filePath,
                        IsExported = cd.IsExported,
                    });
                }
                return;
            }

            // Fallback: a parser path (or the regex-only extractor) set ComponentName
            // without populating ComponentDeclarations. Preserves the pre-multi behavior.
            string? name = ds.ComponentName ?? ExtractComponentName(source);
            if (string.IsNullOrEmpty(name))
                return;
            builder.Add(new PeerComponentInfo(
                name!,
                ns!,
                !ds.FunctionParams.IsDefaultOrEmpty,
                ds.FunctionParams.IsDefault
                    ? ImmutableArray<FunctionParam>.Empty
                    : ds.FunctionParams)
            {
                SourceFilePath = filePath,
                IsExported = true,
            });
        }

        private static bool TryBuildPeerHookContainerInfo(
            string source,
            string filePath,
            out PeerHookContainerInfo hookInfo
        )
        {
            var throwawayDiags = new List<ParseDiagnostic>();
            var ds = DirectiveParser.Parse(source, filePath, throwawayDiags);
            string? hookNs = UitkxPipeline.ResolveEffectiveNamespace(ds, filePath);
            if (string.IsNullOrEmpty(hookNs))
            {
                hookInfo = default!;
                return false;
            }

            // New-mode file (ES-modules campaign, U-06): hooks are plain declarations on the
            // per-file __Exports container; the container-name convention changes, the peer
            // table shape does not.
            if (!ds.UsesLegacySyntax)
            {
                var newModeHooks = ImmutableArray.CreateBuilder<string>();
                if (!ds.MemberDeclarations.IsDefaultOrEmpty)
                    foreach (var m in ds.MemberDeclarations)
                        if (m.Kind == DeclKind.Hook && m.IsExported)
                            newModeHooks.Add(m.Name);
                if (newModeHooks.Count == 0)
                {
                    hookInfo = default!;
                    return false;
                }
                hookInfo = new PeerHookContainerInfo(hookNs!, "__Exports")
                {
                    SourceFilePath = filePath,
                    ExportedHookNames = newModeHooks.ToImmutable(),
                };
                return true;
            }

            if (ds.HookDeclarations.IsDefaultOrEmpty)
            {
                hookInfo = default!;
                return false;
            }
            var exportedHooks = ImmutableArray.CreateBuilder<string>();
            foreach (var h in ds.HookDeclarations)
                if (h.IsExported)
                    exportedHooks.Add(h.Name);

            hookInfo = new PeerHookContainerInfo(
                hookNs!,
                Emitter.HookEmitter.DeriveContainerClassName(filePath)
            )
            {
                SourceFilePath = filePath,
                ExportedHookNames = exportedHooks.ToImmutable(),
            };
            return true;
        }

        /// <summary>
        /// Builds the per-file export surface for a NEW-MODE (plain-declaration) peer (ES-modules
        /// campaign, U-03). Legacy files never get an entry.
        /// </summary>
        private static bool TryBuildPeerExportsInfo(
            string source,
            string filePath,
            out PeerExportsInfo exportsInfo
        )
        {
            var throwawayDiags = new List<ParseDiagnostic>();
            var ds = DirectiveParser.Parse(source, filePath, throwawayDiags);
            string? ns = UitkxPipeline.ResolveEffectiveNamespace(ds, filePath);
            if (ds.UsesLegacySyntax || string.IsNullOrEmpty(ns)
                || (ds.MemberDeclarations.IsDefaultOrEmpty && ds.ComponentDeclarations.IsDefaultOrEmpty))
            {
                exportsInfo = default!;
                return false;
            }

            var exportedComponents = ImmutableArray.CreateBuilder<string>();
            if (!ds.ComponentDeclarations.IsDefaultOrEmpty)
                foreach (var c in ds.ComponentDeclarations)
                    if (c.IsExported)
                        exportedComponents.Add(c.Name);

            exportsInfo = new PeerExportsInfo(
                filePath,
                ns!,
                ds.MemberDeclarations.IsDefaultOrEmpty
                    ? ImmutableArray<MemberDeclaration>.Empty
                    : ds.MemberDeclarations,
                exportedComponents.ToImmutable(),
                ds.DefaultExportName);
            return true;
        }

        /// <summary>
        /// Appends a <see cref="PeerModuleInfo"/> for every <c>module</c> declared in the file
        /// (import/export grammar, leg 3, M6b/strict). Module edges had no peer table before.
        /// </summary>
        // Regex import scan for the value-cycle graph (import/export grammar §6): cheaper than a full
        // parse in the pre-scan, and the value-cycle only needs specifier + names.
        private static readonly Regex s_importScanRe = new Regex(
            @"^\s*import\s*\{([^}]*)\}\s*from\s*""([^""]+)""",
            RegexOptions.Multiline | RegexOptions.CultureInvariant | RegexOptions.Compiled
        );

        // Star / default import forms also create value-cycle edges (audit M5): a `* as X`
        // binding eager-references the whole target container; a default import can bind a
        // member. Sentinel names "*" / "\0default" mark them for BuildValueCycleMap.
        private static readonly Regex s_importScanStarRe = new Regex(
            @"^\s*import\s*\*\s*as\s+\w+\s+from\s*""([^""]+)""",
            RegexOptions.Multiline | RegexOptions.CultureInvariant | RegexOptions.Compiled
        );
        private static readonly Regex s_importScanDefaultRe = new Regex(
            @"^\s*import\s+\w+\s+from\s*""([^""]+)""",
            RegexOptions.Multiline | RegexOptions.CultureInvariant | RegexOptions.Compiled
        );

        internal const string CycleStarSentinel = "*";
        internal const string CycleDefaultSentinel = "\0default";

        private static List<(string[] Names, string Specifier)> ExtractImportsForCycle(string source)
        {
            // Blank comments BEFORE the regex so a commented-out `import { … } from "…"`
            // never injects a phantom value-cycle edge (→ spurious UITKX2306). String
            // literals are preserved so the real specifier is still captured — a plain
            // ScrubNonCode would blank the specifier string and drop real edges instead.
            source = ScrubCommentsPreservingStrings(source);
            var result = new List<(string[], string)>();
            foreach (Match m in s_importScanRe.Matches(source))
            {
                string[] names = m.Groups[1].Value.Split(',');
                for (int i = 0; i < names.Length; i++)
                {
                    names[i] = names[i].Trim();
                    // `a as b` edges key on the ORIGINAL (exported) name.
                    int asIdx = names[i].IndexOf(" as ", StringComparison.Ordinal);
                    if (asIdx > 0)
                        names[i] = names[i].Substring(0, asIdx).Trim();
                }
                result.Add((names, m.Groups[2].Value));
            }
            foreach (Match m in s_importScanStarRe.Matches(source))
                result.Add((new[] { CycleStarSentinel }, m.Groups[1].Value));
            foreach (Match m in s_importScanDefaultRe.Matches(source))
                result.Add((new[] { CycleDefaultSentinel }, m.Groups[1].Value));
            return result;
        }

        /// <summary>
        /// Blanks <c>//</c> and <c>/* */</c> comments while leaving string/char literals
        /// intact (so <c>//</c> or <c>import</c> inside a <c>"…"</c> is never mistaken for a
        /// comment or a real import). Length- and line-preserving. Used by the import
        /// pre-scan, which must ignore commented-out imports but keep real specifier strings.
        /// </summary>
        private static string ScrubCommentsPreservingStrings(string source)
        {
            var sb = new StringBuilder(source);
            int i = 0, n = source.Length;
            while (i < n)
            {
                char c = source[i];
                if (c == '/' && i + 1 < n && source[i + 1] == '/')
                {
                    int start = i;
                    i += 2;
                    while (i < n && source[i] != '\n') i++;
                    for (int k = start; k < i && k < sb.Length; k++)
                        if (!char.IsWhiteSpace(sb[k])) sb[k] = ' ';
                    continue;
                }
                if (c == '/' && i + 1 < n && source[i + 1] == '*')
                {
                    int start = i;
                    int close = source.IndexOf("*/", i + 2, StringComparison.Ordinal);
                    i = close >= 0 ? close + 2 : n;
                    for (int k = start; k < i && k < sb.Length; k++)
                        if (!char.IsWhiteSpace(sb[k])) sb[k] = ' ';
                    continue;
                }
                int before = i;
                if (CSharpLexFacts.TrySkipStringOrCharLiteral(source, n, ref i) && i > before)
                    continue; // preserve the literal verbatim
                i++;
            }
            return sb.ToString();
        }

        private static string NormPath(string? p) => (p ?? string.Empty).Replace('\\', '/').TrimEnd('/');

        /// <summary>
        /// Value-import cycle detection for the build (import/export grammar §6): edges are import
        /// relationships where the imported name is a HOOK or MODULE (components load lazily and are
        /// exempt). Returns a map filePath → 2306 chain message for every file that is part of a cycle.
        /// </summary>
        private static Dictionary<string, string> BuildValueCycleMap(
            List<(string File, List<(string[] Names, string Specifier)> Imports)> importsByFile,
            ImmutableArray<PeerHookContainerInfo> peerHooks,
            ImmutableArray<PeerModuleInfo> peerModules,
            ImmutableArray<PeerExportsInfo> peerExports = default)
        {
            var result = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

            // (normalized target path + '\0' + name) for every hook/module export = a value symbol.
            var valueExports = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (var ph in peerHooks)
                if (!string.IsNullOrEmpty(ph.SourceFilePath))
                    foreach (var n in ph.ExportedHookNames)
                        valueExports.Add(NormPath(ph.SourceFilePath) + "\0" + n);
            foreach (var pm in peerModules)
                if (pm.IsExported && !string.IsNullOrEmpty(pm.SourceFilePath))
                    valueExports.Add(NormPath(pm.SourceFilePath) + "\0" + pm.Name);

            // New-mode files (audit M5): every exported MEMBER is a value symbol — values
            // eager-init via static field initializers; hooks/utils match the legacy graph's
            // over-approximation. Components stay exempt (lazy). Star imports edge on the
            // whole container; default imports edge only when the default is a member.
            var starValueTargets = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var defaultValueTargets = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            if (!peerExports.IsDefaultOrEmpty)
                foreach (var pe in peerExports)
                {
                    if (string.IsNullOrEmpty(pe.SourceFilePath))
                        continue;
                    string peN = NormPath(pe.SourceFilePath);
                    if (!pe.Members.IsDefaultOrEmpty)
                        foreach (var m in pe.Members)
                            if (m.IsExported)
                            {
                                valueExports.Add(peN + "\0" + m.Name);
                                starValueTargets.Add(peN);
                                if (pe.DefaultExportName != null && m.Name == pe.DefaultExportName)
                                    defaultValueTargets.Add(peN);
                            }
                }

            if (valueExports.Count == 0)
                return result;

            var edges = new Dictionary<string, IReadOnlyList<string>>(StringComparer.OrdinalIgnoreCase);
            foreach (var (file, imports) in importsByFile)
            {
                if (imports.Count == 0)
                    continue;
                string dir = NormPath(Path.GetDirectoryName(file));
                string? projRoot = ReactiveUITK.Language.AssetPathUtil.GetProjectRoot(file);
                string root = projRoot != null
                    ? NormPath(projRoot + "/" + ReactiveUITK.Language.UitkxConfig.LoadRoot(dir))
                    : dir;

                foreach (var (names, specifier) in imports)
                {
                    string? tgt = ReactiveUITK.Language.ImportResolver.MapSpecifierToPath(dir, specifier, root, out _);
                    if (tgt == null)
                        continue;
                    string tgtN = NormPath(tgt);
                    string key = NormPath(file);
                    // A self-import (specifier resolving back to the importer) is harmless —
                    // the reference stays within the file's own generated container, no
                    // eager-init/TDZ hazard — but a self-edge makes FindCycle report [A,A].
                    // Skip it so it never produces a spurious UITKX2306.
                    if (string.Equals(tgtN, key, StringComparison.OrdinalIgnoreCase))
                        continue;
                    bool isValue = false;
                    foreach (var n in names)
                    {
                        bool hit = n == CycleStarSentinel ? starValueTargets.Contains(tgtN)
                            : n == CycleDefaultSentinel ? defaultValueTargets.Contains(tgtN)
                            : valueExports.Contains(tgtN + "\0" + n);
                        if (hit) { isValue = true; break; }
                    }
                    if (!isValue)
                        continue;
                    if (!edges.TryGetValue(key, out var list))
                        edges[key] = list = new List<string>();
                    ((List<string>)list).Add(tgtN);
                }
            }

            var cycle = ReactiveUITK.Language.UitkxImportGraph.FindCycle(edges);
            if (cycle != null)
            {
                var names = new List<string>(cycle.Count);
                foreach (var c in cycle)
                    names.Add(Path.GetFileName(c));
                string msg = $"value-import cycle: {string.Join(" -> ", names)} (hooks/modules load eagerly — break the chain or move to component refs)";
                foreach (var c in cycle)
                    result[NormPath(c)] = msg;
            }
            return result;
        }

        private static void CollectPeerModuleInfos(
            string source, string filePath, ImmutableArray<PeerModuleInfo>.Builder builder)
        {
            var throwawayDiags = new List<ParseDiagnostic>();
            var ds = DirectiveParser.Parse(source, filePath, throwawayDiags);
            if (ds.ModuleDeclarations.IsDefaultOrEmpty)
                return;
            string? ns = UitkxPipeline.ResolveEffectiveNamespace(ds, filePath);
            if (string.IsNullOrEmpty(ns))
                return;
            foreach (var m in ds.ModuleDeclarations)
                builder.Add(new PeerModuleInfo(m.Name, ns!, m.IsExported) { SourceFilePath = filePath });
        }
    }
}
