#if UNITY_EDITOR
using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;
using ReactiveUITK.EditorSupport;
using ReactiveUITK.Samples.FunctionalComponents;

namespace ReactiveUITK.Samples.Editor
{
    public sealed class EditorUitkxCounterDemoWindow : EditorWindow
    {
        [MenuItem("ReactiveUITK/Demos/Legacy/UITKX Counter Demo (Source Generator)")]
        public static void Open()
        {
            var window = GetWindow<EditorUitkxCounterDemoWindow>("UITKX Counter Demo");
            window.minSize = new Vector2(320f, 240f);
            window.Show();
        }

        private void CreateGUI()
        {
            var host = rootVisualElement;
            host.style.flexGrow = 1f;
            // UitkxCounterFunc.Render is generated by the UITKX source generator
            // from Samples/Components/UitkxCounterFunc.uitkx
            EditorRootRendererUtility.Render(host, V.Func(UitkxCounterFunc.Render));
        }

        private void OnDisable()
        {
            EditorRootRendererUtility.Unmount(rootVisualElement);
        }
    }
}
#endif
